// @generated by scripts/build-edge-astrology.mjs — DO NOT EDIT.
//
// Source: packages/shared/src/astrology/edge-entry.ts and its imports.
// Regenerate: npm run build:edge-astrology
// Verify:     npm run validate:edge-astrology   (runs in CI; fails on drift)
//
// This is the SAME scoring model the web and mobile apps use, bundled for Deno
// so that get-profile-chart can compute a synastry server-side instead of
// publishing the longitudes it would need to compute one in the browser.
// See docs/security-audit-2026-09-07.md, JUNO-01.
//
// Editing this file by hand is pointless: CI regenerates it and compares.
// @ts-nocheck — generated output, type-checked at its source.
/* eslint-disable */

// packages/shared/src/astrology/signs.ts
var ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces"
];
function placementToLongitude(p) {
  const idx = ZODIAC_SIGNS.indexOf(p.sign);
  if (idx < 0) return 0;
  return idx * 30 + p.degree;
}

// packages/shared/src/astrology/stored.ts
function normalizeStoredSign(value) {
  if (typeof value !== "string" || !value) return null;
  const canonical = value.charAt(0).toUpperCase() + value.slice(1).toLowerCase();
  return ZODIAC_SIGNS.includes(canonical) ? canonical : null;
}
function parseStoredPlacement(raw) {
  if (typeof raw !== "object" || raw == null) return null;
  const obj = raw;
  const sign = normalizeStoredSign(obj.sign);
  if (!sign) return null;
  const degree = typeof obj.degree === "number" && Number.isFinite(obj.degree) ? obj.degree : null;
  let longitude = typeof obj.longitude === "number" && Number.isFinite(obj.longitude) ? obj.longitude : null;
  if (longitude != null && (longitude < 0 || longitude >= 360)) {
    longitude = (longitude % 360 + 360) % 360;
  }
  if (longitude == null) {
    if (degree == null) return null;
    longitude = placementToLongitude({ sign, degree });
  }
  return {
    sign,
    degree: degree ?? longitude % 30,
    longitude
  };
}
function parseConfidence(raw) {
  return raw === "high" || raw === "medium" || raw === "low" ? raw : "medium";
}
var INNER_NON_LUMINARY = [
  "mercury",
  "venus",
  "mars",
  "jupiter",
  "saturn"
];
var OUTER = ["uranus", "neptune", "pluto"];
function hydrateStoredChart(raw) {
  if (typeof raw !== "object" || raw == null) return null;
  const obj = raw;
  const planets = typeof obj.planets === "object" && obj.planets != null ? obj.planets : obj;
  const sun = parseStoredPlacement(obj.sun);
  const moon = parseStoredPlacement(obj.moon);
  if (!sun || !moon) return null;
  const inner = {};
  for (const key of INNER_NON_LUMINARY) {
    const p = parseStoredPlacement(planets[key]);
    if (!p) return null;
    inner[key] = p;
  }
  const outer = {
    uranus: null,
    neptune: null,
    pluto: null
  };
  for (const key of OUTER) {
    outer[key] = parseStoredPlacement(planets[key]);
  }
  const rising = parseStoredPlacement(obj.rising);
  const mc = parseStoredPlacement(obj.mc);
  const houses = Array.isArray(obj.houses) && obj.houses.length === 12 && obj.houses.every((h) => typeof h === "number" && Number.isFinite(h)) ? obj.houses : null;
  const coordinates = typeof obj.coordinates === "object" && obj.coordinates != null ? obj.coordinates : {};
  const latitude = typeof coordinates.latitude === "number" && Number.isFinite(coordinates.latitude) ? coordinates.latitude : null;
  const longitude = typeof coordinates.longitude === "number" && Number.isFinite(coordinates.longitude) ? coordinates.longitude : null;
  return {
    sun,
    moon,
    mercury: inner.mercury,
    venus: inner.venus,
    mars: inner.mars,
    jupiter: inner.jupiter,
    saturn: inner.saturn,
    uranus: outer.uranus,
    neptune: outer.neptune,
    pluto: outer.pluto,
    rising,
    mc,
    houses,
    utcInstant: typeof obj.utcInstant === "string" ? obj.utcInstant : "",
    timezone: typeof obj.timezone === "string" ? obj.timezone : "UTC",
    // Legacy rows without a confidence field predate the confidence model;
    // 'high' matches how the mobile facade always treated them.
    confidence: parseConfidence(obj.confidence),
    warnings: [],
    input: {
      date: "",
      time: null,
      timezone: typeof obj.timezone === "string" ? obj.timezone : null,
      latitude,
      longitude
    }
  };
}

// packages/shared/src/astrology/orbs.ts
var BASE_ORBS = {
  conjunction: 8,
  opposition: 8,
  square: 7,
  trine: 7,
  sextile: 5
};
var LUMINARY_ORB_BONUS = 1;
var OUTER_OUTER_ORB_PENALTY = 2;
var MIN_ORB = 1;
var LUMINARIES = /* @__PURE__ */ new Set(["sun", "moon"]);
var OUTER_PLANETS = /* @__PURE__ */ new Set([
  "uranus",
  "neptune",
  "pluto"
]);
function isLuminary(body) {
  return LUMINARIES.has(body);
}
function isOuterPlanet(body) {
  return OUTER_PLANETS.has(body);
}
function resolveMaxOrb(aspect, bodyA, bodyB) {
  let orb = BASE_ORBS[aspect];
  if (bodyA && isLuminary(bodyA) || bodyB && isLuminary(bodyB)) {
    orb += LUMINARY_ORB_BONUS;
  }
  if (bodyA && bodyB && isOuterPlanet(bodyA) && isOuterPlanet(bodyB)) {
    orb -= OUTER_OUTER_ORB_PENALTY;
  }
  return Math.max(MIN_ORB, orb);
}

// packages/shared/src/astrology/aspects.ts
var ASPECT_DEFINITIONS = [
  { name: "conjunction", angle: 0, kind: "intense" },
  { name: "sextile", angle: 60, kind: "harmonious" },
  { name: "square", angle: 90, kind: "challenging" },
  { name: "trine", angle: 120, kind: "harmonious" },
  { name: "opposition", angle: 180, kind: "challenging" }
];
function angularSeparation(long1, long2) {
  return Math.abs(((long1 - long2 + 180) % 360 + 360) % 360 - 180);
}
function detectAspect(long1, long2, bodyA, bodyB) {
  const sep = angularSeparation(long1, long2);
  let best = null;
  for (const def of ASPECT_DEFINITIONS) {
    const orb = Math.abs(sep - def.angle);
    const maxOrb = resolveMaxOrb(def.name, bodyA, bodyB);
    if (orb <= maxOrb && (best == null || orb < best.orb)) {
      best = {
        name: def.name,
        angle: def.angle,
        separation: Math.round(sep * 100) / 100,
        orb: Math.round(orb * 100) / 100,
        maxOrb,
        kind: def.kind
      };
    }
  }
  return best;
}
function aspectCoefficient(aspect) {
  const orbTightness = Math.max(0, 1 - aspect.orb / 10);
  if (aspect.kind === "harmonious") return orbTightness * 1;
  if (aspect.kind === "intense") return orbTightness * 0.6;
  return -orbTightness * 0.5;
}

// packages/shared/src/astrology/scoring.ts
var SCORE_BANDS = [
  { band: "resonant", min: 88 },
  { band: "strong-themes", min: 76 },
  { band: "promising-mix", min: 64 },
  { band: "mixed", min: 52 },
  { band: "different-rhythms", min: 40 },
  { band: "likely-friction", min: 0 }
];
function bandForScore(score) {
  for (const spec of SCORE_BANDS) {
    if (score >= spec.min) return spec.band;
  }
  return "likely-friction";
}
function applyConfidenceCap(rawScore, confidence) {
  const cap = confidence === "high" ? 100 : confidence === "medium" ? 92 : 80;
  return Math.max(0, Math.min(cap, rawScore));
}
function weakestConfidence(a, b) {
  const rank = { high: 2, medium: 1, low: 0 };
  return rank[a] <= rank[b] ? a : b;
}

// packages/shared/src/astrology/version.ts
var SCORING_MODEL_VERSION = 2;

// packages/shared/src/astrology/synastry.ts
var FRAME_WEIGHTS = {
  love: [
    { bodyA: "sun", bodyB: "sun", weight: 1 },
    { bodyA: "moon", bodyB: "moon", weight: 1.1 },
    { bodyA: "sun", bodyB: "moon", weight: 1 },
    { bodyA: "moon", bodyB: "sun", weight: 1 },
    { bodyA: "venus", bodyB: "mars", weight: 1.1 },
    { bodyA: "mars", bodyB: "venus", weight: 1.1 },
    { bodyA: "venus", bodyB: "venus", weight: 0.8 },
    { bodyA: "mercury", bodyB: "mercury", weight: 0.7 },
    { bodyA: "sun", bodyB: "rising", weight: 0.7 },
    { bodyA: "rising", bodyB: "sun", weight: 0.7 },
    { bodyA: "jupiter", bodyB: "jupiter", weight: 0.4 },
    { bodyA: "saturn", bodyB: "saturn", weight: 0.4 }
  ],
  friendship: [
    { bodyA: "sun", bodyB: "sun", weight: 1 },
    { bodyA: "moon", bodyB: "moon", weight: 1 },
    { bodyA: "sun", bodyB: "moon", weight: 0.7 },
    { bodyA: "moon", bodyB: "sun", weight: 0.7 },
    { bodyA: "mercury", bodyB: "mercury", weight: 1.1 },
    { bodyA: "jupiter", bodyB: "jupiter", weight: 1 },
    { bodyA: "venus", bodyB: "venus", weight: 0.7 },
    { bodyA: "mars", bodyB: "mars", weight: 0.5 },
    { bodyA: "sun", bodyB: "jupiter", weight: 0.7 },
    { bodyA: "jupiter", bodyB: "sun", weight: 0.7 }
  ],
  business: [
    { bodyA: "sun", bodyB: "sun", weight: 0.8 },
    { bodyA: "mercury", bodyB: "mercury", weight: 1.1 },
    { bodyA: "mars", bodyB: "saturn", weight: 1 },
    { bodyA: "saturn", bodyB: "mars", weight: 1 },
    { bodyA: "sun", bodyB: "saturn", weight: 1 },
    { bodyA: "saturn", bodyB: "sun", weight: 1 },
    { bodyA: "jupiter", bodyB: "saturn", weight: 0.8 },
    { bodyA: "saturn", bodyB: "jupiter", weight: 0.8 },
    { bodyA: "mercury", bodyB: "jupiter", weight: 0.6 },
    { bodyA: "jupiter", bodyB: "mercury", weight: 0.6 },
    { bodyA: "mars", bodyB: "mars", weight: 0.5 }
  ]
};
function getLongitude(chart, key) {
  const placement = chart[key];
  return placement?.longitude ?? null;
}
function computeFrame(frame, chart1, chart2) {
  const pairs = FRAME_WEIGHTS[frame];
  let weightedSum = 0;
  let totalWeight = 0;
  const aspects = [];
  for (const pair of pairs) {
    const long1 = getLongitude(chart1, pair.bodyA);
    const long2 = getLongitude(chart2, pair.bodyB);
    if (long1 == null || long2 == null) continue;
    totalWeight += pair.weight;
    const aspect = detectAspect(long1, long2, pair.bodyA, pair.bodyB);
    if (!aspect) continue;
    const coef = aspectCoefficient(aspect);
    weightedSum += pair.weight * coef;
    aspects.push({
      ...aspect,
      bodyA: pair.bodyA,
      bodyB: pair.bodyB,
      contribution: Math.round(pair.weight * coef * 1e3) / 1e3
    });
  }
  const ratio = totalWeight > 0 ? weightedSum / totalWeight : 0;
  const rawScore = Math.round(50 + ratio * 40);
  aspects.sort((a, b) => Math.abs(b.contribution) - Math.abs(a.contribution));
  return { rawScore, aspects };
}
var OUTER_PLANETS2 = ["uranus", "neptune", "pluto"];
var INTERPRETIVE_TARGETS = [
  "sun",
  "moon",
  "mercury",
  "venus",
  "mars",
  "rising",
  "mc"
];
function computeInterpretiveAspects(chart1, chart2) {
  const out = [];
  const directions = [
    [chart1, chart2, false],
    [chart2, chart1, true]
  ];
  for (const [outerChart, targetChart, swapped] of directions) {
    for (const outer of OUTER_PLANETS2) {
      const outerLong = getLongitude(outerChart, outer);
      if (outerLong == null) continue;
      for (const target of INTERPRETIVE_TARGETS) {
        const targetLong = getLongitude(targetChart, target);
        if (targetLong == null) continue;
        const aspect = detectAspect(outerLong, targetLong, outer, target);
        if (!aspect) continue;
        out.push({
          ...aspect,
          bodyA: swapped ? target : outer,
          bodyB: swapped ? outer : target,
          contribution: 0
        });
      }
    }
  }
  out.sort(
    (a, b) => a.orb - b.orb || a.bodyA.localeCompare(b.bodyA) || a.bodyB.localeCompare(b.bodyB)
  );
  return out;
}
function computeSynastry(chart1, chart2) {
  const confidence = weakestConfidence(chart1.confidence, chart2.confidence);
  const warningSet = /* @__PURE__ */ new Set();
  chart1.warnings.forEach((w) => warningSet.add(w));
  chart2.warnings.forEach((w) => warningSet.add(w));
  const frames = {};
  Object.keys(FRAME_WEIGHTS).forEach((frame) => {
    const { rawScore, aspects } = computeFrame(frame, chart1, chart2);
    const capped = applyConfidenceCap(rawScore, confidence);
    frames[frame] = {
      frame,
      score: capped,
      band: bandForScore(capped),
      topAspects: aspects.slice(0, 8)
    };
  });
  return {
    confidence,
    warnings: Array.from(warningSet),
    frames,
    interpretiveAspects: computeInterpretiveAspects(chart1, chart2),
    modelVersion: SCORING_MODEL_VERSION
  };
}

// packages/shared/src/astrology/synastry-view.ts
var BAND_TO_UI = {
  resonant: "exceptional",
  "strong-themes": "strong",
  "promising-mix": "promising",
  mixed: "mixed",
  "different-rhythms": "growth",
  "likely-friction": "different"
};
var SYNASTRY_FRAME_ORDER = [
  "love",
  "friendship",
  "business"
];
function toUiBand(engineBand) {
  return BAND_TO_UI[engineBand] ?? "mixed";
}
function hydrateSynastrySide(raw) {
  if (!raw || typeof raw !== "object") return null;
  return hydrateStoredChart(raw);
}
function buildSynastryView(ownChart, otherChart) {
  const mine = hydrateSynastrySide(ownChart);
  const theirs = hydrateSynastrySide(otherChart);
  if (!mine && !theirs) return { source: "sign-rhythm", reason: "missing_both_charts" };
  if (!mine) return { source: "sign-rhythm", reason: "missing_own_chart" };
  if (!theirs) return { source: "sign-rhythm", reason: "missing_other_chart" };
  const result = computeSynastry(mine, theirs);
  const frames = SYNASTRY_FRAME_ORDER.map((frame) => {
    const score = result.frames[frame];
    return {
      frame,
      score: score.score,
      engineBand: score.band,
      band: toUiBand(score.band),
      topAspects: score.topAspects
    };
  });
  return {
    source: "aspects",
    frames,
    // `love` is first in SYNASTRY_FRAME_ORDER; asserting rather than indexing
    // blindly so a reordering cannot silently change the headline.
    headline: frames.find((f) => f.frame === "love") ?? frames[0],
    interpretiveAspects: result.interpretiveAspects,
    confidence: result.confidence,
    // Anything below `high` means one of the two charts could not pin its
    // timezone, or is a legacy row hydrated as `medium` (see parseConfidence).
    // The reader is told, rather than shown a number that looks certain.
    isLimited: result.confidence !== "high",
    warnings: result.warnings,
    modelVersion: result.modelVersion,
    // The "first impressions" pairs need an ascendant on at least one side.
    missingAscendant: mine.rising === null || theirs.rising === null
  };
}
function formatOrb(orb) {
  return `${(Math.round(orb * 10) / 10).toFixed(1)}°`;
}
export {
  SCORING_MODEL_VERSION,
  buildSynastryView,
  formatOrb,
  hydrateStoredChart,
  hydrateSynastrySide
};
