// @generated by scripts/build-edge-tarot.mjs — DO NOT EDIT.
//
// Source: packages/shared/src/tarot/edge-entry.ts and its imports.
// Regenerate: npm run build:edge-tarot
// Verify:     npm run validate:edge-tarot
//
// The premium-tarot-reading edge draws with the EXACT shared engine. This
// bundle exists so the tarot corpus and shuffle can leave the mobile bundle
// (JUNO-06) without the server growing a second, drifting implementation.

// packages/shared/src/tarot/content-en.ts
var NAMES_EN = {
  "major-00": "The Fool",
  "major-01": "The Magician",
  "major-02": "The High Priestess",
  "major-03": "The Empress",
  "major-04": "The Emperor",
  "major-05": "The Hierophant",
  "major-06": "The Lovers",
  "major-07": "The Chariot",
  "major-08": "Strength",
  "major-09": "The Hermit",
  "major-10": "Wheel of Fortune",
  "major-11": "Justice",
  "major-12": "The Hanged Man",
  "major-13": "Death",
  "major-14": "Temperance",
  "major-15": "The Devil",
  "major-16": "The Tower",
  "major-17": "The Star",
  "major-18": "The Moon",
  "major-19": "The Sun",
  "major-20": "Judgement",
  "major-21": "The World",
  "cups-01": "Ace of Cups",
  "cups-02": "Two of Cups",
  "cups-03": "Three of Cups",
  "cups-04": "Four of Cups",
  "cups-05": "Five of Cups",
  "cups-06": "Six of Cups",
  "cups-07": "Seven of Cups",
  "cups-08": "Eight of Cups",
  "cups-09": "Nine of Cups",
  "cups-10": "Ten of Cups",
  "cups-11": "Page of Cups",
  "cups-12": "Knight of Cups",
  "cups-13": "Queen of Cups",
  "cups-14": "King of Cups",
  "wands-01": "Ace of Wands",
  "wands-02": "Two of Wands",
  "wands-03": "Three of Wands",
  "wands-04": "Four of Wands",
  "wands-05": "Five of Wands",
  "wands-06": "Six of Wands",
  "wands-07": "Seven of Wands",
  "wands-08": "Eight of Wands",
  "wands-09": "Nine of Wands",
  "wands-10": "Ten of Wands",
  "wands-11": "Page of Wands",
  "wands-12": "Knight of Wands",
  "wands-13": "Queen of Wands",
  "wands-14": "King of Wands",
  "swords-01": "Ace of Swords",
  "swords-02": "Two of Swords",
  "swords-03": "Three of Swords",
  "swords-04": "Four of Swords",
  "swords-05": "Five of Swords",
  "swords-06": "Six of Swords",
  "swords-07": "Seven of Swords",
  "swords-08": "Eight of Swords",
  "swords-09": "Nine of Swords",
  "swords-10": "Ten of Swords",
  "swords-11": "Page of Swords",
  "swords-12": "Knight of Swords",
  "swords-13": "Queen of Swords",
  "swords-14": "King of Swords",
  "pents-01": "Ace of Pentacles",
  "pents-02": "Two of Pentacles",
  "pents-03": "Three of Pentacles",
  "pents-04": "Four of Pentacles",
  "pents-05": "Five of Pentacles",
  "pents-06": "Six of Pentacles",
  "pents-07": "Seven of Pentacles",
  "pents-08": "Eight of Pentacles",
  "pents-09": "Nine of Pentacles",
  "pents-10": "Ten of Pentacles",
  "pents-11": "Page of Pentacles",
  "pents-12": "Knight of Pentacles",
  "pents-13": "Queen of Pentacles",
  "pents-14": "King of Pentacles"
};
var MEANINGS_EN = {
  // ---------------------------------------------------------------- majors
  "major-00": {
    love: {
      upright: "Something here is unproven, and that may be the point. Beginning without certainty is its own kind of courage.",
      reversed: "A leap can be avoidance wearing good clothes. Worth asking what you would be stepping away from, not only what you would be stepping toward."
    },
    general: {
      upright: "A beginning with no map yet. Not knowing the shape of it is normal at this stage, and often necessary.",
      reversed: "Either the leap is rushed or the hesitation has outlived its usefulness. Notice which one this actually is."
    }
  },
  "major-01": {
    love: {
      upright: "You have more to work with here than you are counting. Attention, honesty and timing are usually the whole toolkit.",
      reversed: "A gap may be opening between what is shown and what is meant — yours or theirs. Easier to name now than later."
    },
    general: {
      upright: "The pieces are already in your hands. This card is about using them rather than gathering more.",
      reversed: "Capability without direction, or a story told more convincingly than it is lived. Worth checking which."
    }
  },
  "major-02": {
    love: {
      upright: "Something is understood here without being said. Trust the reading, and consider saying it out loud anyway.",
      reversed: "You may be talking yourself out of something you already sense. The quiet signal is information too."
    },
    general: {
      upright: "The answer is closer to intuition than analysis right now. Give it a quiet room.",
      reversed: "Noise has crowded out the inner read. Less input, not more, tends to help here."
    }
  },
  "major-03": {
    love: {
      upright: "Warmth and care, and being fed by a connection rather than drained by it. Notice what actually nourishes.",
      reversed: "Giving may have tipped past generosity into self-erasure. Care that empties you is hard to sustain."
    },
    general: {
      upright: "Growth, comfort and creative fullness. Let something be enjoyed rather than optimised.",
      reversed: "Depletion, or a creative block that is really a rest deficit. Refill before pushing."
    }
  },
  "major-04": {
    love: {
      upright: "Structure makes room for softness. Clear agreements often let a connection relax.",
      reversed: "Control can pose as stability. Where has the structure stopped serving the people inside it?"
    },
    general: {
      upright: "Boundaries, order and follow-through. A frame built now can hold weight later.",
      reversed: "Rigidity, or the absence of any frame at all. Both leave you carrying more than you should."
    }
  },
  "major-05": {
    love: {
      upright: "Shared values, and inherited scripts about how love is supposed to look. Some of them are worth keeping.",
      reversed: "A rule you did not choose may be running things. It can be examined."
    },
    general: {
      upright: "Tradition, mentorship, and the wisdom of a path already walked. Borrowing is allowed.",
      reversed: "The convention no longer fits. Departing from it is a choice, not a failure."
    }
  },
  "major-06": {
    love: {
      upright: "Alignment — of values as much as attraction. What you agree about matters as much as what you feel.",
      reversed: "A pull in two directions, or values quietly out of step. Naming the mismatch is kinder than working around it."
    },
    general: {
      upright: "A choice that asks who you actually are, not only what you want.",
      reversed: "A decision made to avoid discomfort tends to come back. Worth looking at what is being dodged."
    }
  },
  "major-07": {
    love: {
      upright: "Moving toward what you want with your eyes open. Direction matters more than intensity here.",
      reversed: "Effort without agreement is pushing rather than pursuing. Worth checking you are both going the same way."
    },
    general: {
      upright: "Momentum and focus. The obstacle is usually attention, not ability.",
      reversed: "Scattered energy, or force applied where patience would do more."
    }
  },
  "major-08": {
    love: {
      upright: "Steadiness without hardness. Staying gentle under pressure is the harder and better skill.",
      reversed: "Self-doubt may be doing the talking. It tends to overstate the danger."
    },
    general: {
      upright: "Courage that looks quiet from the outside. Patience is part of it.",
      reversed: "Depleted patience, or force where softness would have worked. Rest is not a detour."
    }
  },
  "major-09": {
    love: {
      upright: "Distance can be clarifying. Knowing what you want alone tends to make you clearer with someone else.",
      reversed: "Solitude may have curdled into avoidance. Notice the difference between choosing space and hiding in it."
    },
    general: {
      upright: "A step back to hear yourself. The answer often arrives in the quiet.",
      reversed: "Isolation past its usefulness. One conversation may do more than another week of thinking."
    }
  },
  "major-10": {
    love: {
      upright: "A turn in the pattern. Something may be shifting that you did not arrange, and meeting it tends to cost less than bracing against it.",
      reversed: "The timing feels off. Patience often costs less here than pushing."
    },
    general: {
      upright: "Cycles and turning points. A shift may be asking for your attention rather than your resistance.",
      reversed: "Resisting a change you can already feel. This phase moves; notice what it is showing you."
    }
  },
  "major-11": {
    love: {
      upright: "Fairness, and the relief of being straight with each other. Honesty tends to steady a bond.",
      reversed: "An imbalance neither of you has said out loud. It rarely settles on its own."
    },
    general: {
      upright: "Accountability and clear seeing. Weigh it honestly, including your own part.",
      reversed: "Avoiding a consequence, or judging a situation on incomplete information."
    }
  },
  "major-12": {
    love: {
      upright: "A pause that changes the angle. Not acting is sometimes the most useful thing available.",
      reversed: "Stalling dressed up as patience. Worth asking what the waiting is protecting you from."
    },
    general: {
      upright: "Suspension, and a shift in perspective. The view is genuinely different from here.",
      reversed: "Stuck rather than still. A sacrifice that helps no one can be put down."
    }
  },
  "major-13": {
    love: {
      upright: "An ending that makes room. What closes here was probably already finished.",
      reversed: "Holding on past the point where it helps. Letting go is a slow skill."
    },
    general: {
      upright: "Transformation through release. Something completes so something else can start.",
      reversed: "Resisting a change already underway. The delay often costs more than the change would."
    }
  },
  "major-14": {
    love: {
      upright: "Proportion. Neither too much nor too withheld — the middle is doing real work here.",
      reversed: "Extremes, or a blend that has not found its ratio yet. Adjust slowly."
    },
    general: {
      upright: "Balance and patience. Combining opposites takes time, and it is going fine.",
      reversed: "Overcorrection in one direction. Small adjustments tend to beat dramatic ones."
    }
  },
  "major-15": {
    love: {
      upright: "Intensity and attachment, and the question of what keeps you here. Pull is not the same as fit.",
      reversed: "A pattern loosening its hold. Seeing the mechanism is most of the work."
    },
    general: {
      upright: "What binds you — habit, comfort, appetite. Look at the shape of it without shame.",
      reversed: "Loosening a hold you have been under. Freedom here tends to arrive gradually."
    }
  },
  "major-16": {
    love: {
      upright: "A sudden clarity that rearranges things. Uncomfortable, and it may clear space for honesty.",
      reversed: "Avoiding a break that has been building. Truth tends to surface when it is ready, not before."
    },
    general: {
      upright: "A structure gives way and reveals what it was holding up. Collapse can be information.",
      reversed: "Postponing a change that wants to happen. The delay is its own decision."
    }
  },
  "major-17": {
    love: {
      upright: "Hope that has recovered its footing. Something gentle is being rebuilt.",
      reversed: "Faith running low. It tends to return, usually quietly and not on schedule."
    },
    general: {
      upright: "Replenishment and clarity after strain. Keep going gently.",
      reversed: "Discouragement. Worth naming rather than performing optimism over."
    }
  },
  "major-18": {
    love: {
      upright: "Not everything here is visible yet. Some of what you feel may be memory rather than the present.",
      reversed: "Fog lifting. What frightened you may look smaller in daylight."
    },
    general: {
      upright: "Uncertainty and projection. Hold conclusions loosely for now.",
      reversed: "Clarity emerging. Worth separating what was fear from what was fact."
    }
  },
  "major-19": {
    love: {
      upright: "Warmth without effort. Being seen and liking it — worth enjoying rather than analysing.",
      reversed: "Brightness dimmed, or expectation doing the work joy should. It passes."
    },
    general: {
      upright: "Vitality and plain good feeling. Let it be simple.",
      reversed: "A temporary flatness. Not a verdict on anything."
    }
  },
  "major-20": {
    love: {
      upright: "A reckoning with a pattern, and the chance to answer it differently this time.",
      reversed: "Replaying an old verdict on yourself. The evidence may be out of date."
    },
    general: {
      upright: "Awakening and honest review. What have you actually learned?",
      reversed: "Self-criticism standing in for reflection. They are not the same activity."
    }
  },
  "major-21": {
    love: {
      upright: "A sense of completeness — a cycle closing well rather than dramatically.",
      reversed: "Almost finished. The last step tends to be the one that is easiest to skip."
    },
    general: {
      upright: "Wholeness, and a chapter reaching its end. Worth marking before starting the next.",
      reversed: "A loose end keeping the door open. It can be closed deliberately."
    }
  },
  // ------------------------------------------------------------------ cups
  "cups-01": {
    love: {
      upright: "A feeling opening up, still new and a little unguarded. Let it be tender.",
      reversed: "Feeling held back, possibly for good reason. Notice what makes it hard to open."
    },
    general: {
      upright: "An emotional beginning. Something wants to be felt before it is understood.",
      reversed: "Blocked feeling, or a cup you are keeping covered. It keeps."
    }
  },
  "cups-02": {
    love: {
      upright: "Mutual recognition. Two people meeting each other rather than an idea of each other.",
      reversed: "One side may be carrying more of the connection. Worth saying out loud."
    },
    general: {
      upright: "Partnership on equal footing. Reciprocity is the theme.",
      reversed: "An exchange out of balance. Naming it usually helps more than compensating for it."
    }
  },
  "cups-03": {
    love: {
      upright: "Love in company — friends, celebration, being glad together.",
      reversed: "Too much noise around the connection, or a circle you have drifted from."
    },
    general: {
      upright: "Community and shared joy. Being among people is the point.",
      reversed: "Overextended socially, or quietly outside the circle. Both are worth noticing."
    }
  },
  "cups-04": {
    love: {
      upright: "A flatness where interest used to be. Something may be in front of you, unregistered.",
      reversed: "Interest returning after a dull stretch. Worth looking up."
    },
    general: {
      upright: "Contemplation edging into apathy. Worth asking what stopped landing.",
      reversed: "Appetite coming back. The pause did its work."
    }
  },
  "cups-05": {
    love: {
      upright: "Grief for what did not happen. What remains is easy to overlook while you are looking at what spilled.",
      reversed: "Turning toward what is still standing. Slow, and real."
    },
    general: {
      upright: "Loss and disappointment. Give it room, then count what is left.",
      reversed: "Acceptance beginning. Not resolution, but movement."
    }
  },
  "cups-06": {
    love: {
      upright: "Sweetness with a memory in it. The past can be warm without being where you live.",
      reversed: "Nostalgia doing more work than the present. Compare gently."
    },
    general: {
      upright: "Memory, innocence, a kindness returned. Let it be simple.",
      reversed: "An idealised past crowding out what is here."
    }
  },
  "cups-07": {
    love: {
      upright: "Many possibilities, not all of them real. Choose something you can actually touch.",
      reversed: "Clarity after a stretch of imagining. One option is becoming the option."
    },
    general: {
      upright: "Options and fantasy. Ground one of them before choosing.",
      reversed: "Focus arriving. The fog was doing something for you — worth noticing what."
    }
  },
  "cups-08": {
    love: {
      upright: "Walking away from something that no longer feeds you. Brave, and often quiet.",
      reversed: "Staying past your own knowing. Worth asking honestly what leaving would cost."
    },
    general: {
      upright: "Leaving something incomplete because it is not yours to finish.",
      reversed: "Drifting rather than deciding. A direction would help."
    }
  },
  "cups-09": {
    love: {
      upright: "Contentment. Wanting what you have is its own achievement.",
      reversed: "Satisfaction on the surface with something unmet underneath."
    },
    general: {
      upright: "A wish met. Enjoy it before moving the goalpost.",
      reversed: "Having a lot and feeling little. Worth investigating rather than fixing."
    }
  },
  "cups-10": {
    love: {
      upright: "Belonging, and the ordinary happiness that does not photograph well.",
      reversed: "A gap between the picture and the feeling. Worth saying the quiet part."
    },
    general: {
      upright: "Harmony at home and among your people. This is the good part.",
      reversed: "Friction under a settled surface. Small, and not nothing."
    }
  },
  "cups-11": {
    love: {
      upright: "A tender, unpolished message or gesture. Sincerity tends to beat smoothness.",
      reversed: "Feeling running ahead of what has actually happened. Let it catch up."
    },
    general: {
      upright: "Curiosity and a creative nudge. Follow it without a plan.",
      reversed: "Sensitivity with nowhere to put it. Worth making something."
    }
  },
  "cups-12": {
    love: {
      upright: "Romantic momentum — someone leading with feeling, and reading as sincere.",
      reversed: "Charm outpacing substance, or an idea of love larger than the person."
    },
    general: {
      upright: "Following your heart somewhere. Keep one eye open.",
      reversed: "Mood steering the wheel. A day's distance may help."
    }
  },
  "cups-13": {
    love: {
      upright: "Emotional steadiness — someone who can hold feeling without being swept by it.",
      reversed: "Absorbing everyone's weather. Boundaries are a form of care."
    },
    general: {
      upright: "Compassion and depth. Feeling and thinking are cooperating.",
      reversed: "Merged with other people's states. Where do you end?"
    }
  },
  "cups-14": {
    love: {
      upright: "Warmth with a keel. Feeling expressed without flooding anyone.",
      reversed: "Calm on the surface, unspoken underneath. Composure is not the same as honesty."
    },
    general: {
      upright: "Emotional maturity and diplomacy. You can hold this.",
      reversed: "Feeling managed rather than felt. It tends to come out somewhere."
    }
  },
  // ----------------------------------------------------------------- wands
  "wands-01": {
    love: {
      upright: "A spark — early, energetic, and not yet a story.",
      reversed: "Energy stalled or misfired. Waiting for a real one costs little."
    },
    general: {
      upright: "Inspiration arriving. Start before it is fully formed.",
      reversed: "A false start, or motivation that has not found its object."
    }
  },
  "wands-02": {
    love: {
      upright: "Considering a bigger version of your life, and whether someone is in it.",
      reversed: "Hesitating at the edge of a decision. The map is unlikely to get more certain."
    },
    general: {
      upright: "Planning with real ambition. Choose the direction, not just the wish.",
      reversed: "Playing small, or planning as a substitute for starting."
    }
  },
  "wands-03": {
    love: {
      upright: "Widening horizons. Love with room in it.",
      reversed: "Plans delayed. The wait may be doing something useful."
    },
    general: {
      upright: "Progress you can see from here. Keep going.",
      reversed: "Foresight in short supply. Worth looking further than the next step."
    }
  },
  "wands-04": {
    love: {
      upright: "A milestone worth marking — stability that feels like celebration.",
      reversed: "Home feels unsettled. Small repairs tend to matter more than big gestures."
    },
    general: {
      upright: "Arrival, homecoming, a good moment among people.",
      reversed: "Foundations wobbling. Worth attending to the base."
    }
  },
  "wands-05": {
    love: {
      upright: "Friction, and not necessarily the bad kind. Difference tests a bond honestly.",
      reversed: "Conflict avoided rather than resolved. It waits."
    },
    general: {
      upright: "Competition and clashing views. Useful while it stays about the work.",
      reversed: "Tension held internally. Some of it could come out."
    }
  },
  "wands-06": {
    love: {
      upright: "Being chosen, publicly or quietly. Let it land.",
      reversed: "Needing recognition more than connection. Worth noticing the hunger."
    },
    general: {
      upright: "Recognition earned. Take the win properly.",
      reversed: "A win that did not satisfy, or one you are still waiting for."
    }
  },
  "wands-07": {
    love: {
      upright: "Holding your position. Some things are worth defending calmly.",
      reversed: "Defending out of habit. Worth checking whether anyone is actually attacking."
    },
    general: {
      upright: "Standing your ground under pressure. You have the higher position.",
      reversed: "Worn down by holding on. Consider which of these are yours to fight."
    }
  },
  "wands-08": {
    love: {
      upright: "Things moving quickly. Enjoy the pace without mistaking it for depth.",
      reversed: "Messages crossed, momentum stalled. Slower and plainer tends to help."
    },
    general: {
      upright: "Rapid movement. Ride it while it is here.",
      reversed: "Scattered speed. One thing at a time."
    }
  },
  "wands-09": {
    love: {
      upright: "Tired and still here. Resilience is unglamorous and real.",
      reversed: "Guardedness outliving the threat. Worth asking what you are still bracing for."
    },
    general: {
      upright: "Nearly through, and worn. Rest counts as strategy.",
      reversed: "Defensive without needing to be. Something can be put down."
    }
  },
  "wands-10": {
    love: {
      upright: "Carrying more of the relationship than you have admitted. The weight can be shared.",
      reversed: "Setting something down. Relief may arrive slowly."
    },
    general: {
      upright: "Overloaded. Some of this belongs to someone else.",
      reversed: "Delegating, or dropping what is not yours. Good."
    }
  },
  "wands-11": {
    love: {
      upright: "Enthusiasm, news, someone keen. Let it be light.",
      reversed: "Interest that fizzles fast. Not everything has to become more."
    },
    general: {
      upright: "Exploration and appetite. Follow the curiosity.",
      reversed: "Impatience with the slow part. That part is the work."
    }
  },
  "wands-12": {
    love: {
      upright: "Passion with movement. Exciting, and worth watching for staying power.",
      reversed: "Heat without follow-through. Worth noticing the pattern before investing."
    },
    general: {
      upright: "Bold action and momentum. Go, and steer.",
      reversed: "Impulsiveness. A day's delay costs little."
    }
  },
  "wands-13": {
    love: {
      upright: "Confident warmth. Attractive partly because it is not performing.",
      reversed: "Insecurity showing up as intensity. Be gentle with yourself."
    },
    general: {
      upright: "Vitality and self-possession. You know what you are about.",
      reversed: "Comparison draining the fire. Worth coming back to your own work."
    }
  },
  "wands-14": {
    love: {
      upright: "Vision and generosity. Someone who makes room for your ambition.",
      reversed: "Expectation delivered as instruction. Asking works better."
    },
    general: {
      upright: "Leadership with a long view. People follow this.",
      reversed: "Directing more than listening. The plan improves with input."
    }
  },
  // ---------------------------------------------------------------- swords
  "swords-01": {
    love: {
      upright: "A clear thought about what you actually want. Say it simply.",
      reversed: "Clarity used as a blade, or confusion posing as nuance."
    },
    general: {
      upright: "A breakthrough in understanding. Worth writing down.",
      reversed: "Sharp thinking, badly aimed. Slow the delivery."
    }
  },
  "swords-02": {
    love: {
      upright: "A decision being avoided by keeping both options open.",
      reversed: "Information arriving. The choice is getting easier to see."
    },
    general: {
      upright: "Stalemate. You may know more than you are admitting.",
      reversed: "Too much input. Decide with what you have."
    }
  },
  "swords-03": {
    love: {
      upright: "Hurt, plainly. Naming it accurately is the beginning of it easing.",
      reversed: "The sharp edge dulling. Healing is not linear, and it is happening."
    },
    general: {
      upright: "Painful clarity. It hurts because it is true, not because it is final.",
      reversed: "Recovery underway. Be unhurried about it."
    }
  },
  "swords-04": {
    love: {
      upright: "Rest from relating. Withdrawal that restores rather than punishes.",
      reversed: "Back too soon. The pause was not finished."
    },
    general: {
      upright: "Recovery and quiet. Nothing has to be decided today.",
      reversed: "Restlessness where rest belongs."
    }
  },
  "swords-05": {
    love: {
      upright: "Winning an argument and losing something. Worth counting the whole cost.",
      reversed: "Repair becoming possible. Someone has to move first."
    },
    general: {
      upright: "A hollow victory, or a fight not worth its price.",
      reversed: "Making amends, or walking away without a last word."
    }
  },
  "swords-06": {
    love: {
      upright: "Moving toward calmer water. Bring less with you than you think you need.",
      reversed: "Still carrying the old weather. It travels."
    },
    general: {
      upright: "Transition. The hard part is mostly behind.",
      reversed: "Circling the same ground. What keeps you here?"
    }
  },
  "swords-07": {
    love: {
      upright: "Something withheld — yours or theirs. Partial truth has a cost.",
      reversed: "Coming clean. Uncomfortable, then lighter."
    },
    general: {
      upright: "Strategy shading into evasion. Worth checking your own footing.",
      reversed: "Truth surfacing. Meeting it beats managing it."
    }
  },
  "swords-08": {
    love: {
      upright: "Feeling stuck. The restriction may be more mental than actual.",
      reversed: "A limit loosening. One small move is enough to test it."
    },
    general: {
      upright: "Trapped by a story about your options. It can be tested.",
      reversed: "Perspective returning. There was a door."
    }
  },
  "swords-09": {
    love: {
      upright: "Worry at three in the morning. It exaggerates — that is what it does.",
      reversed: "The worst of it passing. Daylight helps."
    },
    general: {
      upright: "Anxiety with the volume up. Naming it lowers it a little.",
      reversed: "Relief arriving. Be kind about how long it took."
    }
  },
  "swords-10": {
    love: {
      upright: "A painful ending. Rock bottom is also a floor you can build from.",
      reversed: "Slow improvement. The recovery is less dramatic than the ending was."
    },
    general: {
      upright: "Something finishes hard. It is finished, which is its own mercy.",
      reversed: "Getting up. Gradual counts."
    }
  },
  "swords-11": {
    love: {
      upright: "Curiosity and questions. Honest ones open more than clever ones.",
      reversed: "Watching rather than asking. Saying it works better."
    },
    general: {
      upright: "Alertness and new information. Stay curious.",
      reversed: "Talk outrunning action, or too much of it second-hand."
    }
  },
  "swords-12": {
    love: {
      upright: "Direct and fast. Refreshing, as long as it is not careless.",
      reversed: "Words landing harder than intended. Slow the tempo."
    },
    general: {
      upright: "Decisive action. Move while it is clear.",
      reversed: "Haste. Worth rereading before sending."
    }
  },
  "swords-13": {
    love: {
      upright: "Clear boundaries held without coldness. That combination is rare.",
      reversed: "Distance as protection. It works, and it costs."
    },
    general: {
      upright: "Unsentimental clarity. You can see this plainly.",
      reversed: "Sharpness turned inward. Worth easing up."
    }
  },
  "swords-14": {
    love: {
      upright: "Fair, principled, straight with you. Easy to trust.",
      reversed: "Being right prioritised over being close. Both are available."
    },
    general: {
      upright: "Authority grounded in truth. Use it lightly.",
      reversed: "Judgement hardening into criticism."
    }
  },
  // -------------------------------------------------------------- pentacles
  "pents-01": {
    love: {
      upright: "A beginning with substance. Slow, concrete, real.",
      reversed: "An opening missed, or a good thing measured by the wrong scale."
    },
    general: {
      upright: "A tangible start. Plant it and be patient.",
      reversed: "Timing off, or foundations not laid yet."
    }
  },
  "pents-02": {
    love: {
      upright: "Juggling love with everything else. Flexibility is doing the work.",
      reversed: "Too many plates. Something is getting the leftovers."
    },
    general: {
      upright: "Adapting between demands. You are managing.",
      reversed: "Overcommitted. Something can be subtracted."
    }
  },
  "pents-03": {
    love: {
      upright: "Building something together with actual effort. Collaboration, not merger.",
      reversed: "Different blueprints. Worth comparing them before building further."
    },
    general: {
      upright: "Skill, teamwork, and visible progress.",
      reversed: "Effort without alignment. Agree on the plan first."
    }
  },
  "pents-04": {
    love: {
      upright: "Wanting to keep what is good. Holding it with open hands works better.",
      reversed: "Loosening a grip. Security returns in a different form."
    },
    general: {
      upright: "Conservation and security. Reasonable, up to a point.",
      reversed: "Letting go of control. Uncomfortable and useful."
    }
  },
  "pents-05": {
    love: {
      upright: "Hardship pressing on the connection. This is circumstance, not verdict.",
      reversed: "Support appearing. Asking for it is allowed."
    },
    general: {
      upright: "Scarcity and feeling outside. It is a season.",
      reversed: "Help arriving, or found. Worth taking."
    }
  },
  "pents-06": {
    love: {
      upright: "Generosity flowing both ways. Balance in what is given.",
      reversed: "Giving with conditions attached. Worth naming them."
    },
    general: {
      upright: "Sharing and fair exchange.",
      reversed: "An imbalance in who gives and who receives."
    }
  },
  "pents-07": {
    love: {
      upright: "Patience while something grows. Not everything shows progress weekly.",
      reversed: "Impatience with a slow return. Check the timeline rather than the plant."
    },
    general: {
      upright: "Long-term work, mid-stretch. Assess without pulling it up.",
      reversed: "Effort going into the wrong field. Worth reassessing honestly."
    }
  },
  "pents-08": {
    love: {
      upright: "Practising at love — attention, repair, showing up. It is a skill.",
      reversed: "Going through motions, or perfectionism where warmth belongs."
    },
    general: {
      upright: "Craft and repetition. Mastery is mostly this.",
      reversed: "Boredom, or standards that have stopped helping."
    }
  },
  "pents-09": {
    love: {
      upright: "Self-sufficient and open at the same time. A good place to meet from.",
      reversed: "Independence as armour. Needing someone is allowed."
    },
    general: {
      upright: "Earned comfort. Enjoy the result.",
      reversed: "Achievement without company."
    }
  },
  "pents-10": {
    love: {
      upright: "Long-horizon love — family, continuity, the ordinary future.",
      reversed: "Old family patterns showing up in a new connection."
    },
    general: {
      upright: "Stability, legacy, and things that outlast you.",
      reversed: "Inherited strain. It can be examined and set down."
    }
  },
  "pents-11": {
    love: {
      upright: "Someone reliable and unhurried. Promising in a quiet way.",
      reversed: "Plans without follow-through. Watch what is done, not said."
    },
    general: {
      upright: "Studying, starting, learning the trade.",
      reversed: "Procrastination, or a plan that stays a plan."
    }
  },
  "pents-12": {
    love: {
      upright: "Steady, dependable, a little slow. Consistency is underrated.",
      reversed: "Routine without warmth. Something could be added."
    },
    general: {
      upright: "Methodical progress. Dull and effective.",
      reversed: "Stuck in the groove. Worth changing one variable."
    }
  },
  "pents-13": {
    love: {
      upright: "Practical care — the kind that shows up as meals and lifts rather than speeches.",
      reversed: "Caretaking crowding out being cared for."
    },
    general: {
      upright: "Grounded abundance, and comfort you can share.",
      reversed: "Providing while running low yourself."
    }
  },
  "pents-14": {
    love: {
      upright: "Solid, generous, and unbothered by small things. Easy ground to build on.",
      reversed: "Security valued above closeness. Both are available."
    },
    general: {
      upright: "Resourceful leadership and long stability.",
      reversed: "Holding on tightly. Nothing here is as scarce as it feels."
    }
  }
};
var CORPUS_EN = {
  names: NAMES_EN,
  meanings: MEANINGS_EN
};

// packages/shared/src/tarot/content-fr.ts
var NAMES_FR = {
  "major-00": "Le Fou",
  "major-01": "Le Magicien",
  "major-02": "La Grande Prêtresse",
  "major-03": "L'Impératrice",
  "major-04": "L'Empereur",
  "major-05": "Le Hiérophante",
  "major-06": "Les Amoureux",
  "major-07": "Le Chariot",
  "major-08": "La Force",
  "major-09": "L'Ermite",
  "major-10": "La Roue de Fortune",
  "major-11": "La Justice",
  "major-12": "Le Pendu",
  "major-13": "La Mort",
  "major-14": "Tempérance",
  "major-15": "Le Diable",
  "major-16": "La Tour",
  "major-17": "L'Étoile",
  "major-18": "La Lune",
  "major-19": "Le Soleil",
  "major-20": "Le Jugement",
  "major-21": "Le Monde",
  "cups-01": "As de Coupes",
  "cups-02": "Deux de Coupes",
  "cups-03": "Trois de Coupes",
  "cups-04": "Quatre de Coupes",
  "cups-05": "Cinq de Coupes",
  "cups-06": "Six de Coupes",
  "cups-07": "Sept de Coupes",
  "cups-08": "Huit de Coupes",
  "cups-09": "Neuf de Coupes",
  "cups-10": "Dix de Coupes",
  "cups-11": "Valet de Coupes",
  "cups-12": "Cavalier de Coupes",
  "cups-13": "Reine de Coupes",
  "cups-14": "Roi de Coupes",
  "wands-01": "As de Bâtons",
  "wands-02": "Deux de Bâtons",
  "wands-03": "Trois de Bâtons",
  "wands-04": "Quatre de Bâtons",
  "wands-05": "Cinq de Bâtons",
  "wands-06": "Six de Bâtons",
  "wands-07": "Sept de Bâtons",
  "wands-08": "Huit de Bâtons",
  "wands-09": "Neuf de Bâtons",
  "wands-10": "Dix de Bâtons",
  "wands-11": "Valet de Bâtons",
  "wands-12": "Cavalier de Bâtons",
  "wands-13": "Reine de Bâtons",
  "wands-14": "Roi de Bâtons",
  "swords-01": "As d'Épées",
  "swords-02": "Deux d'Épées",
  "swords-03": "Trois d'Épées",
  "swords-04": "Quatre d'Épées",
  "swords-05": "Cinq d'Épées",
  "swords-06": "Six d'Épées",
  "swords-07": "Sept d'Épées",
  "swords-08": "Huit d'Épées",
  "swords-09": "Neuf d'Épées",
  "swords-10": "Dix d'Épées",
  "swords-11": "Valet d'Épées",
  "swords-12": "Cavalier d'Épées",
  "swords-13": "Reine d'Épées",
  "swords-14": "Roi d'Épées",
  "pents-01": "As de Deniers",
  "pents-02": "Deux de Deniers",
  "pents-03": "Trois de Deniers",
  "pents-04": "Quatre de Deniers",
  "pents-05": "Cinq de Deniers",
  "pents-06": "Six de Deniers",
  "pents-07": "Sept de Deniers",
  "pents-08": "Huit de Deniers",
  "pents-09": "Neuf de Deniers",
  "pents-10": "Dix de Deniers",
  "pents-11": "Valet de Deniers",
  "pents-12": "Cavalier de Deniers",
  "pents-13": "Reine de Deniers",
  "pents-14": "Roi de Deniers"
};
var MEANINGS_FR = {
  // ---------------------------------------------------------------- majeurs
  "major-00": {
    love: {
      upright: "Quelque chose ici n'a rien prouvé, et c'est peut-être exactement le sujet. Commencer sans certitude demande son propre courage.",
      reversed: "Un élan peut être une fuite bien habillée. Demande-toi ce que tu quitterais, pas seulement ce vers quoi tu irais."
    },
    general: {
      upright: "Un début sans carte. Ne pas connaître la forme de la chose est normal à ce stade, et souvent nécessaire.",
      reversed: "Soit l'élan est précipité, soit l'hésitation a fait son temps. Remarque de laquelle il s'agit."
    }
  },
  "major-01": {
    love: {
      upright: "Tu as plus de ressources ici que tu n'en comptes. L'attention, la franchise et le rythme forment souvent tout l'outillage.",
      reversed: "Un écart peut s'ouvrir entre ce qui est montré et ce qui est pensé — du tien ou du sien. Plus facile à nommer maintenant que plus tard."
    },
    general: {
      upright: "Les pièces sont déjà dans tes mains. Cette carte parle de les utiliser plutôt que d'en collecter d'autres.",
      reversed: "De la capacité sans direction, ou un récit mieux raconté que vécu. Ça vaut la peine de vérifier lequel."
    }
  },
  "major-02": {
    love: {
      upright: "Quelque chose se comprend ici sans être dit. Fie-toi à cette lecture — et envisage de la dire quand même.",
      reversed: "Tu es peut-être en train de te convaincre du contraire de ce que tu sens. Le signal discret est aussi une information."
    },
    general: {
      upright: "La réponse est plus près de l'intuition que de l'analyse en ce moment. Donne-lui une pièce calme.",
      reversed: "Le bruit a recouvert la lecture intérieure. Moins d'entrées, pas plus, aide généralement ici."
    }
  },
  "major-03": {
    love: {
      upright: "De la chaleur et du soin, et le fait d'être nourri par un lien plutôt que vidé par lui. Remarque ce qui nourrit vraiment.",
      reversed: "Le don a peut-être basculé de la générosité vers l'effacement. Un soin qui te vide se tient difficilement dans la durée."
    },
    general: {
      upright: "Croissance, confort et plénitude créative. Laisse quelque chose être savouré plutôt qu'optimisé.",
      reversed: "Épuisement, ou un blocage créatif qui est surtout un déficit de repos. Remplis avant de pousser."
    }
  },
  "major-04": {
    love: {
      upright: "La structure fait de la place à la douceur. Des accords clairs permettent souvent à un lien de se détendre.",
      reversed: "Le contrôle sait se faire passer pour de la stabilité. Où la structure a-t-elle cessé de servir les gens qu'elle abrite ?"
    },
    general: {
      upright: "Limites, ordre et suivi. Un cadre bâti maintenant pourra porter du poids plus tard.",
      reversed: "Rigidité, ou absence totale de cadre. Les deux te font porter plus que ta part."
    }
  },
  "major-05": {
    love: {
      upright: "Des valeurs partagées, et des scripts hérités sur la forme que l'amour devrait avoir. Certains méritent d'être gardés.",
      reversed: "Une règle que tu n'as pas choisie mène peut-être la barque. Elle peut être examinée."
    },
    general: {
      upright: "Tradition, transmission, et la sagesse d'un chemin déjà parcouru. L'emprunt est permis.",
      reversed: "La convention ne va plus. S'en écarter est un choix, pas un échec."
    }
  },
  "major-06": {
    love: {
      upright: "Alignement — de valeurs autant que d'attirance. Ce sur quoi vous vous entendez compte autant que ce que tu ressens.",
      reversed: "Une traction dans deux directions, ou des valeurs discrètement décalées. Nommer l'écart est plus doux que de le contourner."
    },
    general: {
      upright: "Un choix qui demande qui tu es vraiment, pas seulement ce que tu veux.",
      reversed: "Une décision prise pour éviter l'inconfort a tendance à revenir. Regarde ce que tu esquives."
    }
  },
  "major-07": {
    love: {
      upright: "Avancer vers ce que tu veux, les yeux ouverts. La direction compte plus que l'intensité ici.",
      reversed: "L'effort sans accord, c'est pousser et non poursuivre. Vérifie que vous allez dans le même sens."
    },
    general: {
      upright: "Élan et concentration. L'obstacle est généralement l'attention, pas la capacité.",
      reversed: "Énergie dispersée, ou force appliquée là où la patience ferait davantage."
    }
  },
  "major-08": {
    love: {
      upright: "De la constance sans dureté. Rester doux sous pression est la compétence la plus difficile, et la meilleure.",
      reversed: "C'est peut-être le doute qui parle. Il a tendance à exagérer le danger."
    },
    general: {
      upright: "Un courage qui, de l'extérieur, a l'air tranquille. La patience en fait partie.",
      reversed: "Patience épuisée, ou force employée là où la douceur aurait suffi. Le repos n'est pas un détour."
    }
  },
  "major-09": {
    love: {
      upright: "La distance peut clarifier. Savoir ce que tu veux seul te rend souvent plus net avec quelqu'un d'autre.",
      reversed: "La solitude a peut-être tourné à l'évitement. Remarque la différence entre choisir l'espace et s'y cacher."
    },
    general: {
      upright: "Un pas en arrière pour t'entendre. La réponse arrive souvent dans le calme.",
      reversed: "Isolement au-delà de son utilité. Une conversation peut faire plus qu'une semaine de réflexion."
    }
  },
  "major-10": {
    love: {
      upright: "Un tour dans le motif. Quelque chose bouge peut-être que tu n'as pas organisé, et l'accueillir coûte souvent moins que de s'arc-bouter.",
      reversed: "Le timing sonne faux. La patience coûte souvent moins cher ici que la poussée."
    },
    general: {
      upright: "Cycles et points de bascule. Un changement demande peut-être ton attention plutôt que ta résistance.",
      reversed: "Résister à un mouvement que tu sens déjà. Cette phase se déplace ; remarque ce qu'elle te montre."
    }
  },
  "major-11": {
    love: {
      upright: "L'équité, et le soulagement d'être franc l'un avec l'autre. La franchise a tendance à stabiliser un lien.",
      reversed: "Un déséquilibre que ni l'un ni l'autre n'a dit à voix haute. Il se règle rarement tout seul."
    },
    general: {
      upright: "Responsabilité et vue claire. Pèse honnêtement, ta propre part comprise.",
      reversed: "Éviter une conséquence, ou juger une situation sur des informations incomplètes."
    }
  },
  "major-12": {
    love: {
      upright: "Une pause qui change l'angle. Ne pas agir est parfois la chose la plus utile disponible.",
      reversed: "De l'attentisme déguisé en patience. Demande-toi de quoi l'attente te protège."
    },
    general: {
      upright: "Suspension, et déplacement du point de vue. La vue est réellement différente d'ici.",
      reversed: "Coincé plutôt qu'immobile. Un sacrifice qui n'aide personne peut être déposé."
    }
  },
  "major-13": {
    love: {
      upright: "Une fin qui fait de la place. Ce qui se referme ici était probablement déjà terminé.",
      reversed: "Tenir au-delà du point où ça aide. Lâcher est une compétence lente."
    },
    general: {
      upright: "Transformation par le relâchement. Quelque chose s'achève pour qu'autre chose commence.",
      reversed: "Résister à un changement déjà en cours. Le délai coûte souvent plus que le changement."
    }
  },
  "major-14": {
    love: {
      upright: "La proportion. Ni trop, ni trop retenu — le milieu fait un vrai travail ici.",
      reversed: "Des extrêmes, ou un mélange qui n'a pas encore trouvé son dosage. Ajuste doucement."
    },
    general: {
      upright: "Équilibre et patience. Combiner des contraires prend du temps, et ça se passe bien.",
      reversed: "Surcorrection dans un sens. Les petits ajustements valent mieux que les grands gestes."
    }
  },
  "major-15": {
    love: {
      upright: "Intensité et attachement, et la question de ce qui te retient ici. L'attraction n'est pas l'accord.",
      reversed: "Un motif qui desserre sa prise. Voir le mécanisme, c'est déjà l'essentiel du travail."
    },
    general: {
      upright: "Ce qui t'attache — habitude, confort, appétit. Regarde-en la forme sans honte.",
      reversed: "Desserrer une emprise que tu subissais. La liberté arrive ici progressivement."
    }
  },
  "major-16": {
    love: {
      upright: "Une clarté soudaine qui redispose les choses. Inconfortable, et ça peut dégager de la place pour la franchise.",
      reversed: "Éviter une rupture qui se prépare. La vérité remonte quand elle est prête, pas avant."
    },
    general: {
      upright: "Une structure cède et révèle ce qu'elle soutenait. L'effondrement peut être une information.",
      reversed: "Repousser un changement qui veut arriver. Le délai est lui-même une décision."
    }
  },
  "major-17": {
    love: {
      upright: "Un espoir qui a retrouvé son assise. Quelque chose de doux se reconstruit.",
      reversed: "La foi est basse. Elle a tendance à revenir, discrètement et hors calendrier."
    },
    general: {
      upright: "Reconstitution et clarté après la tension. Continue doucement.",
      reversed: "Découragement. Mieux vaut le nommer que jouer l'optimisme par-dessus."
    }
  },
  "major-18": {
    love: {
      upright: "Tout n'est pas encore visible ici. Une part de ce que tu ressens est peut-être de la mémoire plutôt que du présent.",
      reversed: "Le brouillard se lève. Ce qui t'effrayait paraît parfois plus petit à la lumière."
    },
    general: {
      upright: "Incertitude et projection. Tiens tes conclusions sans serrer, pour l'instant.",
      reversed: "La clarté émerge. Sépare ce qui relevait de la peur de ce qui relevait du fait."
    }
  },
  "major-19": {
    love: {
      upright: "De la chaleur sans effort. Être vu et aimer ça — à savourer plutôt qu'à analyser.",
      reversed: "Éclat atténué, ou attente faisant le travail que la joie devrait faire. Ça passe."
    },
    general: {
      upright: "Vitalité et bien-être tout simple. Laisse ça rester simple.",
      reversed: "Une platitude passagère. Ce n'est un verdict sur rien."
    }
  },
  "major-20": {
    love: {
      upright: "Un règlement de comptes avec un motif, et la possibilité d'y répondre autrement cette fois.",
      reversed: "Rejouer un vieux verdict sur toi-même. Les preuves ont peut-être expiré."
    },
    general: {
      upright: "Réveil et revue honnête. Qu'as-tu réellement appris ?",
      reversed: "L'autocritique prend la place de la réflexion. Ce sont deux activités différentes."
    }
  },
  "major-21": {
    love: {
      upright: "Un sentiment de complétude — un cycle qui se referme bien plutôt que spectaculairement.",
      reversed: "Presque fini. La dernière marche est souvent celle qu'on saute le plus facilement."
    },
    general: {
      upright: "Plénitude, et un chapitre qui touche à sa fin. Ça vaut la peine de le marquer avant le suivant.",
      reversed: "Un fil qui traîne et garde la porte ouverte. Il peut être coupé volontairement."
    }
  },
  // ----------------------------------------------------------------- coupes
  "cups-01": {
    love: {
      upright: "Un sentiment qui s'ouvre, encore neuf et un peu sans défense. Laisse-le être tendre.",
      reversed: "Un sentiment retenu, peut-être pour de bonnes raisons. Remarque ce qui rend l'ouverture difficile."
    },
    general: {
      upright: "Un début émotionnel. Quelque chose demande à être ressenti avant d'être compris.",
      reversed: "Émotion bloquée, ou une coupe que tu gardes couverte. Elle se conserve."
    }
  },
  "cups-02": {
    love: {
      upright: "Reconnaissance mutuelle. Deux personnes qui se rencontrent plutôt qu'une idée l'une de l'autre.",
      reversed: "Un côté porte peut-être davantage le lien. Ça vaut la peine de le dire."
    },
    general: {
      upright: "Un partenariat à égalité. La réciprocité est le sujet.",
      reversed: "Un échange déséquilibré. Le nommer aide généralement plus que le compenser."
    }
  },
  "cups-03": {
    love: {
      upright: "L'amour en compagnie — les amis, la fête, la joie partagée.",
      reversed: "Trop de bruit autour du lien, ou un cercle dont tu t'es éloigné."
    },
    general: {
      upright: "Communauté et joie commune. Être parmi les gens est le sujet.",
      reversed: "Socialement surchargé, ou discrètement hors du cercle. Les deux méritent d'être remarqués."
    }
  },
  "cups-04": {
    love: {
      upright: "Une platitude là où il y avait de l'intérêt. Quelque chose est peut-être devant toi, non enregistré.",
      reversed: "L'intérêt revient après une période terne. Ça vaut la peine de lever les yeux."
    },
    general: {
      upright: "Contemplation qui glisse vers l'apathie. Demande-toi ce qui a cessé d'atteindre.",
      reversed: "L'appétit revient. La pause a fait son travail."
    }
  },
  "cups-05": {
    love: {
      upright: "Le chagrin de ce qui n'a pas eu lieu. Ce qui reste s'oublie facilement quand on regarde ce qui s'est renversé.",
      reversed: "Se tourner vers ce qui tient encore debout. Lent, et réel."
    },
    general: {
      upright: "Perte et déception. Donne-leur de la place, puis compte ce qui reste.",
      reversed: "L'acceptation commence. Pas la résolution, mais du mouvement."
    }
  },
  "cups-06": {
    love: {
      upright: "Une douceur avec de la mémoire dedans. Le passé peut être chaud sans être ton adresse.",
      reversed: "La nostalgie travaille plus fort que le présent. Compare doucement."
    },
    general: {
      upright: "Mémoire, innocence, une gentillesse qui revient. Laisse ça rester simple.",
      reversed: "Un passé idéalisé qui encombre ce qui est là."
    }
  },
  "cups-07": {
    love: {
      upright: "Beaucoup de possibilités, pas toutes réelles. Choisis-en une que tu peux toucher.",
      reversed: "La clarté après une période d'imagination. Une option devient l'option."
    },
    general: {
      upright: "Options et fantaisie. Ancres-en une avant de choisir.",
      reversed: "La concentration arrive. Le flou te servait à quelque chose — remarque à quoi."
    }
  },
  "cups-08": {
    love: {
      upright: "S'éloigner de ce qui ne te nourrit plus. Courageux, et souvent silencieux.",
      reversed: "Rester au-delà de ce que tu sais. Demande-toi honnêtement ce que partir coûterait."
    },
    general: {
      upright: "Laisser quelque chose d'inachevé parce que ce n'est pas à toi de le finir.",
      reversed: "Dériver plutôt que décider. Une direction aiderait."
    }
  },
  "cups-09": {
    love: {
      upright: "Le contentement. Vouloir ce que tu as est un accomplissement en soi.",
      reversed: "De la satisfaction en surface avec quelque chose d'inassouvi dessous."
    },
    general: {
      upright: "Un souhait exaucé. Savoure-le avant de déplacer la cible.",
      reversed: "Avoir beaucoup et ressentir peu. À explorer plutôt qu'à réparer."
    }
  },
  "cups-10": {
    love: {
      upright: "L'appartenance, et le bonheur ordinaire qui photographie mal.",
      reversed: "Un écart entre l'image et le ressenti. Ça vaut la peine de dire la partie silencieuse."
    },
    general: {
      upright: "Harmonie chez toi et parmi les tiens. C'est la bonne partie.",
      reversed: "Une friction sous une surface tranquille. Petite, et pas rien."
    }
  },
  "cups-11": {
    love: {
      upright: "Un message ou un geste tendre et maladroit. La sincérité bat souvent l'aisance.",
      reversed: "Le sentiment court devant ce qui s'est réellement passé. Laisse-le rattraper."
    },
    general: {
      upright: "Curiosité et petite poussée créative. Suis-la sans plan.",
      reversed: "De la sensibilité sans endroit où la mettre. Fabrique quelque chose."
    }
  },
  "cups-12": {
    love: {
      upright: "Un élan romantique — quelqu'un qui mène par le sentiment, et ça sonne sincère.",
      reversed: "Le charme dépasse la substance, ou une idée de l'amour plus grande que la personne."
    },
    general: {
      upright: "Suivre ton cœur quelque part. Garde un œil ouvert.",
      reversed: "L'humeur tient le volant. Une journée de recul peut aider."
    }
  },
  "cups-13": {
    love: {
      upright: "Une stabilité émotionnelle — quelqu'un qui porte le sentiment sans être emporté.",
      reversed: "Absorber la météo de tout le monde. Les limites sont une forme de soin."
    },
    general: {
      upright: "Compassion et profondeur. Le sentir et le penser coopèrent.",
      reversed: "Fondu dans les états des autres. Où est-ce que tu t'arrêtes ?"
    }
  },
  "cups-14": {
    love: {
      upright: "De la chaleur avec une quille. Le sentiment exprimé sans submerger personne.",
      reversed: "Calme en surface, non-dit en dessous. Le sang-froid n'est pas la franchise."
    },
    general: {
      upright: "Maturité émotionnelle et diplomatie. Tu peux porter ça.",
      reversed: "Un sentiment géré plutôt que ressenti. Il ressort ailleurs."
    }
  },
  // ----------------------------------------------------------------- bâtons
  "wands-01": {
    love: {
      upright: "Une étincelle — précoce, énergique, et pas encore une histoire.",
      reversed: "Énergie calée ou mal partie. Attendre la vraie coûte peu."
    },
    general: {
      upright: "L'inspiration arrive. Commence avant que ce soit complètement formé.",
      reversed: "Un faux départ, ou une motivation qui n'a pas trouvé son objet."
    }
  },
  "wands-02": {
    love: {
      upright: "Envisager une version plus grande de ta vie, et si quelqu'un y figure.",
      reversed: "Hésiter au bord d'une décision. La carte a peu de chances de devenir plus sûre."
    },
    general: {
      upright: "Planifier avec de l'ambition réelle. Choisis la direction, pas seulement le souhait.",
      reversed: "Voir petit, ou planifier au lieu de commencer."
    }
  },
  "wands-03": {
    love: {
      upright: "Des horizons qui s'élargissent. Un amour avec de l'espace dedans.",
      reversed: "Des plans retardés. L'attente fait peut-être quelque chose d'utile."
    },
    general: {
      upright: "Un progrès visible d'ici. Continue.",
      reversed: "Peu de vue d'ensemble. Regarde plus loin que le pas suivant."
    }
  },
  "wands-04": {
    love: {
      upright: "Une étape à marquer — une stabilité qui ressemble à une fête.",
      reversed: "Le chez-soi est instable. Les petites réparations comptent plus que les grands gestes."
    },
    general: {
      upright: "Arrivée, retour, un bon moment entre gens.",
      reversed: "Des fondations qui vacillent. Occupe-toi de la base."
    }
  },
  "wands-05": {
    love: {
      upright: "De la friction, et pas forcément la mauvaise. La différence teste un lien honnêtement.",
      reversed: "Un conflit évité plutôt que réglé. Il attend."
    },
    general: {
      upright: "Compétition et avis qui s'entrechoquent. Utile tant que ça reste sur le travail.",
      reversed: "Tension gardée à l'intérieur. Une part pourrait sortir."
    }
  },
  "wands-06": {
    love: {
      upright: "Être choisi, publiquement ou discrètement. Laisse ça se poser.",
      reversed: "Avoir plus besoin de reconnaissance que de lien. Remarque la faim."
    },
    general: {
      upright: "Une reconnaissance méritée. Prends la victoire correctement.",
      reversed: "Une victoire qui n'a pas rassasié, ou une que tu attends encore."
    }
  },
  "wands-07": {
    love: {
      upright: "Tenir ta position. Certaines choses méritent d'être défendues calmement.",
      reversed: "Se défendre par habitude. Vérifie si quelqu'un attaque vraiment."
    },
    general: {
      upright: "Tenir bon sous pression. Tu as la position haute.",
      reversed: "Usé à force de tenir. Regarde lesquels de ces combats sont les tiens."
    }
  },
  "wands-08": {
    love: {
      upright: "Les choses vont vite. Savoure le rythme sans le confondre avec la profondeur.",
      reversed: "Messages croisés, élan calé. Plus lent et plus simple aide généralement."
    },
    general: {
      upright: "Mouvement rapide. Profites-en tant qu'il est là.",
      reversed: "De la vitesse dispersée. Une chose à la fois."
    }
  },
  "wands-09": {
    love: {
      upright: "Fatigué et encore là. La résilience est peu spectaculaire et bien réelle.",
      reversed: "Une garde qui survit à la menace. Demande-toi contre quoi tu te prépares encore."
    },
    general: {
      upright: "Presque au bout, et usé. Le repos compte comme stratégie.",
      reversed: "Sur la défensive sans nécessité. Quelque chose peut être déposé."
    }
  },
  "wands-10": {
    love: {
      upright: "Porter plus de la relation que tu ne l'as admis. Le poids peut être partagé.",
      reversed: "Déposer quelque chose. Le soulagement peut arriver lentement."
    },
    general: {
      upright: "Surchargé. Une part de tout ça appartient à quelqu'un d'autre.",
      reversed: "Déléguer, ou lâcher ce qui n'est pas à toi. Bien."
    }
  },
  "wands-11": {
    love: {
      upright: "Enthousiasme, nouvelles, quelqu'un d'enthousiaste. Laisse ça rester léger.",
      reversed: "Un intérêt qui retombe vite. Tout n'a pas à devenir davantage."
    },
    general: {
      upright: "Exploration et appétit. Suis la curiosité.",
      reversed: "Impatience avec la partie lente. Cette partie est le travail."
    }
  },
  "wands-12": {
    love: {
      upright: "De la passion avec du mouvement. Excitant, et à observer pour la tenue dans le temps.",
      reversed: "De la chaleur sans suite. Remarque le motif avant d'investir."
    },
    general: {
      upright: "Action franche et élan. Vas-y, et pilote.",
      reversed: "Impulsivité. Une journée d'écart coûte peu."
    }
  },
  "wands-13": {
    love: {
      upright: "Une chaleur confiante. Attirante en partie parce qu'elle ne joue pas.",
      reversed: "L'insécurité qui se présente en intensité. Sois doux avec toi."
    },
    general: {
      upright: "Vitalité et présence à soi. Tu sais ce que tu vaux.",
      reversed: "La comparaison vide le feu. Reviens à ton propre travail."
    }
  },
  "wands-14": {
    love: {
      upright: "Vision et générosité. Quelqu'un qui fait de la place à ton ambition.",
      reversed: "Une attente livrée comme une consigne. Demander fonctionne mieux."
    },
    general: {
      upright: "Un leadership avec de la distance. Les gens suivent ça.",
      reversed: "Diriger plus qu'écouter. Le plan s'améliore avec les avis."
    }
  },
  // ------------------------------------------------------------------ épées
  "swords-01": {
    love: {
      upright: "Une pensée claire sur ce que tu veux vraiment. Dis-la simplement.",
      reversed: "La clarté employée comme lame, ou la confusion déguisée en nuance."
    },
    general: {
      upright: "Une percée de compréhension. Ça vaut la peine de l'écrire.",
      reversed: "Pensée affûtée, mal visée. Ralentis la livraison."
    }
  },
  "swords-02": {
    love: {
      upright: "Une décision évitée en gardant les deux options ouvertes.",
      reversed: "L'information arrive. Le choix devient plus lisible."
    },
    general: {
      upright: "Impasse. Tu en sais peut-être plus que tu ne l'admets.",
      reversed: "Trop d'entrées. Décide avec ce que tu as."
    }
  },
  "swords-03": {
    love: {
      upright: "De la peine, simplement. La nommer précisément est le début de son apaisement.",
      reversed: "Le tranchant s'émousse. La guérison n'est pas linéaire, et elle est en cours."
    },
    general: {
      upright: "Une clarté douloureuse. Ça fait mal parce que c'est vrai, pas parce que c'est définitif.",
      reversed: "Récupération en cours. Prends ton temps."
    }
  },
  "swords-04": {
    love: {
      upright: "Du repos loin du lien. Un retrait qui restaure plutôt qu'il ne punit.",
      reversed: "Revenu trop tôt. La pause n'était pas finie."
    },
    general: {
      upright: "Récupération et silence. Rien n'a besoin d'être décidé aujourd'hui.",
      reversed: "De l'agitation là où le repos a sa place."
    }
  },
  "swords-05": {
    love: {
      upright: "Gagner une dispute et perdre quelque chose. Compte le coût entier.",
      reversed: "La réparation devient possible. Quelqu'un doit bouger en premier."
    },
    general: {
      upright: "Une victoire creuse, ou un combat qui ne valait pas son prix.",
      reversed: "Réparer, ou partir sans le dernier mot."
    }
  },
  "swords-06": {
    love: {
      upright: "Aller vers des eaux plus calmes. Emporte moins que tu ne crois nécessaire.",
      reversed: "Encore chargé de l'ancienne météo. Elle voyage."
    },
    general: {
      upright: "Transition. Le plus dur est largement derrière.",
      reversed: "Tourner sur le même terrain. Qu'est-ce qui te retient ici ?"
    }
  },
  "swords-07": {
    love: {
      upright: "Quelque chose de retenu — du tien ou du sien. Une vérité partielle a un coût.",
      reversed: "Dire les choses. Inconfortable, puis plus léger."
    },
    general: {
      upright: "La stratégie qui glisse vers l'esquive. Vérifie ton propre appui.",
      reversed: "La vérité remonte. L'accueillir vaut mieux que la gérer."
    }
  },
  "swords-08": {
    love: {
      upright: "Se sentir coincé. La contrainte est peut-être plus mentale que réelle.",
      reversed: "Une limite se desserre. Un petit mouvement suffit à la tester."
    },
    general: {
      upright: "Piégé par un récit sur tes options. Il peut être testé.",
      reversed: "La perspective revient. Il y avait une porte."
    }
  },
  "swords-09": {
    love: {
      upright: "L'inquiétude de trois heures du matin. Elle exagère — c'est son métier.",
      reversed: "Le pire passe. Le jour aide."
    },
    general: {
      upright: "L'anxiété avec le volume monté. La nommer la baisse un peu.",
      reversed: "Le soulagement arrive. Sois indulgent sur le temps que ça a pris."
    }
  },
  "swords-10": {
    love: {
      upright: "Une fin douloureuse. Le fond est aussi un plancher sur lequel bâtir.",
      reversed: "Une amélioration lente. La reprise est moins spectaculaire que la fin ne l'a été."
    },
    general: {
      upright: "Quelque chose se termine durement. C'est terminé, ce qui est déjà une clémence.",
      reversed: "Se relever. Le progressif compte."
    }
  },
  "swords-11": {
    love: {
      upright: "Curiosité et questions. Les honnêtes ouvrent plus que les habiles.",
      reversed: "Observer au lieu de demander. Le dire fonctionne mieux."
    },
    general: {
      upright: "Vigilance et informations neuves. Reste curieux.",
      reversed: "La parole dépasse l'action, ou trop d'informations de seconde main."
    }
  },
  "swords-12": {
    love: {
      upright: "Direct et rapide. Rafraîchissant, tant que ce n'est pas négligent.",
      reversed: "Des mots qui atterrissent plus fort que prévu. Ralentis le tempo."
    },
    general: {
      upright: "Action décisive. Bouge tant que c'est clair.",
      reversed: "Précipitation. Relis avant d'envoyer."
    }
  },
  "swords-13": {
    love: {
      upright: "Des limites nettes tenues sans froideur. Cette combinaison est rare.",
      reversed: "La distance comme protection. Ça marche, et ça coûte."
    },
    general: {
      upright: "Une clarté sans sentimentalisme. Tu vois ça nettement.",
      reversed: "Le tranchant retourné vers toi. Desserre un peu."
    }
  },
  "swords-14": {
    love: {
      upright: "Juste, de principe, franc avec toi. Facile à croire.",
      reversed: "Avoir raison passe avant être proche. Les deux sont disponibles."
    },
    general: {
      upright: "Une autorité fondée sur le vrai. Emploie-la légèrement.",
      reversed: "Le jugement qui durcit en critique."
    }
  },
  // ---------------------------------------------------------------- deniers
  "pents-01": {
    love: {
      upright: "Un début qui a de la matière. Lent, concret, réel.",
      reversed: "Une ouverture manquée, ou une bonne chose mesurée à la mauvaise échelle."
    },
    general: {
      upright: "Un départ tangible. Plante-le et sois patient.",
      reversed: "Le moment ne va pas, ou les fondations ne sont pas posées."
    }
  },
  "pents-02": {
    love: {
      upright: "Jongler entre l'amour et tout le reste. La souplesse fait le travail.",
      reversed: "Trop d'assiettes en l'air. Quelque chose reçoit les restes."
    },
    general: {
      upright: "S'adapter entre des exigences. Tu t'en sors.",
      reversed: "Trop d'engagements. Quelque chose peut être soustrait."
    }
  },
  "pents-03": {
    love: {
      upright: "Bâtir quelque chose ensemble avec de l'effort réel. Collaboration, pas fusion.",
      reversed: "Des plans différents. Comparez-les avant de bâtir plus haut."
    },
    general: {
      upright: "Compétence, équipe, et progrès visible.",
      reversed: "De l'effort sans alignement. Mettez-vous d'accord sur le plan d'abord."
    }
  },
  "pents-04": {
    love: {
      upright: "Vouloir garder ce qui est bon. Le tenir mains ouvertes fonctionne mieux.",
      reversed: "Desserrer la prise. La sécurité revient sous une autre forme."
    },
    general: {
      upright: "Conservation et sécurité. Raisonnable, jusqu'à un certain point.",
      reversed: "Lâcher le contrôle. Inconfortable et utile."
    }
  },
  "pents-05": {
    love: {
      upright: "Une difficulté qui pèse sur le lien. C'est une circonstance, pas un verdict.",
      reversed: "Du soutien apparaît. Le demander est permis."
    },
    general: {
      upright: "Manque et sentiment d'être dehors. C'est une saison.",
      reversed: "De l'aide qui arrive, ou qu'on trouve. Ça se prend."
    }
  },
  "pents-06": {
    love: {
      upright: "Une générosité qui circule dans les deux sens. De l'équilibre dans ce qui est donné.",
      reversed: "Donner avec des conditions attachées. Ça vaut la peine de les nommer."
    },
    general: {
      upright: "Partage et échange équitable.",
      reversed: "Un déséquilibre entre qui donne et qui reçoit."
    }
  },
  "pents-07": {
    love: {
      upright: "De la patience pendant que ça pousse. Tout ne montre pas des progrès chaque semaine.",
      reversed: "De l'impatience devant un rendement lent. Vérifie le calendrier plutôt que la plante."
    },
    general: {
      upright: "Un travail de long terme, à mi-parcours. Évalue sans déterrer.",
      reversed: "De l'effort versé dans le mauvais champ. Ça vaut une réévaluation honnête."
    }
  },
  "pents-08": {
    love: {
      upright: "S'exercer à aimer — attention, réparation, présence. C'est une compétence.",
      reversed: "Faire les gestes, ou du perfectionnisme là où la chaleur a sa place."
    },
    general: {
      upright: "Métier et répétition. La maîtrise, c'est surtout ça.",
      reversed: "Ennui, ou des exigences qui ont cessé d'aider."
    }
  },
  "pents-09": {
    love: {
      upright: "Autonome et ouvert en même temps. Un bon endroit d'où rencontrer.",
      reversed: "L'indépendance comme armure. Avoir besoin de quelqu'un est permis."
    },
    general: {
      upright: "Un confort gagné. Savoure le résultat.",
      reversed: "De la réussite sans compagnie."
    }
  },
  "pents-10": {
    love: {
      upright: "Un amour à long horizon — famille, continuité, l'avenir ordinaire.",
      reversed: "De vieux motifs familiaux qui se présentent dans un lien neuf."
    },
    general: {
      upright: "Stabilité, héritage, et des choses qui te survivent.",
      reversed: "Une tension héritée. Elle peut être examinée et déposée."
    }
  },
  "pents-11": {
    love: {
      upright: "Quelqu'un de fiable et sans hâte. Prometteur discrètement.",
      reversed: "Des plans sans suite. Regarde ce qui est fait, pas ce qui est dit."
    },
    general: {
      upright: "Étudier, commencer, apprendre le métier.",
      reversed: "Procrastination, ou un plan qui reste un plan."
    }
  },
  "pents-12": {
    love: {
      upright: "Stable, fiable, un peu lent. La constance est sous-estimée.",
      reversed: "De la routine sans chaleur. Quelque chose pourrait être ajouté."
    },
    general: {
      upright: "Un progrès méthodique. Ennuyeux et efficace.",
      reversed: "Coincé dans le sillon. Change une variable."
    }
  },
  "pents-13": {
    love: {
      upright: "Un soin pratique — celui qui prend la forme de repas et de trajets plutôt que de discours.",
      reversed: "Prendre soin au point de ne plus être pris en soin."
    },
    general: {
      upright: "Une abondance ancrée, et un confort partageable.",
      reversed: "Pourvoir en étant soi-même à sec."
    }
  },
  "pents-14": {
    love: {
      upright: "Solide, généreux, imperturbable sur les petites choses. Un terrain facile où bâtir.",
      reversed: "La sécurité placée au-dessus de la proximité. Les deux sont disponibles."
    },
    general: {
      upright: "Un leadership débrouillard et une stabilité longue.",
      reversed: "Serrer fort. Rien ici n'est aussi rare que ça en a l'air."
    }
  }
};
var CORPUS_FR = {
  names: NAMES_FR,
  meanings: MEANINGS_FR
};

// packages/shared/src/tarot/deck.ts
var DECK = [
  { id: "major-00", suit: "major", number: 0, imageFile: "major-00.jpg" },
  { id: "major-01", suit: "major", number: 1, imageFile: "major-01.jpg" },
  { id: "major-02", suit: "major", number: 2, imageFile: "major-02.jpg" },
  { id: "major-03", suit: "major", number: 3, imageFile: "major-03.jpg" },
  { id: "major-04", suit: "major", number: 4, imageFile: "major-04.jpg" },
  { id: "major-05", suit: "major", number: 5, imageFile: "major-05.jpg" },
  { id: "major-06", suit: "major", number: 6, imageFile: "major-06.jpg" },
  { id: "major-07", suit: "major", number: 7, imageFile: "major-07.jpg" },
  { id: "major-08", suit: "major", number: 8, imageFile: "major-08.jpg" },
  { id: "major-09", suit: "major", number: 9, imageFile: "major-09.jpg" },
  { id: "major-10", suit: "major", number: 10, imageFile: "major-10.jpg" },
  { id: "major-11", suit: "major", number: 11, imageFile: "major-11.jpg" },
  { id: "major-12", suit: "major", number: 12, imageFile: "major-12.jpg" },
  { id: "major-13", suit: "major", number: 13, imageFile: "major-13.jpg" },
  { id: "major-14", suit: "major", number: 14, imageFile: "major-14.jpg" },
  { id: "major-15", suit: "major", number: 15, imageFile: "major-15.jpg" },
  { id: "major-16", suit: "major", number: 16, imageFile: "major-16.jpg" },
  { id: "major-17", suit: "major", number: 17, imageFile: "major-17.jpg" },
  { id: "major-18", suit: "major", number: 18, imageFile: "major-18.jpg" },
  { id: "major-19", suit: "major", number: 19, imageFile: "major-19.jpg" },
  { id: "major-20", suit: "major", number: 20, imageFile: "major-20.jpg" },
  { id: "major-21", suit: "major", number: 21, imageFile: "major-21.jpg" },
  { id: "cups-01", suit: "cups", number: 1, imageFile: "cups-01.jpg" },
  { id: "cups-02", suit: "cups", number: 2, imageFile: "cups-02.jpg" },
  { id: "cups-03", suit: "cups", number: 3, imageFile: "cups-03.jpg" },
  { id: "cups-04", suit: "cups", number: 4, imageFile: "cups-04.jpg" },
  { id: "cups-05", suit: "cups", number: 5, imageFile: "cups-05.jpg" },
  { id: "cups-06", suit: "cups", number: 6, imageFile: "cups-06.jpg" },
  { id: "cups-07", suit: "cups", number: 7, imageFile: "cups-07.jpg" },
  { id: "cups-08", suit: "cups", number: 8, imageFile: "cups-08.jpg" },
  { id: "cups-09", suit: "cups", number: 9, imageFile: "cups-09.jpg" },
  { id: "cups-10", suit: "cups", number: 10, imageFile: "cups-10.jpg" },
  { id: "cups-11", suit: "cups", number: 11, imageFile: "cups-11.jpg" },
  { id: "cups-12", suit: "cups", number: 12, imageFile: "cups-12.jpg" },
  { id: "cups-13", suit: "cups", number: 13, imageFile: "cups-13.jpg" },
  { id: "cups-14", suit: "cups", number: 14, imageFile: "cups-14.jpg" },
  { id: "wands-01", suit: "wands", number: 1, imageFile: "wands-01.jpg" },
  { id: "wands-02", suit: "wands", number: 2, imageFile: "wands-02.jpg" },
  { id: "wands-03", suit: "wands", number: 3, imageFile: "wands-03.jpg" },
  { id: "wands-04", suit: "wands", number: 4, imageFile: "wands-04.jpg" },
  { id: "wands-05", suit: "wands", number: 5, imageFile: "wands-05.jpg" },
  { id: "wands-06", suit: "wands", number: 6, imageFile: "wands-06.jpg" },
  { id: "wands-07", suit: "wands", number: 7, imageFile: "wands-07.jpg" },
  { id: "wands-08", suit: "wands", number: 8, imageFile: "wands-08.jpg" },
  { id: "wands-09", suit: "wands", number: 9, imageFile: "wands-09.jpg" },
  { id: "wands-10", suit: "wands", number: 10, imageFile: "wands-10.jpg" },
  { id: "wands-11", suit: "wands", number: 11, imageFile: "wands-11.jpg" },
  { id: "wands-12", suit: "wands", number: 12, imageFile: "wands-12.jpg" },
  { id: "wands-13", suit: "wands", number: 13, imageFile: "wands-13.jpg" },
  { id: "wands-14", suit: "wands", number: 14, imageFile: "wands-14.jpg" },
  { id: "swords-01", suit: "swords", number: 1, imageFile: "swords-01.jpg" },
  { id: "swords-02", suit: "swords", number: 2, imageFile: "swords-02.jpg" },
  { id: "swords-03", suit: "swords", number: 3, imageFile: "swords-03.jpg" },
  { id: "swords-04", suit: "swords", number: 4, imageFile: "swords-04.jpg" },
  { id: "swords-05", suit: "swords", number: 5, imageFile: "swords-05.jpg" },
  { id: "swords-06", suit: "swords", number: 6, imageFile: "swords-06.jpg" },
  { id: "swords-07", suit: "swords", number: 7, imageFile: "swords-07.jpg" },
  { id: "swords-08", suit: "swords", number: 8, imageFile: "swords-08.jpg" },
  { id: "swords-09", suit: "swords", number: 9, imageFile: "swords-09.jpg" },
  { id: "swords-10", suit: "swords", number: 10, imageFile: "swords-10.jpg" },
  { id: "swords-11", suit: "swords", number: 11, imageFile: "swords-11.jpg" },
  { id: "swords-12", suit: "swords", number: 12, imageFile: "swords-12.jpg" },
  { id: "swords-13", suit: "swords", number: 13, imageFile: "swords-13.jpg" },
  { id: "swords-14", suit: "swords", number: 14, imageFile: "swords-14.jpg" },
  { id: "pents-01", suit: "pents", number: 1, imageFile: "pents-01.jpg" },
  { id: "pents-02", suit: "pents", number: 2, imageFile: "pents-02.jpg" },
  { id: "pents-03", suit: "pents", number: 3, imageFile: "pents-03.jpg" },
  { id: "pents-04", suit: "pents", number: 4, imageFile: "pents-04.jpg" },
  { id: "pents-05", suit: "pents", number: 5, imageFile: "pents-05.jpg" },
  { id: "pents-06", suit: "pents", number: 6, imageFile: "pents-06.jpg" },
  { id: "pents-07", suit: "pents", number: 7, imageFile: "pents-07.jpg" },
  { id: "pents-08", suit: "pents", number: 8, imageFile: "pents-08.jpg" },
  { id: "pents-09", suit: "pents", number: 9, imageFile: "pents-09.jpg" },
  { id: "pents-10", suit: "pents", number: 10, imageFile: "pents-10.jpg" },
  { id: "pents-11", suit: "pents", number: 11, imageFile: "pents-11.jpg" },
  { id: "pents-12", suit: "pents", number: 12, imageFile: "pents-12.jpg" },
  { id: "pents-13", suit: "pents", number: 13, imageFile: "pents-13.jpg" },
  { id: "pents-14", suit: "pents", number: 14, imageFile: "pents-14.jpg" }
];

// packages/shared/src/tarot/engine.ts
var SPREAD_POSITIONS = [
  "present",
  "attention",
  "connection",
  "advice"
];
var CARDS_PER_PERIOD = {
  weekly: 4,
  monthly: 3
};
var REVERSED_PROBABILITY = 0.3;
function hashSeed(seed) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
function seededRandom(seed) {
  let a = hashSeed(seed);
  return () => {
    a = a + 1831565813 >>> 0;
    let t = a;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
function shuffle(items, rng) {
  const out = items.slice();
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    const swap = out[i];
    out[i] = out[j];
    out[j] = swap;
  }
  return out;
}
function isoWeek(date) {
  const d = new Date(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate())
  );
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - day);
  const year = d.getUTCFullYear();
  const jan1 = new Date(Date.UTC(year, 0, 1));
  const week = Math.ceil(((d.getTime() - jan1.getTime()) / 864e5 + 1) / 7);
  return { year, week };
}
function periodKey(period, now) {
  if (period === "weekly") {
    const { year, week } = isoWeek(now);
    return `${year}-W${String(week).padStart(2, "0")}`;
  }
  return `${now.getFullYear()}-M${now.getMonth() + 1}`;
}
function drawSpread(options) {
  const now = options.now ?? /* @__PURE__ */ new Date();
  const seedKey = periodKey(options.period, now);
  const rng = seededRandom(
    `${options.userId}-${options.mode}-${options.period}-${seedKey}`
  );
  const shuffled = shuffle(DECK, rng);
  const count = CARDS_PER_PERIOD[options.period];
  const cards = SPREAD_POSITIONS.slice(0, count).map((position, index) => ({
    position,
    shape: shuffled[index],
    reversed: rng() < REVERSED_PROBABILITY
  }));
  return { cards, seed: seedKey };
}
function pickMeaning(meanings, mode, reversed) {
  return meanings[mode][reversed ? "reversed" : "upright"];
}

// packages/shared/src/tarot/index.ts
var WRITTEN_TAROT_LOCALES = ["en", "fr"];
var CORPORA = {
  en: CORPUS_EN,
  fr: CORPUS_FR
};
function resolveTarotCorpus(locale) {
  const written = WRITTEN_TAROT_LOCALES.find((l) => l === locale);
  if (written) {
    return { corpus: CORPORA[written], resolvedLocale: written, isFallback: false };
  }
  return { corpus: CORPUS_EN, resolvedLocale: "en", isFallback: true };
}
function resolveCard(options) {
  const shape = DECK.find((c) => c.id === options.id);
  if (!shape) {
    throw new Error(`Unknown tarot card id: ${String(options.id)}`);
  }
  const { corpus, isFallback } = resolveTarotCorpus(options.locale);
  return {
    ...shape,
    name: corpus.names[options.id],
    reversed: options.reversed,
    meaning: pickMeaning(corpus.meanings[options.id], options.mode, options.reversed),
    isFallback
  };
}
function generateReading(options) {
  const { cards, seed } = drawSpread({
    userId: options.userId,
    mode: options.mode,
    period: options.period,
    now: options.now
  });
  const resolved = cards.map(({ position, shape, reversed }) => ({
    position,
    card: resolveCard({
      id: shape.id,
      mode: options.mode,
      reversed,
      locale: options.locale
    })
  }));
  return {
    mode: options.mode,
    period: options.period,
    locale: options.locale ?? "en",
    cards: resolved,
    seed,
    generatedAt: (options.now ?? /* @__PURE__ */ new Date()).toISOString(),
    isFallback: resolved.some((entry) => entry.card.isFallback)
  };
}
export {
  CORPUS_EN,
  CORPUS_FR,
  DECK,
  drawSpread,
  generateReading,
  pickMeaning
};
