// The synastry computation moved to the server. This proves it is the SAME
// computation, that the generated Deno bundle is not a second implementation,
// and that both clients still render a reading.
//
// WHY IT MOVED
// ------------
// The web and mobile screens computed the score themselves, which meant
// `get-profile-chart` had to publish the other person's ecliptic longitudes —
// and those inverted straight back to their exact birth instant and birth
// coordinates. Publishing the RESULT instead of the INPUTS is the only version
// of this feature that does not hand over the birth record.
// docs/security-audit-2026-09-07.md, JUNO-01.
//
// THE RISK THIS SUITE EXISTS FOR
// ------------------------------
// A hand-written Deno copy of the scoring model would drift from the shared
// engine, silently, exactly as the two ephemeris copies did before
// `engine-contract.test.ts` was written. So the bundle is GENERATED from these
// very modules by `scripts/build-edge-astrology.mjs`, and the tests below
// execute the committed artefact and compare it, case for case, with the
// engine the apps import.

import { existsSync } from 'node:fs';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  REPO_ROOT,
  cleanupEdgeModules,
  loadWholeModule,
  readRepoFile,
} from '../../testing/edge-source';
import { computeNatalChart } from '../chart';
import {
  buildSynastryView,
  isSynastryView,
  resolveSynastryView,
  type SynastryView,
} from '../synastry-view';
import { toStoredBirthChart } from '../stored';
import type { NatalChart } from '../types';

const BUNDLE = 'supabase/functions/_shared/astrology-engine.generated.ts';

type Bundle = {
  buildSynastryView: (own: unknown, other: unknown) => SynastryView;
  hydrateStoredChart: (raw: unknown) => NatalChart | null;
  SCORING_MODEL_VERSION: number;
};

let bundle: Bundle;

beforeAll(async () => {
  // Compile the COMMITTED artefact, not the sources it came from. If the two
  // have diverged, `npm run validate:edge-astrology` is what says so; this
  // suite proves the artefact on disk behaves like the engine.
  //
  // Through `loadWholeModule` rather than by hand: it writes into the harness's
  // per-process scratch directory, which `cleanupEdgeModules()` in `afterAll`
  // then removes. Doing it inline left a `.edge-source` directory behind inside
  // `src/` after every run — one `git add .` away from being committed.
  expect(
    existsSync(path.join(REPO_ROOT, BUNDLE)),
    `${BUNDLE} is missing — run npm run build:edge-astrology`,
  ).toBe(true);
  bundle = await loadWholeModule<Bundle>(BUNDLE, 'astrology-bundle');
});

afterAll(() => cleanupEdgeModules());

// Real-ish birth records, fictional people. Chosen to exercise every branch:
// full data, no birth time, no birthplace.
const PEOPLE = {
  montreal: computeNatalChart({
    date: '1994-07-14', time: '03:47', timezone: 'America/Montreal',
    latitude: 45.5017, longitude: -73.5673,
  }),
  paris: computeNatalChart({
    date: '1991-11-02', time: '19:20', timezone: 'Europe/Paris',
    latitude: 48.8566, longitude: 2.3522,
  }),
  tokyo: computeNatalChart({
    date: '1988-03-21', time: '06:05', timezone: 'Asia/Tokyo',
    latitude: 35.6762, longitude: 139.6503,
  }),
  noTime: computeNatalChart({
    date: '1990-01-15', time: null, timezone: 'America/New_York',
    latitude: 40.7128, longitude: -74.006,
  }),
  noPlace: computeNatalChart({
    date: '1985-09-09', time: '11:11', timezone: 'Europe/London',
    latitude: null, longitude: null,
  }),
};

const PAIRS: Array<[keyof typeof PEOPLE, keyof typeof PEOPLE]> = [
  ['montreal', 'paris'],
  ['montreal', 'tokyo'],
  ['paris', 'tokyo'],
  ['montreal', 'noTime'],
  ['noTime', 'noPlace'],
  ['paris', 'noPlace'],
];

describe('the bundle is the engine, not a copy of it', () => {
  it('is committed, self-contained, and marked generated', () => {
    const source = readRepoFile(BUNDLE);
    expect(source).toContain('@generated by scripts/build-edge-astrology.mjs');
    expect(source).toContain('DO NOT EDIT');
    // Deno cannot resolve a bare npm specifier here; the build script asserts
    // this too, and this is the second lock.
    for (const dep of ['astronomy-engine', 'luxon', 'tz-lookup', '@supabase/supabase-js']) {
      expect(source).not.toMatch(new RegExp(`from\\s+["']${dep}["']`));
    }
    expect(source).not.toMatch(/\bprocess\.env\b/);
    expect(source).not.toMatch(/\brequire\(/);
  });

  it('reports the same scoring model version as the engine', async () => {
    const { SCORING_MODEL_VERSION } = await import('../version');
    expect(bundle.SCORING_MODEL_VERSION).toBe(SCORING_MODEL_VERSION);
  });

  it.each(PAIRS)('scores %s × %s identically to the shared engine', (a, b) => {
    const own = toStoredBirthChart(PEOPLE[a]);
    const other = toStoredBirthChart(PEOPLE[b]);

    const fromEngine = buildSynastryView(own, other);
    const fromBundle = bundle.buildSynastryView(own, other);

    // Deep equality, not "close enough": the same code on the same input must
    // produce the same object, or the generation step is not doing its job.
    expect(fromBundle).toEqual(fromEngine);
  });

  it('agrees on the fallback states too', () => {
    for (const [own, other] of [
      [null, toStoredBirthChart(PEOPLE.paris)],
      [toStoredBirthChart(PEOPLE.paris), null],
      [null, null],
      [{}, {}],
      ['not a chart', 42],
    ] as Array<[unknown, unknown]>) {
      expect(bundle.buildSynastryView(own, other)).toEqual(buildSynastryView(own, other));
    }
  });
});

describe('the published reading carries no chart geometry', () => {
  it('contains no longitude, no coordinates and no birth field', () => {
    const view = bundle.buildSynastryView(
      toStoredBirthChart(PEOPLE.montreal),
      toStoredBirthChart(PEOPLE.paris),
    );
    const json = JSON.stringify(view);
    expect(json).not.toContain('longitude');
    expect(json).not.toContain('latitude');
    expect(json).not.toContain('coordinates');
    expect(json).not.toMatch(/birth_/);
    expect(json).not.toContain('utcInstant');
    expect(json).not.toContain('timezone');
  });

  it('names bodies and aspects, and carries only two angular measurements', () => {
    const view = bundle.buildSynastryView(
      toStoredBirthChart(PEOPLE.montreal),
      toStoredBirthChart(PEOPLE.paris),
    ) as Extract<SynastryView, { source: 'aspects' }>;
    expect(view.source).toBe('aspects');
    for (const aspect of view.headline.topAspects) {
      // The shape is pinned so a NEW numeric field cannot appear unnoticed.
      // `separation` and `orb` are the two that describe this pair's geometry
      // and are quantised on the way out; `angle` and `maxOrb` are constants
      // from the aspect table and the orb policy, identical for everybody.
      expect(Object.keys(aspect).sort()).toEqual(
        ['angle', 'bodyA', 'bodyB', 'contribution', 'kind', 'maxOrb', 'name', 'orb', 'separation'],
      );
      expect([0, 60, 90, 120, 180]).toContain(aspect.angle);
    }
  });
});

describe('resolveSynastryView — what each client renders', () => {
  const own = toStoredBirthChart(PEOPLE.montreal);
  const other = toStoredBirthChart(PEOPLE.paris);

  it('prefers the server reading when one arrives', () => {
    const server = bundle.buildSynastryView(own, other);
    // Charts deliberately swapped in the local arguments: if the local branch
    // ran, the answer would differ. It must not.
    expect(resolveSynastryView(server, null, null)).toEqual(server);
  });

  it('computes locally when the server sent nothing', () => {
    for (const missing of [null, undefined]) {
      expect(resolveSynastryView(missing, own, other)).toEqual(buildSynastryView(own, other));
    }
  });

  it('computes locally rather than trusting a malformed payload', () => {
    // The payload crosses the network. A cast would turn a missing `frames`
    // array into a crash inside a render; the guard turns it into a fallback.
    for (const junk of [
      42, 'aspects', [], {}, { source: 'aspects' },
      { source: 'aspects', frames: [] },
      { source: 'aspects', frames: [{}], headline: {} },
      { source: 'aspects', frames: [{}], headline: { score: 'high' }, interpretiveAspects: [] },
      { source: 'nonsense' },
    ]) {
      expect(isSynastryView(junk)).toBe(false);
      expect(resolveSynastryView(junk, own, other)).toEqual(buildSynastryView(own, other));
    }
  });

  it('accepts a well-formed sign-rhythm answer from the server', () => {
    const fallback = { source: 'sign-rhythm', reason: 'missing_other_chart' };
    expect(isSynastryView(fallback)).toBe(true);
    expect(resolveSynastryView(fallback, own, other)).toEqual(fallback);
  });

  it('degrades to sign-rhythm, never to a fabricated score', () => {
    const view = resolveSynastryView(null, own, null);
    expect(view.source).toBe('sign-rhythm');
    expect(view).not.toHaveProperty('headline');
  });
});

describe('both platforms are wired to the same helper', () => {
  it.each([
    ['apps/web/src/components/SynastryOverview.tsx', 'matchSynastry'],
    ['apps/mobile/app/premium-screens/synastry.tsx', 'matchSynastry'],
  ])('%s prefers the server reading', (file, stateName) => {
    const source = readRepoFile(file);
    expect(source).toContain('resolveSynastryView');
    expect(source).toContain(stateName);
    // Reads `response.synastry` into that state.
    expect(source).toMatch(/set[A-Za-z]*Synastry\((?:response|payload)?\.?synastry/);
    // And no longer calls the local-only entry point directly, which is what
    // required the longitudes.
    expect(source).not.toMatch(/[^e]buildSynastryView\(/);
  });

  it('the edge function computes and returns it', () => {
    const source = readRepoFile('supabase/functions/get-profile-chart/index.ts');
    expect(source).toContain("from '../_shared/astrology-engine.generated.ts'");
    expect(source).toContain('buildSynastryView(');
    expect(source).toContain('withRoundedOrbs(');
    expect(source).toContain('synastry }');
    // The viewer's own chart is read server-side, so the client no longer has
    // to send it — and never sends someone else's.
    expect(source).toContain("select('birth_chart')");
  });

  it('treats a failed synastry computation as non-fatal', () => {
    // The reading is the product; the compatibility panel is a section of it.
    // A viewer whose own birth_chart cannot be read still gets the profile.
    const source = readRepoFile('supabase/functions/get-profile-chart/index.ts');
    const block = source.slice(source.indexOf('let synastry'), source.indexOf('// 6b.'));
    expect(block).toContain('try {');
    expect(block).toContain('catch');
    expect(block).not.toContain('return jsonError');
  });
});
