// The zodiac lookup table and the two conversions that use it — extracted
// from `chart.ts` on 2026-09-07, with no change to any value or behaviour.
//
// WHY IT MOVED
// ------------
// `chart.ts` opens with `import * as Astronomy from 'astronomy-engine'` and
// pulls in `./time` (luxon + tz-lookup). Everything in this file is pure
// arithmetic over a twelve-element array and needs none of that — but
// `stored.ts` imported `ZODIAC_SIGNS` and `placementToLongitude` from
// `chart.ts`, so hydrating a stored chart dragged the whole ephemeris in.
//
// That mattered the day the synastry computation moved server-side
// (docs/security-audit-2026-09-07.md, JUNO-01): the edge bundle generated by
// `scripts/build-edge-astrology.mjs` must contain no npm dependency at all, and
// `scripts/validate-edge-astrology.mjs` fails the build if one appears. With
// the table still living beside the ephemeris, tree-shaking that import was a
// hope rather than a guarantee. Now it is structural.
//
// `chart.ts` re-exports all four names, so every existing import keeps working.

import type { Placement, ZodiacSign } from './types';

export const ZODIAC_SIGNS: readonly ZodiacSign[] = [
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces',
] as const;

/** Wrap any angle into [0, 360). */
export function normalize360(x: number): number {
  return ((x % 360) + 360) % 360;
}

/**
 * Split a longitude into its sign and its degree within that sign.
 *
 * Both outputs are rounded to two decimals — the storage quantum asserted by
 * `engine-contract.test.ts`. This is the ENGINE's internal precision and is
 * deliberately untouched by the JUNO-01 payload minimisation, which happens at
 * the edge of the network and nowhere else.
 */
export function longitudeToPlacement(longitude: number): Placement {
  const lon = normalize360(longitude);
  const idx = Math.floor(lon / 30);
  const degree = lon % 30;
  return {
    sign: ZODIAC_SIGNS[idx],
    degree: Math.round(degree * 100) / 100,
    longitude: Math.round(lon * 100) / 100,
  };
}

/** The inverse: rebuild a longitude from a sign and a degree within it. */
export function placementToLongitude(p: { sign: string; degree: number }): number {
  const idx = ZODIAC_SIGNS.indexOf(p.sign as ZodiacSign);
  if (idx < 0) return 0;
  return idx * 30 + p.degree;
}
