import type { ProductInput, Strategy } from "@/types/strategy";
import type { LearningMemory, SavedRun, TestResult } from "@/types/workspace";
import type {
  ReviewBoardSummary,
  ReviewComment,
  ReviewItem,
} from "@/types/review";
import {
  CRITICAL_REVIEW_ITEM_KINDS,
  NON_CRITICAL_REVIEW_ITEM_KINDS,
} from "@/types/review";
import { reviewItemKindLabel } from "@/lib/review/review-board";
import { awarenessLabel } from "./awareness";
import { sophisticationLabel } from "./sophistication";
import { windowKindLabel } from "./calendar";

// Optional Campaign Log context — emitted when the caller passes
// workspace state. Absent → existing brief is byte-identical.
export interface ExportBriefWorkspaceContext {
  runs?: SavedRun[];
  results?: TestResult[];
  learningMemory?: LearningMemory;
  // Optional Review & Approval board — when provided AND the board
  // has at least one item, the exporter appends an `## Approval Pack`
  // section. Absent or empty → existing brief is byte-identical.
  reviewBoard?: {
    items: ReviewItem[];
    comments: ReviewComment[];
    summary: ReviewBoardSummary;
  };
}

// generateExportBrief — assembles a clean, single-page markdown brief
// covering every section of the strategy. Designed to be pasted into
// Notion, Google Docs, or a team message and still read cleanly. No
// emojis, no decorative characters.
//
// Section order follows the stakeholder reading flow:
//   1. Product snapshot
//   2. Journey status
//   3. Audience avatars
//   4. Positioning (+ central promise / mechanism)
//   5. Offer architecture
//   6. Campaign calendar
//   7. Ad concept cards
//   8. Hook library
//   9. Creator briefs / Video scripts / Shot lists
//  10. Quality strip: Creative QA / Tracking readiness / KPI ladder /
//      KPI diagnosis / Ad review checklist / Applied ad reviews
//  11. Editor handoff
// Secondary reference sections (score, awareness diagnosis, awareness
// variants, offer diagnosis, headlines, landing, store, experiments,
// CTA bank, static briefs, ad variants, generic-copy flags) follow
// after the primary flow so the strategy doc reads top-down.

export function generateExportBrief(
  input: ProductInput,
  strategy: Strategy,
  workspace?: ExportBriefWorkspaceContext
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${input.name || "Untitled product"} — strategy brief`);
  lines.push("");
  lines.push(
    `Generated by BigAd. All copy is a starting draft to be edited, not finished marketing.`
  );
  lines.push("");

  // 1. Product snapshot
  section(lines, "Product snapshot");
  lines.push(`- **Name:** ${input.name || "—"}`);
  lines.push(`- **Category:** ${input.category || "—"}`);
  lines.push(`- **Description:** ${input.description || "—"}`);
  lines.push(`- **Price:** ${input.price || "—"}`);
  lines.push(`- **Business model:** ${input.businessModel}`);
  lines.push(`- **Audience:** ${input.audience || "—"}`);
  lines.push(`- **Core pain:** ${input.audiencePain || "—"}`);
  lines.push(`- **Competitors:** ${input.competitors || "—"}`);
  lines.push(`- **Differentiator:** ${input.differentiator || "—"}`);
  lines.push(`- **Goal:** ${input.goal || "—"}`);
  lines.push(`- **Awareness:** ${awarenessLabel(input.awareness)}`);
  lines.push(`- **Sophistication:** ${sophisticationLabel(input.sophistication)}`);
  if (input.campaignType) {
    lines.push(`- **Campaign type:** ${campaignTypeLabel(input.campaignType)}`);
  }
  const ctx = input.offerContext;
  if (ctx) {
    if (typeof ctx.cogsPercent === "number") {
      lines.push(`- **COGS %:** ${ctx.cogsPercent}`);
    }
    if (typeof ctx.targetMarginPercent === "number") {
      lines.push(`- **Target margin %:** ${ctx.targetMarginPercent}`);
    }
    if (typeof ctx.currentAOV === "number") {
      lines.push(`- **Current AOV:** ${ctx.currentAOV}`);
    }
    if (typeof ctx.targetROAS === "number") {
      lines.push(`- **Target ROAS:** ${ctx.targetROAS}x`);
    }
  }
  lines.push("");

  // 2. Journey Status
  section(lines, "Journey Status");
  const js = strategy.journeyStatus;
  lines.push(
    `Current stage: **${journeyStageLabel(js.currentStage)}** — ready to spend: ${js.readyToSpend ? "yes" : "no"}.`
  );
  lines.push("");
  lines.push(`**Next step.** ${js.nextStep}`);
  lines.push("");
  if (js.blockers.length > 0) {
    lines.push(`**Blockers:**`);
    for (const b of js.blockers) {
      const src = b.sourceCheck ? ` (source: ${b.sourceCheck})` : "";
      lines.push(`- [${b.kind}] ${b.message}${src}`);
    }
    lines.push("");
  }
  if (js.warnings.length > 0) {
    lines.push(`**Warnings:**`);
    for (const w of js.warnings) {
      const src = w.sourceCheck ? ` (source: ${w.sourceCheck})` : "";
      lines.push(`- [${w.kind}] ${w.message}${src}`);
    }
    lines.push("");
  }

  // 3. Audience Avatars
  section(lines, "Audience Avatars");
  if (strategy.audienceAvatars.length === 0) {
    lines.push("_No avatars generated for this input._");
    lines.push("");
  } else {
    for (const av of strategy.audienceAvatars) {
      lines.push(`### ${av.label} (${av.id})`);
      lines.push("");
      lines.push(`- **Buying trigger:** ${av.buyingTrigger}`);
      lines.push(`- **Core pain:** ${av.corePain}`);
      lines.push(`- **Desired outcome:** ${av.desiredOutcome}`);
      lines.push(`- **Best channel angle:** ${av.bestChannelAngle}`);
      lines.push("");
      lines.push(`**Objections:**`);
      lines.push("");
      lines.push(`| Kind | Statement | Reframe |`);
      lines.push(`|------|-----------|---------|`);
      for (const o of av.objections) {
        lines.push(
          `| ${o.kind} | ${o.statement.replace(/\|/g, "/")} | ${o.reframe.replace(/\|/g, "/")} |`
        );
      }
      lines.push("");
      lines.push(`**Failed alternatives:**`);
      for (const fa of av.failedAlternatives) lines.push(`- ${fa}`);
      lines.push("");
      lines.push(
        `**Emotional language:** ${av.emotionalLanguage.map((p) => `"${p}"`).join(" · ")}`
      );
      lines.push("");
      lines.push(`**Proof needed:**`);
      for (const p of av.proofNeeded) lines.push(`- ${p}`);
      lines.push("");
    }
  }

  // 4. Positioning
  section(lines, "Positioning");
  lines.push(strategy.positioning.statement);
  lines.push("");
  lines.push(`- **For whom:** ${strategy.positioning.forWhom}`);
  lines.push(`- **Category:** ${strategy.positioning.category}`);
  lines.push(`- **Unlike:** ${strategy.positioning.unlike}`);
  lines.push(`- **Unique:** ${strategy.positioning.unique}`);
  lines.push("");
  lines.push(`**Central promise.** ${strategy.centralPromise}`);
  lines.push("");
  lines.push(`**Unique mechanism.** ${strategy.uniqueMechanism}`);
  lines.push("");

  // 5. Offer architecture
  section(lines, "Offer Architecture");
  strategy.offers.forEach((o, i) => {
    const roas =
      typeof o.breakevenROAS === "number"
        ? `${o.breakevenROAS.toFixed(2)}x breakeven ROAS`
        : "breakeven ROAS not computed";
    lines.push(
      `${i + 1}. **${offerKindLabel(o.kind)} — ${o.label}.** ${roas}; stickiness risk: ${o.stickinessRisk}; awareness fit: ${o.awarenessFit.join(", ") || "—"}.`
    );
    lines.push(`   - Why: ${o.rationale}`);
    if (typeof o.discountPercent === "number") {
      lines.push(`   - Assumed discount: ${o.discountPercent}%`);
    }
    if (o.notes) {
      lines.push(`   - Note: ${o.notes}`);
    }
  });
  lines.push("");

  // 6. Campaign calendar
  section(lines, "Campaign Calendar");
  lines.push(
    `Campaign type: **${campaignTypeLabel(strategy.campaignCalendar.campaignType)}** — anchor: ${strategy.campaignCalendar.anchorLabel}.`
  );
  lines.push("");
  strategy.campaignCalendar.windows.forEach((w, i) => {
    const range = formatRange(w.startOffsetDays, w.durationDays);
    const dipFlag = w.dipForecasts.length > 0 ? "  (forecast dips)" : "";
    const offer = w.recommendedOfferKind ? offerKindLabel(w.recommendedOfferKind) : "—";
    lines.push(
      `${i + 1}. **${windowKindLabel(w.kind)} — ${w.label}.** ${range}${dipFlag}`
    );
    lines.push(`   - KPI: ${w.primaryKPI}`);
    lines.push(`   - Readiness gate: ${w.readinessGate}`);
    lines.push(`   - Recommended offer: ${offer}`);
    // Audience architecture
    const arch = w.recommendedArchitecture;
    const archLabel = arch.kind === "promo-3-tier" ? "Promo 3-tier" : "Single-tier";
    const tierNames = arch.tiers.map((t) => t.name).join(" / ");
    lines.push(
      `   - Architecture: ${archLabel} — ${tierNames}${arch.budgetSplitHint ? ` (budget split ${arch.budgetSplitHint})` : ""}.`
    );
    lines.push(`     - Rationale: ${arch.rationale}`);
    for (const t of arch.tiers) {
      lines.push(
        `     - ${t.name} (${audienceIntentLabel(t.intent)})${t.notes ? `: ${t.notes}` : ""}`
      );
    }
    // Dip forecasts
    if (w.dipForecasts.length > 0) {
      lines.push(`   - Dip forecasts:`);
      for (const dip of w.dipForecasts) {
        lines.push(
          `     - ${dipMechanismLabel(dip.mechanism)} (${dip.severity}, ~day +${dip.expectedAroundDayOffset} into window): ${dip.rationale}`
        );
      }
    }
    // Retrospective gate
    if (w.retrospectiveGate) {
      lines.push(`   - Pre-peak retrospective gate (${w.retrospectiveGate.questions.length} questions):`);
      for (const q of w.retrospectiveGate.questions) {
        lines.push(`     - **[${q.topic}]** ${q.question}`);
        lines.push(`       - Why it matters: ${q.whyItMatters}`);
      }
    }
    lines.push(`   - Notes: ${w.notes}`);
  });
  lines.push("");

  // 7. Ad Concept Cards
  section(lines, "Ad Concept Cards");
  if (strategy.adConceptCards.length === 0) {
    lines.push("_No concept cards generated for this input._");
    lines.push("");
  } else {
    for (const c of strategy.adConceptCards) {
      lines.push(`### ${c.name} (${c.id})`);
      lines.push("");
      lines.push(`- **Target avatar:** ${c.targetAvatarId}`);
      lines.push(
        `- **Hook (${hookPatternLabel(c.hook.pattern)}):** ${c.hook.text}`
      );
      lines.push(`- **Promise:** ${c.promise}`);
      lines.push(`- **Proof angle:** ${c.proofAngle}`);
      lines.push(`- **Offer tie-in:** ${c.offerTieIn}`);
      lines.push(`- **Visual idea:** ${c.visualIdea}`);
      lines.push(`- **Format fit:** ${c.formatFit.join(", ")}`);
      lines.push(`- **Test hypothesis:** ${c.testHypothesis}`);
      lines.push(`- **Next variant:** ${c.nextVariantSuggestion}`);
      lines.push("");
    }
  }

  // 8. Hook Library
  section(lines, "Hook Library");
  if (strategy.hookLibrary.items.length === 0) {
    lines.push("_No hook library generated for this input._");
    lines.push("");
  } else {
    const patterns: ReadonlyArray<typeof strategy.hookLibrary.items[number]["pattern"]> = [
      "pain-first",
      "outcome-first",
      "contrarian",
      "proof-led",
      "curiosity",
      "comparison",
      "mistake",
      "before-after",
    ];
    for (const pattern of patterns) {
      const items = strategy.hookLibrary.items.filter((it) => it.pattern === pattern);
      if (items.length === 0) continue;
      lines.push(`### ${hookPatternLabel(pattern)}`);
      lines.push("");
      for (const it of items) {
        lines.push(`- **Hook:** ${it.text}`);
        lines.push(
          `  - Awareness fit: ${it.awarenessFit.join(", ")} · Avatar fit: ${it.avatarFit.join(", ")}`
        );
        lines.push(`  - Risk: ${it.riskNote}`);
      }
      lines.push("");
    }
  }

  // 9a. Creator briefs
  section(lines, "Creator Briefs");
  if (strategy.creatorBriefs.length === 0) {
    lines.push("_No briefs generated for this input._");
    lines.push("");
  } else {
    strategy.creatorBriefs.forEach((brief) => {
      lines.push(`### ${brief.forAngle}`);
      lines.push("");
      lines.push(`- **Brief ID:** ${brief.id}`);
      lines.push(`- **Total duration:** ~${brief.durationSeconds}s`);
      lines.push(`- **Framing:** ${brief.framing}`);
      if (brief.notes) {
        lines.push(`- **Note:** ${brief.notes}`);
      }
      lines.push("");
      lines.push(`**Alt hooks:**`);
      for (const h of brief.altHooks) lines.push(`- ${h}`);
      lines.push("");
      lines.push(`**Sections:**`);
      for (const s of brief.sections) {
        lines.push(
          `- **${briefSectionLabel(s.kind)} — ${s.label}** (~${s.durationSeconds}s). ${s.beat}`
        );
        if (s.whatToSay && s.whatToSay.length > 0) {
          for (const line of s.whatToSay) lines.push(`  - Say: ${line}`);
        }
        if (s.whatToShow && s.whatToShow.length > 0) {
          for (const line of s.whatToShow) lines.push(`  - Show: ${line}`);
        }
        if (s.doNot && s.doNot.length > 0) {
          for (const line of s.doNot) lines.push(`  - Do not: ${line}`);
        }
      }
      lines.push("");
      lines.push(`**Deliverables:**`);
      for (const d of brief.deliverables) lines.push(`- ${d}`);
      lines.push("");
    });
  }

  // 9b. Video scripts
  section(lines, "Video Scripts");
  if (strategy.videoScripts.length === 0) {
    lines.push("_No video scripts generated for this input._");
    lines.push("");
  } else {
    strategy.videoScripts.forEach((script) => {
      const matched = strategy.creatorBriefs.find((b) => b.id === script.briefId);
      const ref = matched ? matched.forAngle : script.briefId;
      lines.push(`### ${script.briefId} — ${ref}`);
      lines.push("");
      lines.push(`Total duration: ~${script.totalDurationSeconds}s.`);
      lines.push("");
      lines.push(`| # | Section | Kind | Start | Duration | Text |`);
      lines.push(`|---|---------|------|-------|----------|------|`);
      for (const ln of script.lines) {
        const text = ln.text.replace(/\|/g, "/");
        lines.push(
          `| ${ln.index} | ${briefSectionIndexLabel(ln.briefSectionIndex)} | ${scriptLineKindLabel(ln.kind)} | ${ln.startSeconds}s | ${ln.durationSeconds}s | ${text} |`
        );
      }
      lines.push("");
    });
  }

  // 9c. Shot lists
  section(lines, "Shot Lists");
  if (strategy.shotLists.length === 0) {
    lines.push("_No shot lists generated for this input._");
    lines.push("");
  } else {
    strategy.shotLists.forEach((list) => {
      const matched = strategy.creatorBriefs.find((b) => b.id === list.briefId);
      const angleRef = matched ? matched.forAngle : list.briefId;
      lines.push(`### ${list.briefId} — ${angleRef}`);
      lines.push("");
      lines.push(`Total shots: ${list.totalShots}.`);
      lines.push("");
      lines.push(`| # | Kind | Framing | Angle | Duration | Sound | Props |`);
      lines.push(`|---|------|---------|-------|----------|-------|-------|`);
      for (const it of list.items) {
        const propsCell = it.props.join("; ");
        const sound = it.sound.replace(/\|/g, "/");
        const framing = it.framing.replace(/\|/g, "/");
        lines.push(
          `| ${it.index} | ${shotKindLabel(it.kind)} | ${framing} | ${cameraAngleLabel(it.angle)} | ${it.duration} | ${sound} | ${propsCell} |`
        );
      }
      lines.push("");
    });
  }

  // 10a. Creative QA
  section(lines, "Creative QA");
  if (strategy.creativeQa.length === 0) {
    lines.push("_No QA report generated._");
    lines.push("");
  } else {
    for (const cq of strategy.creativeQa) {
      const matched =
        cq.scope === "all"
          ? null
          : strategy.creatorBriefs.find((b) => b.id === cq.scope);
      const heading =
        cq.scope === "all"
          ? "Aggregate"
          : matched
          ? `${cq.scope} — ${matched.forAngle}`
          : cq.scope;
      lines.push(`### ${heading}`);
      lines.push("");
      lines.push(
        `Blockers: ${cq.blockerCount}. Warnings: ${cq.warningCount}.`
      );
      lines.push("");
      lines.push(`| Rule | Severity | Message | Suggestion |`);
      lines.push(`|------|----------|---------|------------|`);
      for (const f of cq.findings) {
        lines.push(
          `| ${f.rule} | ${f.severity} | ${f.message.replace(/\|/g, "/")} | ${(f.suggestion || "—").replace(/\|/g, "/")} |`
        );
      }
      lines.push("");
    }
  }

  // 10b. Tracking Readiness
  section(lines, "Tracking Readiness");
  const tr = strategy.trackingReadiness;
  lines.push(
    `Score: **${tr.score}/100** — status: **${trackingStatusLabel(tr.status)}**. Blockers: ${tr.blockers}. Warnings: ${tr.warnings}.`
  );
  lines.push("");
  for (const c of tr.checks) {
    lines.push(`- **${c.label} — ${readinessStatusLabel(c.status)}.** ${c.rationale}`);
    if (c.fix) lines.push(`  - Fix: ${c.fix}`);
  }
  lines.push("");

  // 10c. KPI Target Ladder
  section(lines, "KPI Target Ladder");
  lines.push(`| KPI | Tier | Breakeven | Scaling | Direction |`);
  lines.push(`|-----|------|-----------|---------|-----------|`);
  for (const t of strategy.kpiLadder.targets) {
    lines.push(
      `| ${kpiNameLabel(t.kpi)} | ${ladderTierLabel(t.tier)} | ${t.breakeven} | ${t.scaling} | ${t.direction} |`
    );
  }
  lines.push("");

  // 10d. KPI Diagnosis
  section(lines, "KPI Diagnosis");
  lines.push(
    `Primary category: **${diagnosisCategoryLabel(strategy.kpiDiagnosis.primaryCategory)}**. Synthetic sample anchored near healthy-tier breakeven.`
  );
  lines.push("");
  const snap = strategy.kpiDiagnosis.snapshot;
  lines.push(
    `Snapshot: CTR ${fmtMetric(snap.ctr)}, CPC ${fmtMetric(snap.cpc)}, CPM ${fmtMetric(snap.cpm)}, CPA ${fmtMetric(snap.cpa)}, CVR ${fmtMetric(snap.cvr)}, ROAS ${fmtMetric(snap.roas)}, Hook-rate ${fmtMetric(snap.hookRate)}, Hold-rate ${fmtMetric(snap.holdRate)}.`
  );
  lines.push("");
  for (const f of strategy.kpiDiagnosis.findings) {
    lines.push(`- **${diagnosisCategoryLabel(f.category)} — ${f.signal}.** ${f.inference}`);
    lines.push(`  - Action: ${f.recommendedAction}`);
  }
  lines.push("");

  // 10e. Ad Review Checklist
  section(lines, "Ad Review Checklist");
  lines.push(`Total weight: ${strategy.adReview.totalWeight}.`);
  lines.push("");
  for (const a of strategy.adReview.axes) {
    lines.push(`- **${a.label} (weight ${a.weight}).** ${a.question}`);
  }
  lines.push("");

  // 10f. Applied Ad Reviews — per-brief evaluation against the checklist.
  section(lines, "Applied Ad Reviews");
  if (strategy.appliedAdReviews.length === 0) {
    lines.push("_No briefs were evaluated against the checklist._");
    lines.push("");
  } else {
    for (const review of strategy.appliedAdReviews) {
      const matched = strategy.creatorBriefs.find(
        (b) => b.id === review.targetId
      );
      const ref = matched ? matched.forAngle : review.targetId;
      lines.push(`### ${review.targetId} — ${ref}`);
      lines.push("");
      lines.push(
        `Score: **${review.totalScore}/${review.maxScore} (${review.scorePercent}%)** — verdict: **${appliedVerdictLabel(review.verdict)}**.`
      );
      lines.push("");
      lines.push(`| Axis | Verdict | Score | Evidence | Fix |`);
      lines.push(`|------|---------|-------|----------|-----|`);
      for (const f of review.findings) {
        const evidence = f.evidence.replace(/\|/g, "/");
        const fix = (f.fix ?? "—").replace(/\|/g, "/");
        lines.push(
          `| ${reviewAxisLabel(f.axis)} | ${appliedFindingVerdictLabel(f.verdict)} | ${f.scoreContribution}/${f.weight} | ${evidence} | ${fix} |`
        );
      }
      lines.push("");
    }
  }

  // 11. Editor Handoff
  section(lines, "Editor Handoff");
  if (strategy.editorHandoffs.length === 0) {
    lines.push("_No editor handoffs generated._");
    lines.push("");
  } else {
    for (const h of strategy.editorHandoffs) {
      lines.push(h.markdown);
      lines.push("");
    }
  }

  // 12. Execution OS — Creative Testing Matrix
  section(lines, "Creative Testing Matrix");
  const ctm = strategy.creativeTestingMatrix;
  lines.push(
    `Max concurrent tests: **${ctm.maxConcurrentTests}**. First batch: **${ctm.recommendedFirstBatch.length}** cell${ctm.recommendedFirstBatch.length === 1 ? "" : "s"} of ${ctm.testCells.length} planned.`
  );
  lines.push("");
  if (ctm.testingWarnings.length > 0) {
    lines.push(`**Testing warnings:**`);
    for (const w of ctm.testingWarnings) {
      lines.push(`- [${w.kind}] ${oneLine(w.message)}`);
    }
    lines.push("");
  }
  const firstBatchSet = new Set(ctm.recommendedFirstBatch);
  const firstBatchCells = ctm.testCells.filter((c) => firstBatchSet.has(c.id));
  if (firstBatchCells.length > 0) {
    lines.push(`**Recommended first batch:**`);
    lines.push("");
    lines.push(
      `| ID | Concept | Avatar | Hook | Format | Funnel | Tier | Offer | Primary KPI | Kill | Scale | Learning | Days |`
    );
    lines.push(
      `|----|---------|--------|------|--------|--------|------|-------|-------------|------|-------|----------|------|`
    );
    for (const c of firstBatchCells) {
      lines.push(
        `| ${c.id} | ${c.conceptId} | ${c.avatarId} | ${oneLine(c.hook).replace(/\|/g, "/")} | ${c.format} | ${c.funnelStage} | ${c.audienceTier.replace(/\|/g, "/")} | ${c.offer} | ${c.primaryKpi} | ${c.killRule.comparator} ${c.killRule.threshold} after $${c.killRule.afterSpend} | ${c.scaleRule.comparator} ${c.scaleRule.threshold} after $${c.scaleRule.afterSpend} | ${oneLine(c.learningGoal).replace(/\|/g, "/")} | ${c.estimatedRunDays} |`
      );
    }
    lines.push("");
  } else {
    lines.push("_No first-batch cells planned._");
    lines.push("");
  }
  const queuedCells = ctm.testCells.filter((c) => !firstBatchSet.has(c.id));
  if (queuedCells.length > 0) {
    lines.push(`**Queued cells (after first batch):**`);
    lines.push("");
    lines.push(
      `| ID | Concept | Avatar | Hook | Format | Funnel | Tier | Offer | Primary KPI | Days |`
    );
    lines.push(
      `|----|---------|--------|------|--------|--------|------|-------|-------------|------|`
    );
    for (const c of queuedCells) {
      lines.push(
        `| ${c.id} | ${c.conceptId} | ${c.avatarId} | ${oneLine(c.hook).replace(/\|/g, "/")} | ${c.format} | ${c.funnelStage} | ${c.audienceTier.replace(/\|/g, "/")} | ${c.offer} | ${c.primaryKpi} | ${c.estimatedRunDays} |`
      );
    }
    lines.push("");
  }

  // 13. Execution OS — Campaign Setup
  section(lines, "Campaign Setup");
  const cs = strategy.campaignSetup;
  lines.push(`Naming convention: \`${cs.namingConvention}\`.`);
  lines.push("");
  for (const camp of cs.campaigns) {
    lines.push(`### ${camp.name}`);
    lines.push("");
    lines.push(`- **Objective:** ${camp.objective}`);
    lines.push(`- **Conversion event:** ${camp.conversionEvent}`);
    lines.push(`- **Budget mode:** ${camp.budgetMode}`);
    lines.push(`- **Audience architecture:** ${camp.audienceArchitecture}`);
    lines.push(`- **UTM template:** \`${camp.utmTemplate}\``);
    lines.push(
      `- **Reporting columns:** ${camp.reportingColumns.join(", ")}`
    );
    lines.push("");
    for (const adSet of camp.adSets) {
      lines.push(`#### Ad set — ${adSet.name}`);
      lines.push("");
      lines.push(`- **Tier:** ${adSet.audienceTier}`);
      lines.push(`- **Budget split:** ${adSet.budgetSplit}`);
      lines.push(
        `- **Inclusions:** ${adSet.inclusions.join("; ") || "—"}`
      );
      lines.push(
        `- **Exclusions:** ${adSet.exclusions.join("; ") || "—"}`
      );
      lines.push(`- **Placements:** ${adSet.placements.join(", ")}`);
      lines.push(`- **Optimization event:** ${adSet.optimizationEvent}`);
      lines.push(`- **Ads:** ${adSet.ads.join(", ")}`);
      lines.push("");
    }
  }
  if (cs.preLaunchChecklist.length > 0) {
    lines.push(`**Pre-launch checklist:**`);
    lines.push("");
    for (const it of cs.preLaunchChecklist) {
      lines.push(
        `- [${it.status}] ${it.label}${it.source ? ` _(${it.source})_` : ""}`
      );
    }
    lines.push("");
  }

  // 14. Execution OS — Next Iteration Plan
  section(lines, "Next Iteration Plan");
  const nip = strategy.nextIterationPlan;
  for (const rec of nip.recommendations) {
    lines.push(`### ${rec.signal}`);
    lines.push("");
    lines.push(`${rec.diagnosis}`);
    lines.push("");
    if (rec.nextSteps.length > 0) {
      lines.push(`**Next steps:**`);
      for (const s of rec.nextSteps) lines.push(`- ${s}`);
      lines.push("");
    }
    if (rec.nextAssetsToProduce.length > 0) {
      lines.push(
        `**Next assets to produce:** ${rec.nextAssetsToProduce.join(", ")}.`
      );
      lines.push("");
    }
    if (rec.nextAnglesToTry.length > 0) {
      lines.push(
        `**Next angles to try:** ${rec.nextAnglesToTry.map((a) => oneLine(a)).join("; ")}.`
      );
      lines.push("");
    }
  }
  if (nip.nextAssetsToProduce.length > 0) {
    lines.push(
      `**Aggregated assets to produce:** ${nip.nextAssetsToProduce.join(", ")}.`
    );
    lines.push("");
  }
  if (nip.nextAnglesToTry.length > 0) {
    lines.push(
      `**Aggregated angles to try:** ${nip.nextAnglesToTry.map((a) => oneLine(a)).join("; ")}.`
    );
    lines.push("");
  }

  // ---- Secondary reference sections ----
  // Anything below this point is supporting material an operator can
  // skim after the primary flow above.

  // Strategy quality score
  section(lines, "Strategy quality score");
  lines.push(`**Overall:** ${strategy.score.overall}/100`);
  lines.push("");
  for (const d of strategy.score.dimensions) {
    lines.push(`- **${d.label} — ${d.score}/100.** ${d.explanation}`);
    lines.push(`  - Suggestion: ${d.suggestion}`);
  }
  lines.push("");

  // Awareness diagnosis
  section(lines, "Awareness diagnosis");
  lines.push(`Current stage: **${awarenessLabel(input.awareness)}**.`);
  lines.push("");
  for (const n of strategy.awarenessNotes) lines.push(`- ${n}`);
  lines.push("");
  lines.push(`Sophistication: **${sophisticationLabel(input.sophistication)}**.`);
  lines.push("");
  for (const n of strategy.sophisticationNotes) lines.push(`- ${n}`);
  lines.push("");

  // Offer diagnosis
  section(lines, "Offer diagnosis");
  lines.push(`- **Strongest promise:** ${strategy.diagnosis.strongestPromise}`);
  lines.push(`- **Weakest claim:** ${strategy.diagnosis.weakestClaim}`);
  lines.push(`- **Missing proof:** ${strategy.diagnosis.missingProof}`);
  lines.push(`- **Biggest objection:** ${strategy.diagnosis.biggestObjection}`);
  lines.push(
    `- **Recommended proof asset:** ${strategy.diagnosis.recommendedAsset} — ${strategy.diagnosis.recommendedAssetReason}`
  );
  lines.push(
    `- See §5 (Offer Architecture) for the full ranked recommendation set.`
  );
  lines.push("");

  // Top angles (ranked) — cross-reference for the Concepts section.
  section(lines, "Top angles (ranked by fit)");
  strategy.rankedAngles.forEach((a, i) => {
    lines.push(
      `${i + 1}. **${a.name}** — score ${a.score ?? 0}/100, best channel: ${a.channelFit ?? "—"}, stage: ${a.awarenessStage ?? "—"}.`
    );
    lines.push(`   - Hook: ${a.hook}`);
    if (a.objectionAddressed)
      lines.push(`   - Objection addressed: ${a.objectionAddressed}`);
    if (a.whyItCouldWork)
      lines.push(`   - Why it could work: ${a.whyItCouldWork}`);
  });
  lines.push("");

  // Headlines
  section(lines, "Headlines");
  strategy.headlines.forEach((h, i) => lines.push(`${i + 1}. ${h}`));
  lines.push("");

  // Copy variants by awareness stage
  section(lines, "Copy variants by awareness stage");
  for (const v of strategy.awarenessVariants) {
    lines.push(`### ${stageLabel(v.stage)}`);
    lines.push(`- **Headline:** ${v.headline}`);
    lines.push(`- **Ad hook:** ${v.adHook}`);
    lines.push(`- **Landing section angle:** ${v.landingAngle}`);
    lines.push("");
  }

  // Landing copy
  section(lines, "Landing copy");
  lines.push(`**Hero.** ${strategy.landing.hero}`);
  lines.push("");
  lines.push(`**Sub-hero.** ${strategy.landing.subhead}`);
  lines.push("");
  lines.push(`**Value bullets:**`);
  for (const b of strategy.landing.bullets) lines.push(`- ${b}`);
  lines.push("");
  lines.push(`**CTA:** ${strategy.landing.cta}`);
  lines.push(`**Social proof line:** ${strategy.landing.socialProofLine}`);
  lines.push("");
  lines.push(`**Objection handlers (on-page):**`);
  for (const o of strategy.landing.objectionsHandled) {
    lines.push(`- ${o.objection}`);
    lines.push(`  ${o.reply}`);
  }
  lines.push("");

  // Store copy
  section(lines, "Store copy");
  lines.push(`- **App name:** ${strategy.store.appName}`);
  lines.push(`- **Subtitle:** ${strategy.store.subtitle}`);
  lines.push(`- **Promotional text:** ${strategy.store.promoText}`);
  lines.push(`- **Keywords:** ${strategy.store.keywords.join(", ")}`);
  lines.push("");
  lines.push(`**Long description:**`);
  lines.push("");
  lines.push(strategy.store.description);
  lines.push("");

  // TikTok / Reels scripts
  section(lines, "TikTok / Reels Scripts");
  if (strategy.tiktokScripts.length === 0) {
    lines.push("_No short-form scripts generated for this input._");
    lines.push("");
  } else {
    strategy.tiktokScripts.forEach((s, i) => {
      lines.push(`### Script ${i + 1}`);
      lines.push("");
      lines.push(`- **Hook:** ${s.hook}`);
      lines.push(`- **Beats:**`);
      for (const beat of s.beats) lines.push(`  - ${beat}`);
      lines.push(`- **CTA:** ${s.cta}`);
      lines.push("");
    });
  }

  // Facebook / Meta ad concepts
  section(lines, "Meta Ad Concepts");
  if (strategy.facebookAds.length === 0) {
    lines.push("_No meta ad concepts generated for this input._");
    lines.push("");
  } else {
    strategy.facebookAds.forEach((c, i) => {
      lines.push(`### ${i + 1}. ${c.angle}`);
      lines.push("");
      lines.push(`- **Primary text:** ${c.primaryText}`);
      lines.push(`- **Headline:** ${c.headline}`);
      lines.push(`- **Description:** ${c.description}`);
      lines.push(`- **CTA:** ${c.cta}`);
      lines.push("");
    });
  }

  // Objections
  section(lines, "Objections");
  if (strategy.objections.length === 0) {
    lines.push("_No objections drafted._");
    lines.push("");
  } else {
    for (const o of strategy.objections) {
      lines.push(`- **${o.objection}**`);
      lines.push(`  ${o.reply}`);
    }
    lines.push("");
  }

  // Experiments
  section(lines, "Experiments");
  strategy.experiments.forEach((e, i) => {
    lines.push(`${i + 1}. **${e.hypothesis}**`);
    lines.push(`   - A: ${e.variantA}`);
    lines.push(`   - B: ${e.variantB}`);
    lines.push(`   - Metric: ${e.metric}`);
  });
  lines.push("");

  // CTA Bank
  section(lines, "CTA Bank");
  if (strategy.ctaBank.variants.length === 0) {
    lines.push("_No CTA variants generated._");
    lines.push("");
  } else {
    // Group by surface so the editor scans a clean table per placement.
    const ctaSurfaces = [
      "meta-feed",
      "meta-reels",
      "tiktok",
      "landing-primary",
      "email",
    ] as const;
    for (const surface of ctaSurfaces) {
      const inSurface = strategy.ctaBank.variants.filter(
        (v) => v.surface === surface
      );
      if (inSurface.length === 0) continue;
      lines.push(`### ${ctaSurfaceLabel(surface)}`);
      lines.push("");
      lines.push(`| Style | Text | Rationale |`);
      lines.push(`|-------|------|-----------|`);
      for (const v of inSurface) {
        lines.push(
          `| ${ctaStyleLabel(v.style)} | ${v.text.replace(/\|/g, "/")} | ${v.rationale.replace(/\|/g, "/")} |`
        );
      }
      lines.push("");
    }
  }

  // Static Briefs
  section(lines, "Static Briefs");
  if (strategy.staticBriefs.length === 0) {
    lines.push("_No static briefs generated._");
    lines.push("");
  } else {
    // Group by briefId.
    const byBrief = new Map<string, typeof strategy.staticBriefs>();
    for (const s of strategy.staticBriefs) {
      const list = byBrief.get(s.briefId) ?? [];
      list.push(s);
      byBrief.set(s.briefId, list);
    }
    for (const [briefId, statics] of byBrief) {
      const matched = strategy.creatorBriefs.find((b) => b.id === briefId);
      const ref = matched ? matched.forAngle : briefId;
      lines.push(`### ${briefId} — ${ref}`);
      lines.push("");
      for (const s of statics) {
        lines.push(`#### ${s.size}`);
        lines.push("");
        lines.push(`| Field | Value |`);
        lines.push(`|-------|-------|`);
        lines.push(`| Headline overlay | ${s.headlineOverlay.replace(/\|/g, "/")} |`);
        if (s.subOverlay) {
          lines.push(`| Sub overlay | ${s.subOverlay.replace(/\|/g, "/")} |`);
        }
        lines.push(`| Hero element | ${s.heroElement.replace(/\|/g, "/")} |`);
        lines.push(`| Proof element | ${s.proofElement.replace(/\|/g, "/")} |`);
        lines.push(`| CTA badge | ${s.ctaBadge.replace(/\|/g, "/")} |`);
        lines.push(`| Reading order | ${s.visualHierarchy.replace(/\|/g, "/")} |`);
        lines.push("");
      }
    }
  }

  // Ad Variants
  section(lines, "Ad Variants");
  if (strategy.variantSets.length === 0) {
    lines.push("_No variant sets generated for this input._");
    lines.push("");
  } else {
    strategy.variantSets.forEach((vset) => {
      lines.push(`### Base concept ${vset.baseConceptId}`);
      lines.push("");
      vset.variants.forEach((v, i) => {
        lines.push(
          `${i + 1}. **Axis changed: ${variantAxisLabel(v.changedAxis)}** — ${v.rationale}`
        );
        lines.push(`   - Hook: ${v.hook}`);
        lines.push(`   - Hold: ${v.hold}`);
        lines.push(`   - Proof: ${v.proof}`);
        lines.push(`   - CTA: ${v.cta}`);
        lines.push(`   - Offer: ${v.offer}`);
      });
      lines.push("");
    });
  }

  // Generic-copy flags (if any)
  if (strategy.genericFlags.length > 0) {
    section(lines, "Generic-copy flags");
    for (const f of strategy.genericFlags) {
      lines.push(
        `- **${f.field}** — banned phrase: "${f.phrase}". Suggestion: ${f.suggestion}`
      );
    }
    lines.push("");
  }

  // Input Assistant — quality assessment of the raw inputs.
  section(lines, "Input Assistant");
  const iq = strategy.inputQuality;
  lines.push(
    `Score: **${iq.score}/100** — status: **${inputQualityStatusLabel(iq.status)}**. Warnings: ${iq.warnings.length}. Suggestions: ${iq.suggestions.length}.`
  );
  lines.push("");
  if (iq.warnings.length > 0) {
    lines.push(`| Kind | Field | Severity | Message | Fix |`);
    lines.push(`|------|-------|----------|---------|-----|`);
    for (const w of iq.warnings) {
      lines.push(
        `| ${w.kind} | ${w.field} | ${w.severity} | ${oneLine(w.message)} | ${oneLine(w.fix)} |`
      );
    }
    lines.push("");
  } else {
    lines.push("_No input warnings._");
    lines.push("");
  }
  if (iq.suggestions.length > 0) {
    lines.push(`**Suggestions:**`);
    lines.push("");
    lines.push(`| Field | Suggestion | Rationale |`);
    lines.push(`|-------|------------|-----------|`);
    for (const s of iq.suggestions) {
      lines.push(
        `| ${s.field} | ${oneLine(s.suggestion)} | ${oneLine(s.rationale)} |`
      );
    }
    lines.push("");
  }
  lines.push(`**Rewritten hints:**`);
  lines.push("");
  lines.push(`- **You wrote audience:** ${input.audience || "—"}`);
  lines.push(`- **BigAd suggests:** ${iq.rewrittenHints.audience || "—"}`);
  lines.push(`- **You wrote core pain:** ${input.audiencePain || "—"}`);
  lines.push(`- **BigAd suggests:** ${iq.rewrittenHints.corePain || "—"}`);
  lines.push(`- **You wrote differentiator:** ${input.differentiator || "—"}`);
  lines.push(`- **BigAd suggests:** ${iq.rewrittenHints.differentiator || "—"}`);
  lines.push(`- **You wrote goal:** ${input.goal || "—"}`);
  lines.push(`- **BigAd suggests:** ${iq.rewrittenHints.goal || "—"}`);
  lines.push(
    `- **Proof types this product needs:** ${iq.rewrittenHints.proofNeeded.join(", ") || "—"}`
  );
  lines.push("");

  // Proof Asset Plan.
  section(lines, "Proof Asset Plan");
  const pap = strategy.proofAssetPlan;
  lines.push(
    `Proof readiness: **${pap.proofReadinessScore}/100**. Minimum proof set: ${pap.minimumProofSet.length} must-have asset${pap.minimumProofSet.length === 1 ? "" : "s"}. Missing before spend: ${pap.missingBeforeSpend.length}.`
  );
  lines.push("");
  if (pap.missingBeforeSpend.length > 0) {
    lines.push(
      `**Missing before spend:** ${pap.missingBeforeSpend.join(", ")}.`
    );
    lines.push("");
  }
  if (pap.priorityAssets.length > 0) {
    lines.push(`| Priority | Type | Title | Why | Capture | Where | Objection | Impact |`);
    lines.push(`|----------|------|-------|-----|---------|-------|-----------|--------|`);
    for (const p of pap.priorityAssets) {
      lines.push(
        `| ${p.priority} | ${p.type} | ${oneLine(p.title)} | ${oneLine(p.whyItMatters)} | ${oneLine(p.captureInstructions)} | ${p.whereToUse.join("; ")} | ${oneLine(p.relatedObjection ?? "—")} | ${p.readinessImpact} |`
      );
    }
    lines.push("");
  } else {
    lines.push("_No proof assets planned._");
    lines.push("");
  }

  // Copy quality flags — emitted by the copy-normalize validator.
  // Always render the section header so tests can confirm coverage; the
  // body says "clean" when there are no issues.
  section(lines, "Copy Quality Flags");
  if (strategy.copyIssues.length === 0) {
    lines.push("_No copy-quality issues detected._");
    lines.push("");
  } else {
    for (const i of strategy.copyIssues) {
      lines.push(
        `- **${i.kind}** at \`${i.source}\` — ${oneLine(i.text)}`
      );
    }
    lines.push("");
  }

  // Campaign Log — only rendered when the caller supplies workspace
  // context (runs / results / learning memory). Without it, the brief
  // is byte-identical to the no-workspace build.
  if (workspace) {
    const runs = (workspace.runs ?? []).slice();
    const results = (workspace.results ?? []).slice();
    const mem = workspace.learningMemory;
    const hasAny =
      runs.length > 0 || results.length > 0 || (mem && mem.learnings.length > 0);
    if (hasAny) {
      section(lines, "Campaign Log");

      if (runs.length > 0) {
        lines.push("**Recent runs.**");
        lines.push("");
        // Sort by runAt desc (most recent first), then take the last 5.
        const sortedRuns = runs.sort((a, b) =>
          a.runAt < b.runAt ? 1 : a.runAt > b.runAt ? -1 : 0
        );
        for (const r of sortedRuns.slice(0, 5)) {
          const offerLead = r.strategy.offers[0]?.kind ?? "—";
          const windowsCount = r.strategy.campaignCalendar.windows.length;
          const topAngle = r.strategy.rankedAngles[0]?.name ?? "—";
          lines.push(
            `- \`${r.id}\` at ${r.runAt} — product: ${r.input.name || "—"}; top offer: ${offerLead}; windows: ${windowsCount}; top angle: ${topAngle}.`
          );
        }
        lines.push("");
      }

      if (results.length > 0) {
        lines.push("**Recent test results.**");
        lines.push("");
        // Sort by updatedAt desc, take last 10.
        const sortedResults = results.sort((a, b) =>
          a.updatedAt < b.updatedAt ? 1 : a.updatedAt > b.updatedAt ? -1 : 0
        );
        for (const result of sortedResults.slice(0, 10)) {
          const metrics = result.metrics
            .map((m) => `${m.kpi}=${m.value}`)
            .join(", ");
          const noteSuffix = result.notes ? ` — ${oneLine(result.notes)}` : "";
          lines.push(
            `- \`${result.testCellId}\` (run \`${result.runId}\`) — status: **${result.status}**, spend: ${result.spend}, days: ${result.daysRun}${
              metrics ? `, ${metrics}` : ""
            }${noteSuffix}.`
          );
        }
        lines.push("");
      }

      if (mem && mem.learnings.length > 0) {
        lines.push("**Current learnings.**");
        lines.push("");
        // Group by signal for readability.
        const bySignal = new Map<string, typeof mem.learnings>();
        for (const learning of mem.learnings) {
          const arr = bySignal.get(learning.signal) ?? [];
          arr.push(learning);
          bySignal.set(learning.signal, arr);
        }
        for (const [signal, ls] of bySignal) {
          lines.push(`- **${signal}**`);
          for (const l of ls) {
            lines.push(
              `  - ${l.subject} — confidence ${l.confidence}; ${l.supportingResultIds.length} supporting result${
                l.supportingResultIds.length === 1 ? "" : "s"
              }.`
            );
          }
        }
        lines.push("");
      }
    }
  }

  // Approval Pack — Review & Approval Layer summary. Emitted only
  // when the caller supplies a non-empty `reviewBoard`. Absent or
  // empty → existing brief is byte-identical (and existing tests
  // stay green).
  const reviewBoard = workspace?.reviewBoard;
  if (reviewBoard && reviewBoard.items.length > 0) {
    appendApprovalPack(lines, reviewBoard);
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n");
}

function appendApprovalPack(
  lines: string[],
  board: {
    items: ReviewItem[];
    comments: ReviewComment[];
    summary: ReviewBoardSummary;
  }
): void {
  section(lines, "Approval Pack");
  const s = board.summary;
  lines.push(
    `**Approval score:** ${s.approvalScore} / 100 — ${s.approvalReadiness}`
  );
  lines.push(
    `**Critical approvals:** ${s.criticalApproved} / ${s.criticalTotal}`
  );
  lines.push(`**Unresolved comments:** ${s.unresolvedComments}`);
  lines.push("");

  const byKind = new Map<string, ReviewItem>();
  for (const it of board.items) {
    byKind.set(it.kind, it);
  }
  const unresolvedCountByItem: Record<string, number> = {};
  for (const it of board.items) unresolvedCountByItem[it.id] = 0;
  for (const c of board.comments) {
    if (c.resolved) continue;
    if (unresolvedCountByItem[c.itemId] === undefined) continue;
    unresolvedCountByItem[c.itemId] += 1;
  }

  function emitItemLine(it: ReviewItem): string {
    const label = reviewItemKindLabel(it.kind);
    const unresolved = unresolvedCountByItem[it.id] ?? 0;
    const unresolvedSuffix =
      unresolved > 0
        ? ` (${unresolved} unresolved comment${unresolved === 1 ? "" : "s"})`
        : "";
    if (it.status === "approved") {
      const who = it.approvedBy ? ` by ${it.approvedBy}` : "";
      const when = it.approvedAt
        ? ` (${new Date(it.approvedAt).toISOString().slice(0, 10)})`
        : "";
      return `- [approved] ${label} — approved${who}${when}${unresolvedSuffix}`;
    }
    if (it.status === "needs-changes") {
      return `- [needs-changes] ${label} — needs-changes${unresolvedSuffix}`;
    }
    if (it.status === "blocked") {
      return `- [blocked] ${label} — blocked${unresolvedSuffix}`;
    }
    return `- [pending] ${label} — pending${unresolvedSuffix}`;
  }

  lines.push(`### Critical items`);
  for (const kind of CRITICAL_REVIEW_ITEM_KINDS) {
    const it = byKind.get(kind);
    if (!it) continue;
    lines.push(emitItemLine(it));
  }
  lines.push("");

  lines.push(`### Non-critical items`);
  for (const kind of NON_CRITICAL_REVIEW_ITEM_KINDS) {
    const it = byKind.get(kind);
    if (!it) continue;
    lines.push(emitItemLine(it));
  }
  lines.push("");

  const openComments = board.comments
    .filter((c) => !c.resolved)
    .slice()
    .sort((a, b) => (a.createdAt < b.createdAt ? -1 : 1));
  if (openComments.length > 0) {
    lines.push(`### Open comments`);
    for (const c of openComments) {
      const owningItem = board.items.find((it) => it.id === c.itemId);
      const kindLabel = owningItem
        ? reviewItemKindLabel(owningItem.kind)
        : c.itemId;
      const when =
        typeof c.createdAt === "number" && c.createdAt > 0
          ? ` — ${new Date(c.createdAt).toISOString().slice(0, 10)}`
          : "";
      lines.push(
        `- [${c.author} / ${kindLabel}] "${oneLine(c.body)}"${when}`
      );
    }
    lines.push("");
  }
}

function oneLine(s: string): string {
  return (s ?? "").replace(/\s+/g, " ").trim();
}

function section(lines: string[], title: string) {
  lines.push(`## ${title}`);
  lines.push("");
}

function stageLabel(stage: string): string {
  return {
    "unaware": "Unaware",
    "problem-aware": "Problem-aware",
    "solution-aware": "Solution-aware",
    "product-aware": "Product-aware",
    "most-aware": "Most-aware",
  }[stage] ?? stage;
}

function offerKindLabel(kind: string): string {
  return (
    {
      discount: "Discount",
      bundle: "Bundle",
      guarantee: "Guarantee",
      "free-shipping": "Free shipping",
      "free-gift": "Free gift",
      "payment-plan": "Payment plan",
      "free-trial": "Free trial",
    }[kind] ?? kind
  );
}

function campaignTypeLabel(type: string): string {
  return (
    {
      launch: "Launch",
      seasonal: "Seasonal",
      "always-on": "Always-on",
    }[type] ?? type
  );
}

function formatRange(startOffset: number, duration: number): string {
  const start = startOffset === 0 ? "Day 0" : startOffset > 0 ? `Day +${startOffset}` : `Day ${startOffset}`;
  return `${start} for ${duration} ${duration === 1 ? "day" : "days"}`;
}

function briefSectionLabel(kind: string): string {
  return (
    {
      hook: "Hook",
      problem: "Problem",
      "solution-or-proof": "Solution / proof",
      cta: "CTA",
    }[kind] ?? kind
  );
}

function shotKindLabel(kind: string): string {
  return (
    {
      "talking-head": "Talking head",
      "product-shot": "Product shot",
      "b-roll": "B-roll",
      screenshot: "Screenshot",
      "ugc-selfie": "UGC selfie",
      lifestyle: "Lifestyle",
    }[kind] ?? kind
  );
}

function cameraAngleLabel(angle: string): string {
  return (
    {
      "eye-level": "Eye-level",
      high: "High",
      low: "Low",
      "over-shoulder": "Over-shoulder",
      pov: "POV",
    }[angle] ?? angle
  );
}

function briefSectionIndexLabel(i: number): string {
  return (
    [
      "Hook",
      "Problem",
      "Solution / proof",
      "CTA",
    ][i] ?? `Section ${i + 1}`
  );
}

function scriptLineKindLabel(kind: string): string {
  return (
    {
      vo: "VO",
      "on-camera": "On-camera",
      "on-screen-text": "On-screen text",
      sfx: "SFX",
    }[kind] ?? kind
  );
}

function variantAxisLabel(axis: string): string {
  return (
    {
      hook: "Hook",
      hold: "Hold",
      proof: "Proof",
      cta: "CTA",
      offer: "Offer",
    }[axis] ?? axis
  );
}

function trackingStatusLabel(status: string): string {
  return (
    {
      ready: "Ready",
      almost: "Almost ready",
      "not-ready": "Not ready",
    }[status] ?? status
  );
}

function readinessStatusLabel(status: string): string {
  return (
    {
      passed: "Passed",
      warning: "Warning",
      blocker: "Blocker",
      unknown: "Unknown",
    }[status] ?? status
  );
}

function kpiNameLabel(name: string): string {
  return (
    {
      ctr: "CTR",
      cpc: "CPC",
      cpm: "CPM",
      cpa: "CPA",
      cvr: "CVR",
      roas: "ROAS",
      hookRate: "Hook rate",
      holdRate: "Hold rate",
    }[name] ?? name
  );
}

function ladderTierLabel(tier: string): string {
  return (
    {
      starter: "Starter",
      healthy: "Healthy",
      scaling: "Scaling",
    }[tier] ?? tier
  );
}

function diagnosisCategoryLabel(cat: string): string {
  return (
    {
      creative: "Creative",
      "landing-page": "Landing page",
      offer: "Offer",
      audience: "Audience",
      tracking: "Tracking",
      fatigue: "Fatigue",
      healthy: "Healthy",
    }[cat] ?? cat
  );
}

function journeyStageLabel(stage: string): string {
  return (
    {
      "strategy-drafted": "Strategy drafted",
      "creative-planned": "Creative planned",
      "tracking-ready": "Tracking ready",
      "kpi-aligned": "KPI aligned",
      "review-passed": "Review passed",
      "ready-to-spend": "Ready to spend",
    }[stage] ?? stage
  );
}

function fmtMetric(n: number | undefined): string {
  if (typeof n !== "number" || !Number.isFinite(n)) return "—";
  return String(n);
}

function appliedVerdictLabel(verdict: string): string {
  return (
    {
      ready: "Ready",
      almost: "Almost",
      "not-ready": "Not ready",
    }[verdict] ?? verdict
  );
}

function appliedFindingVerdictLabel(verdict: string): string {
  return (
    {
      passed: "Passed",
      partial: "Partial",
      missing: "Missing",
      unknown: "Unknown",
    }[verdict] ?? verdict
  );
}

function ctaSurfaceLabel(surface: string): string {
  return (
    {
      "meta-feed": "Meta feed",
      "meta-reels": "Meta reels",
      tiktok: "TikTok",
      "landing-primary": "Landing primary",
      email: "Email",
    }[surface] ?? surface
  );
}

function ctaStyleLabel(style: string): string {
  return (
    {
      direct: "Direct",
      curious: "Curious",
      "time-boxed": "Time-boxed",
      "proof-led": "Proof-led",
      "low-pressure": "Low-pressure",
    }[style] ?? style
  );
}

function dipMechanismLabel(m: string): string {
  return (
    {
      "warm-cohort-saturation": "Warm-cohort saturation",
      "warm-cohort-exhaustion": "Warm-cohort exhaustion",
      "urgency-collapse": "Urgency collapse",
      "post-peak-reset": "Post-peak reset",
    }[m] ?? m
  );
}

function audienceIntentLabel(intent: string): string {
  return (
    {
      prospecting: "Prospecting",
      "engagement-retargeting": "Engagement retargeting",
      "site-retargeting": "Site retargeting",
    }[intent] ?? intent
  );
}

function hookPatternLabel(p: string): string {
  return (
    {
      "pain-first": "Pain-first",
      "outcome-first": "Outcome-first",
      contrarian: "Contrarian",
      "proof-led": "Proof-led",
      curiosity: "Curiosity",
      comparison: "Comparison",
      mistake: "Mistake",
      "before-after": "Before-after",
    }[p] ?? p
  );
}

function inputQualityStatusLabel(status: string): string {
  return (
    {
      weak: "Weak",
      okay: "Okay",
      strong: "Strong",
    }[status] ?? status
  );
}

function reviewAxisLabel(axis: string): string {
  return (
    {
      "hook-clarity": "Hook clarity",
      "first-3s-payoff": "First-3s payoff",
      "claim-specificity": "Claim specificity",
      "proof-strength": "Proof strength",
      "offer-visibility": "Offer visibility",
      "cta-clarity": "CTA clarity",
      "platform-fit": "Platform fit",
      "tone-match": "Tone match",
      "awareness-fit": "Awareness fit",
      pacing: "Pacing",
      "visual-hierarchy": "Visual hierarchy",
      "captions-overlay": "Captions / overlay",
      "audio-quality": "Audio quality",
      "brand-presence": "Brand presence",
      "tracking-readiness-ref": "Tracking readiness ref",
    }[axis] ?? axis
  );
}
