import type { ProductInput, Strategy } from "@/types/strategy";
import { awarenessLabel } from "./awareness";
import { sophisticationLabel } from "./sophistication";
import { windowKindLabel } from "./calendar";

// generateExportBrief — assembles a clean, single-page markdown brief
// covering every section of the strategy. Designed to be pasted into
// Notion, Google Docs, or a team message and still read cleanly. No
// emojis, no decorative characters.

export function generateExportBrief(
  input: ProductInput,
  strategy: Strategy
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${input.name || "Untitled product"} — strategy brief`);
  lines.push("");
  lines.push(
    `Generated by BigAd. All copy is a starting draft to be edited, not finished marketing.`
  );
  lines.push("");

  // 1. Product snapshot
  section(lines, "Product snapshot");
  lines.push(`- **Name:** ${input.name || "—"}`);
  lines.push(`- **Category:** ${input.category || "—"}`);
  lines.push(`- **Description:** ${input.description || "—"}`);
  lines.push(`- **Price:** ${input.price || "—"}`);
  lines.push(`- **Business model:** ${input.businessModel}`);
  lines.push(`- **Audience:** ${input.audience || "—"}`);
  lines.push(`- **Core pain:** ${input.audiencePain || "—"}`);
  lines.push(`- **Competitors:** ${input.competitors || "—"}`);
  lines.push(`- **Differentiator:** ${input.differentiator || "—"}`);
  lines.push(`- **Goal:** ${input.goal || "—"}`);
  lines.push(`- **Awareness:** ${awarenessLabel(input.awareness)}`);
  lines.push(`- **Sophistication:** ${sophisticationLabel(input.sophistication)}`);
  if (input.campaignType) {
    lines.push(`- **Campaign type:** ${campaignTypeLabel(input.campaignType)}`);
  }
  const ctx = input.offerContext;
  if (ctx) {
    if (typeof ctx.cogsPercent === "number") {
      lines.push(`- **COGS %:** ${ctx.cogsPercent}`);
    }
    if (typeof ctx.targetMarginPercent === "number") {
      lines.push(`- **Target margin %:** ${ctx.targetMarginPercent}`);
    }
    if (typeof ctx.currentAOV === "number") {
      lines.push(`- **Current AOV:** ${ctx.currentAOV}`);
    }
    if (typeof ctx.targetROAS === "number") {
      lines.push(`- **Target ROAS:** ${ctx.targetROAS}x`);
    }
  }
  lines.push("");

  // 2. Quality score
  section(lines, "Strategy quality score");
  lines.push(`**Overall:** ${strategy.score.overall}/100`);
  lines.push("");
  for (const d of strategy.score.dimensions) {
    lines.push(`- **${d.label} — ${d.score}/100.** ${d.explanation}`);
    lines.push(`  - Suggestion: ${d.suggestion}`);
  }
  lines.push("");

  // 3. Positioning
  section(lines, "Positioning");
  lines.push(strategy.positioning.statement);
  lines.push("");
  lines.push(`- **For whom:** ${strategy.positioning.forWhom}`);
  lines.push(`- **Category:** ${strategy.positioning.category}`);
  lines.push(`- **Unlike:** ${strategy.positioning.unlike}`);
  lines.push(`- **Unique:** ${strategy.positioning.unique}`);
  lines.push("");
  lines.push(`**Central promise.** ${strategy.centralPromise}`);
  lines.push("");
  lines.push(`**Unique mechanism.** ${strategy.uniqueMechanism}`);
  lines.push("");

  // 4. Awareness diagnosis
  section(lines, "Awareness diagnosis");
  lines.push(`Current stage: **${awarenessLabel(input.awareness)}**.`);
  lines.push("");
  for (const n of strategy.awarenessNotes) lines.push(`- ${n}`);
  lines.push("");
  lines.push(`Sophistication: **${sophisticationLabel(input.sophistication)}**.`);
  lines.push("");
  for (const n of strategy.sophisticationNotes) lines.push(`- ${n}`);
  lines.push("");

  // 5. Offer diagnosis
  section(lines, "Offer diagnosis");
  lines.push(`- **Strongest promise:** ${strategy.diagnosis.strongestPromise}`);
  lines.push(`- **Weakest claim:** ${strategy.diagnosis.weakestClaim}`);
  lines.push(`- **Missing proof:** ${strategy.diagnosis.missingProof}`);
  lines.push(`- **Biggest objection:** ${strategy.diagnosis.biggestObjection}`);
  lines.push(
    `- **Recommended proof asset:** ${strategy.diagnosis.recommendedAsset} — ${strategy.diagnosis.recommendedAssetReason}`
  );
  lines.push("");

  // 5b. Offer architecture
  section(lines, "Offer Architecture");
  strategy.offers.forEach((o, i) => {
    const roas =
      typeof o.breakevenROAS === "number"
        ? `${o.breakevenROAS.toFixed(2)}x breakeven ROAS`
        : "breakeven ROAS not computed";
    lines.push(
      `${i + 1}. **${offerKindLabel(o.kind)} — ${o.label}.** ${roas}; stickiness risk: ${o.stickinessRisk}; awareness fit: ${o.awarenessFit.join(", ") || "—"}.`
    );
    lines.push(`   - Why: ${o.rationale}`);
    if (typeof o.discountPercent === "number") {
      lines.push(`   - Assumed discount: ${o.discountPercent}%`);
    }
    if (o.notes) {
      lines.push(`   - Note: ${o.notes}`);
    }
  });
  lines.push("");

  // 5c. Campaign calendar
  section(lines, "Campaign Calendar");
  lines.push(
    `Campaign type: **${campaignTypeLabel(strategy.campaignCalendar.campaignType)}** — anchor: ${strategy.campaignCalendar.anchorLabel}.`
  );
  lines.push("");
  strategy.campaignCalendar.windows.forEach((w, i) => {
    const range = formatRange(w.startOffsetDays, w.durationDays);
    const dipFlag = w.expectedDip ? "  (forecast dip)" : "";
    const offer = w.recommendedOfferKind ? offerKindLabel(w.recommendedOfferKind) : "—";
    lines.push(
      `${i + 1}. **${windowKindLabel(w.kind)} — ${w.label}.** ${range}${dipFlag}`
    );
    lines.push(`   - KPI: ${w.primaryKPI}`);
    lines.push(`   - Readiness gate: ${w.readinessGate}`);
    lines.push(`   - Recommended offer: ${offer}`);
    lines.push(`   - Notes: ${w.notes}`);
  });
  lines.push("");

  // 5d. Creator briefs
  section(lines, "Creator Briefs");
  if (strategy.creatorBriefs.length === 0) {
    lines.push("_No briefs generated for this input._");
    lines.push("");
  } else {
    strategy.creatorBriefs.forEach((brief) => {
      lines.push(`### ${brief.forAngle}`);
      lines.push("");
      lines.push(`- **Brief ID:** ${brief.id}`);
      lines.push(`- **Total duration:** ~${brief.durationSeconds}s`);
      lines.push(`- **Framing:** ${brief.framing}`);
      if (brief.notes) {
        lines.push(`- **Note:** ${brief.notes}`);
      }
      lines.push("");
      lines.push(`**Alt hooks:**`);
      for (const h of brief.altHooks) lines.push(`- ${h}`);
      lines.push("");
      lines.push(`**Sections:**`);
      for (const s of brief.sections) {
        lines.push(
          `- **${briefSectionLabel(s.kind)} — ${s.label}** (~${s.durationSeconds}s). ${s.beat}`
        );
        if (s.whatToSay && s.whatToSay.length > 0) {
          for (const line of s.whatToSay) lines.push(`  - Say: ${line}`);
        }
        if (s.whatToShow && s.whatToShow.length > 0) {
          for (const line of s.whatToShow) lines.push(`  - Show: ${line}`);
        }
        if (s.doNot && s.doNot.length > 0) {
          for (const line of s.doNot) lines.push(`  - Do not: ${line}`);
        }
      }
      lines.push("");
      lines.push(`**Deliverables:**`);
      for (const d of brief.deliverables) lines.push(`- ${d}`);
      lines.push("");
    });
  }

  // 5e. Shot lists
  section(lines, "Shot Lists");
  if (strategy.shotLists.length === 0) {
    lines.push("_No shot lists generated for this input._");
    lines.push("");
  } else {
    strategy.shotLists.forEach((list) => {
      const matched = strategy.creatorBriefs.find((b) => b.id === list.briefId);
      const angleRef = matched ? matched.forAngle : list.briefId;
      lines.push(`### ${list.briefId} — ${angleRef}`);
      lines.push("");
      lines.push(`Total shots: ${list.totalShots}.`);
      lines.push("");
      lines.push(`| # | Kind | Framing | Angle | Duration | Sound | Props |`);
      lines.push(`|---|------|---------|-------|----------|-------|-------|`);
      for (const it of list.items) {
        const propsCell = it.props.join("; ");
        const sound = it.sound.replace(/\|/g, "/");
        const framing = it.framing.replace(/\|/g, "/");
        lines.push(
          `| ${it.index} | ${shotKindLabel(it.kind)} | ${framing} | ${cameraAngleLabel(it.angle)} | ${it.duration} | ${sound} | ${propsCell} |`
        );
      }
      lines.push("");
    });
  }

  // 5f. Video scripts
  section(lines, "Video Scripts");
  if (strategy.videoScripts.length === 0) {
    lines.push("_No video scripts generated for this input._");
    lines.push("");
  } else {
    strategy.videoScripts.forEach((script) => {
      const matched = strategy.creatorBriefs.find((b) => b.id === script.briefId);
      const ref = matched ? matched.forAngle : script.briefId;
      lines.push(`### ${script.briefId} — ${ref}`);
      lines.push("");
      lines.push(`Total duration: ~${script.totalDurationSeconds}s.`);
      lines.push("");
      lines.push(`| # | Section | Kind | Start | Duration | Text |`);
      lines.push(`|---|---------|------|-------|----------|------|`);
      for (const ln of script.lines) {
        const text = ln.text.replace(/\|/g, "/");
        lines.push(
          `| ${ln.index} | ${briefSectionIndexLabel(ln.briefSectionIndex)} | ${scriptLineKindLabel(ln.kind)} | ${ln.startSeconds}s | ${ln.durationSeconds}s | ${text} |`
        );
      }
      lines.push("");
    });
  }

  // 5g. Ad variants
  section(lines, "Ad Variants");
  if (strategy.variantSets.length === 0) {
    lines.push("_No variant sets generated for this input._");
    lines.push("");
  } else {
    strategy.variantSets.forEach((vset) => {
      lines.push(`### Base concept ${vset.baseConceptId}`);
      lines.push("");
      vset.variants.forEach((v, i) => {
        lines.push(
          `${i + 1}. **Axis changed: ${variantAxisLabel(v.changedAxis)}** — ${v.rationale}`
        );
        lines.push(`   - Hook: ${v.hook}`);
        lines.push(`   - Hold: ${v.hold}`);
        lines.push(`   - Proof: ${v.proof}`);
        lines.push(`   - CTA: ${v.cta}`);
        lines.push(`   - Offer: ${v.offer}`);
      });
      lines.push("");
    });
  }

  // 5h. Tracking Readiness
  section(lines, "Tracking Readiness");
  const tr = strategy.trackingReadiness;
  lines.push(
    `Score: **${tr.score}/100** — status: **${trackingStatusLabel(tr.status)}**. Blockers: ${tr.blockers}. Warnings: ${tr.warnings}.`
  );
  lines.push("");
  for (const c of tr.checks) {
    lines.push(`- **${c.label} — ${readinessStatusLabel(c.status)}.** ${c.rationale}`);
    if (c.fix) lines.push(`  - Fix: ${c.fix}`);
  }
  lines.push("");

  // 5i. KPI Target Ladder
  section(lines, "KPI Target Ladder");
  lines.push(`| KPI | Tier | Breakeven | Scaling | Direction |`);
  lines.push(`|-----|------|-----------|---------|-----------|`);
  for (const t of strategy.kpiLadder.targets) {
    lines.push(
      `| ${kpiNameLabel(t.kpi)} | ${ladderTierLabel(t.tier)} | ${t.breakeven} | ${t.scaling} | ${t.direction} |`
    );
  }
  lines.push("");

  // 5j. KPI Diagnosis
  section(lines, "KPI Diagnosis");
  lines.push(
    `Primary category: **${diagnosisCategoryLabel(strategy.kpiDiagnosis.primaryCategory)}**. Synthetic sample anchored near healthy-tier breakeven.`
  );
  lines.push("");
  const snap = strategy.kpiDiagnosis.snapshot;
  lines.push(
    `Snapshot: CTR ${fmtMetric(snap.ctr)}, CPC ${fmtMetric(snap.cpc)}, CPM ${fmtMetric(snap.cpm)}, CPA ${fmtMetric(snap.cpa)}, CVR ${fmtMetric(snap.cvr)}, ROAS ${fmtMetric(snap.roas)}, Hook-rate ${fmtMetric(snap.hookRate)}, Hold-rate ${fmtMetric(snap.holdRate)}.`
  );
  lines.push("");
  for (const f of strategy.kpiDiagnosis.findings) {
    lines.push(`- **${diagnosisCategoryLabel(f.category)} — ${f.signal}.** ${f.inference}`);
    lines.push(`  - Action: ${f.recommendedAction}`);
  }
  lines.push("");

  // 5k. Ad Review Checklist
  section(lines, "Ad Review Checklist");
  lines.push(`Total weight: ${strategy.adReview.totalWeight}.`);
  lines.push("");
  for (const a of strategy.adReview.axes) {
    lines.push(`- **${a.label} (weight ${a.weight}).** ${a.question}`);
  }
  lines.push("");

  // 5k-bis. Applied Ad Reviews — per-brief evaluation against the checklist.
  section(lines, "Applied Ad Reviews");
  if (strategy.appliedAdReviews.length === 0) {
    lines.push("_No briefs were evaluated against the checklist._");
    lines.push("");
  } else {
    for (const review of strategy.appliedAdReviews) {
      const matched = strategy.creatorBriefs.find(
        (b) => b.id === review.targetId
      );
      const ref = matched ? matched.forAngle : review.targetId;
      lines.push(`### ${review.targetId} — ${ref}`);
      lines.push("");
      lines.push(
        `Score: **${review.totalScore}/${review.maxScore} (${review.scorePercent}%)** — verdict: **${appliedVerdictLabel(review.verdict)}**.`
      );
      lines.push("");
      lines.push(`| Axis | Verdict | Score | Evidence | Fix |`);
      lines.push(`|------|---------|-------|----------|-----|`);
      for (const f of review.findings) {
        const evidence = f.evidence.replace(/\|/g, "/");
        const fix = (f.fix ?? "—").replace(/\|/g, "/");
        lines.push(
          `| ${reviewAxisLabel(f.axis)} | ${appliedFindingVerdictLabel(f.verdict)} | ${f.scoreContribution}/${f.weight} | ${evidence} | ${fix} |`
        );
      }
      lines.push("");
    }
  }

  // 5l. Journey Status
  section(lines, "Journey Status");
  const js = strategy.journeyStatus;
  lines.push(
    `Current stage: **${journeyStageLabel(js.currentStage)}** — ready to spend: ${js.readyToSpend ? "yes" : "no"}.`
  );
  lines.push("");
  lines.push(`**Next step.** ${js.nextStep}`);
  lines.push("");
  if (js.blockers.length > 0) {
    lines.push(`**Blockers:**`);
    for (const b of js.blockers) {
      const src = b.sourceCheck ? ` (source: ${b.sourceCheck})` : "";
      lines.push(`- [${b.kind}] ${b.message}${src}`);
    }
    lines.push("");
  }
  if (js.warnings.length > 0) {
    lines.push(`**Warnings:**`);
    for (const w of js.warnings) {
      const src = w.sourceCheck ? ` (source: ${w.sourceCheck})` : "";
      lines.push(`- [${w.kind}] ${w.message}${src}`);
    }
    lines.push("");
  }

  // 6. Top angles (ranked)
  section(lines, "Top angles (ranked by fit)");
  strategy.rankedAngles.forEach((a, i) => {
    lines.push(
      `${i + 1}. **${a.name}** — score ${a.score ?? 0}/100, best channel: ${a.channelFit ?? "—"}, stage: ${a.awarenessStage ?? "—"}.`
    );
    lines.push(`   - Hook: ${a.hook}`);
    if (a.objectionAddressed)
      lines.push(`   - Objection addressed: ${a.objectionAddressed}`);
    if (a.whyItCouldWork)
      lines.push(`   - Why it could work: ${a.whyItCouldWork}`);
  });
  lines.push("");

  // 7. Headlines
  section(lines, "Headlines");
  strategy.headlines.forEach((h, i) => lines.push(`${i + 1}. ${h}`));
  lines.push("");

  // 8. Copy variants by awareness stage
  section(lines, "Copy variants by awareness stage");
  for (const v of strategy.awarenessVariants) {
    lines.push(`### ${stageLabel(v.stage)}`);
    lines.push(`- **Headline:** ${v.headline}`);
    lines.push(`- **Ad hook:** ${v.adHook}`);
    lines.push(`- **Landing section angle:** ${v.landingAngle}`);
    lines.push("");
  }

  // 9. Landing copy
  section(lines, "Landing copy");
  lines.push(`**Hero.** ${strategy.landing.hero}`);
  lines.push("");
  lines.push(`**Sub-hero.** ${strategy.landing.subhead}`);
  lines.push("");
  lines.push(`**Value bullets:**`);
  for (const b of strategy.landing.bullets) lines.push(`- ${b}`);
  lines.push("");
  lines.push(`**CTA:** ${strategy.landing.cta}`);
  lines.push(`**Social proof line:** ${strategy.landing.socialProofLine}`);
  lines.push("");
  lines.push(`**Objection handlers (on-page):**`);
  for (const o of strategy.landing.objectionsHandled) {
    lines.push(`- ${o.objection}`);
    lines.push(`  ${o.reply}`);
  }
  lines.push("");

  // 10. App Store / Play Store
  section(lines, "Store copy");
  lines.push(`- **App name:** ${strategy.store.appName}`);
  lines.push(`- **Subtitle:** ${strategy.store.subtitle}`);
  lines.push(`- **Promotional text:** ${strategy.store.promoText}`);
  lines.push(`- **Keywords:** ${strategy.store.keywords.join(", ")}`);
  lines.push("");
  lines.push(`**Long description:**`);
  lines.push("");
  lines.push(strategy.store.description);
  lines.push("");

  // 11. Experiments
  section(lines, "Experiments");
  strategy.experiments.forEach((e, i) => {
    lines.push(`${i + 1}. **${e.hypothesis}**`);
    lines.push(`   - A: ${e.variantA}`);
    lines.push(`   - B: ${e.variantB}`);
    lines.push(`   - Metric: ${e.metric}`);
  });
  lines.push("");

  // 11b. CTA Bank
  section(lines, "CTA Bank");
  if (strategy.ctaBank.variants.length === 0) {
    lines.push("_No CTA variants generated._");
    lines.push("");
  } else {
    // Group by surface so the editor scans a clean table per placement.
    const ctaSurfaces = [
      "meta-feed",
      "meta-reels",
      "tiktok",
      "landing-primary",
      "email",
    ] as const;
    for (const surface of ctaSurfaces) {
      const inSurface = strategy.ctaBank.variants.filter(
        (v) => v.surface === surface
      );
      if (inSurface.length === 0) continue;
      lines.push(`### ${ctaSurfaceLabel(surface)}`);
      lines.push("");
      lines.push(`| Style | Text | Rationale |`);
      lines.push(`|-------|------|-----------|`);
      for (const v of inSurface) {
        lines.push(
          `| ${ctaStyleLabel(v.style)} | ${v.text.replace(/\|/g, "/")} | ${v.rationale.replace(/\|/g, "/")} |`
        );
      }
      lines.push("");
    }
  }

  // 11c. Static Briefs
  section(lines, "Static Briefs");
  if (strategy.staticBriefs.length === 0) {
    lines.push("_No static briefs generated._");
    lines.push("");
  } else {
    // Group by briefId.
    const byBrief = new Map<string, typeof strategy.staticBriefs>();
    for (const s of strategy.staticBriefs) {
      const list = byBrief.get(s.briefId) ?? [];
      list.push(s);
      byBrief.set(s.briefId, list);
    }
    for (const [briefId, statics] of byBrief) {
      const matched = strategy.creatorBriefs.find((b) => b.id === briefId);
      const ref = matched ? matched.forAngle : briefId;
      lines.push(`### ${briefId} — ${ref}`);
      lines.push("");
      for (const s of statics) {
        lines.push(`#### ${s.size}`);
        lines.push("");
        lines.push(`| Field | Value |`);
        lines.push(`|-------|-------|`);
        lines.push(`| Headline overlay | ${s.headlineOverlay.replace(/\|/g, "/")} |`);
        if (s.subOverlay) {
          lines.push(`| Sub overlay | ${s.subOverlay.replace(/\|/g, "/")} |`);
        }
        lines.push(`| Hero element | ${s.heroElement.replace(/\|/g, "/")} |`);
        lines.push(`| Proof element | ${s.proofElement.replace(/\|/g, "/")} |`);
        lines.push(`| CTA badge | ${s.ctaBadge.replace(/\|/g, "/")} |`);
        lines.push(`| Reading order | ${s.visualHierarchy.replace(/\|/g, "/")} |`);
        lines.push("");
      }
    }
  }

  // 11d. Creative QA
  section(lines, "Creative QA");
  if (strategy.creativeQa.length === 0) {
    lines.push("_No QA report generated._");
    lines.push("");
  } else {
    for (const cq of strategy.creativeQa) {
      const matched =
        cq.scope === "all"
          ? null
          : strategy.creatorBriefs.find((b) => b.id === cq.scope);
      const heading =
        cq.scope === "all"
          ? "Aggregate"
          : matched
          ? `${cq.scope} — ${matched.forAngle}`
          : cq.scope;
      lines.push(`### ${heading}`);
      lines.push("");
      lines.push(
        `Blockers: ${cq.blockerCount}. Warnings: ${cq.warningCount}.`
      );
      lines.push("");
      lines.push(`| Rule | Severity | Message | Suggestion |`);
      lines.push(`|------|----------|---------|------------|`);
      for (const f of cq.findings) {
        lines.push(
          `| ${f.rule} | ${f.severity} | ${f.message.replace(/\|/g, "/")} | ${(f.suggestion || "—").replace(/\|/g, "/")} |`
        );
      }
      lines.push("");
    }
  }

  // 11e. Editor Handoff
  section(lines, "Editor Handoff");
  if (strategy.editorHandoffs.length === 0) {
    lines.push("_No editor handoffs generated._");
    lines.push("");
  } else {
    for (const h of strategy.editorHandoffs) {
      lines.push(h.markdown);
      lines.push("");
    }
  }

  // 12. Generic-copy flags (if any)
  if (strategy.genericFlags.length > 0) {
    section(lines, "Generic-copy flags");
    for (const f of strategy.genericFlags) {
      lines.push(
        `- **${f.field}** — banned phrase: "${f.phrase}". Suggestion: ${f.suggestion}`
      );
    }
    lines.push("");
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n");
}

function section(lines: string[], title: string) {
  lines.push(`## ${title}`);
  lines.push("");
}

function stageLabel(stage: string): string {
  return {
    "unaware": "Unaware",
    "problem-aware": "Problem-aware",
    "solution-aware": "Solution-aware",
    "product-aware": "Product-aware",
    "most-aware": "Most-aware",
  }[stage] ?? stage;
}

function offerKindLabel(kind: string): string {
  return (
    {
      discount: "Discount",
      bundle: "Bundle",
      guarantee: "Guarantee",
      "free-shipping": "Free shipping",
      "free-gift": "Free gift",
      "payment-plan": "Payment plan",
      "free-trial": "Free trial",
    }[kind] ?? kind
  );
}

function campaignTypeLabel(type: string): string {
  return (
    {
      launch: "Launch",
      seasonal: "Seasonal",
      "always-on": "Always-on",
    }[type] ?? type
  );
}

function formatRange(startOffset: number, duration: number): string {
  const start = startOffset === 0 ? "Day 0" : startOffset > 0 ? `Day +${startOffset}` : `Day ${startOffset}`;
  return `${start} for ${duration} ${duration === 1 ? "day" : "days"}`;
}

function briefSectionLabel(kind: string): string {
  return (
    {
      hook: "Hook",
      problem: "Problem",
      "solution-or-proof": "Solution / proof",
      cta: "CTA",
    }[kind] ?? kind
  );
}

function shotKindLabel(kind: string): string {
  return (
    {
      "talking-head": "Talking head",
      "product-shot": "Product shot",
      "b-roll": "B-roll",
      screenshot: "Screenshot",
      "ugc-selfie": "UGC selfie",
      lifestyle: "Lifestyle",
    }[kind] ?? kind
  );
}

function cameraAngleLabel(angle: string): string {
  return (
    {
      "eye-level": "Eye-level",
      high: "High",
      low: "Low",
      "over-shoulder": "Over-shoulder",
      pov: "POV",
    }[angle] ?? angle
  );
}

function briefSectionIndexLabel(i: number): string {
  return (
    [
      "Hook",
      "Problem",
      "Solution / proof",
      "CTA",
    ][i] ?? `Section ${i + 1}`
  );
}

function scriptLineKindLabel(kind: string): string {
  return (
    {
      vo: "VO",
      "on-camera": "On-camera",
      "on-screen-text": "On-screen text",
      sfx: "SFX",
    }[kind] ?? kind
  );
}

function variantAxisLabel(axis: string): string {
  return (
    {
      hook: "Hook",
      hold: "Hold",
      proof: "Proof",
      cta: "CTA",
      offer: "Offer",
    }[axis] ?? axis
  );
}

function trackingStatusLabel(status: string): string {
  return (
    {
      ready: "Ready",
      almost: "Almost ready",
      "not-ready": "Not ready",
    }[status] ?? status
  );
}

function readinessStatusLabel(status: string): string {
  return (
    {
      passed: "Passed",
      warning: "Warning",
      blocker: "Blocker",
      unknown: "Unknown",
    }[status] ?? status
  );
}

function kpiNameLabel(name: string): string {
  return (
    {
      ctr: "CTR",
      cpc: "CPC",
      cpm: "CPM",
      cpa: "CPA",
      cvr: "CVR",
      roas: "ROAS",
      hookRate: "Hook rate",
      holdRate: "Hold rate",
    }[name] ?? name
  );
}

function ladderTierLabel(tier: string): string {
  return (
    {
      starter: "Starter",
      healthy: "Healthy",
      scaling: "Scaling",
    }[tier] ?? tier
  );
}

function diagnosisCategoryLabel(cat: string): string {
  return (
    {
      creative: "Creative",
      "landing-page": "Landing page",
      offer: "Offer",
      audience: "Audience",
      tracking: "Tracking",
      fatigue: "Fatigue",
      healthy: "Healthy",
    }[cat] ?? cat
  );
}

function journeyStageLabel(stage: string): string {
  return (
    {
      "strategy-drafted": "Strategy drafted",
      "creative-planned": "Creative planned",
      "tracking-ready": "Tracking ready",
      "kpi-aligned": "KPI aligned",
      "review-passed": "Review passed",
      "ready-to-spend": "Ready to spend",
    }[stage] ?? stage
  );
}

function fmtMetric(n: number | undefined): string {
  if (typeof n !== "number" || !Number.isFinite(n)) return "—";
  return String(n);
}

function appliedVerdictLabel(verdict: string): string {
  return (
    {
      ready: "Ready",
      almost: "Almost",
      "not-ready": "Not ready",
    }[verdict] ?? verdict
  );
}

function appliedFindingVerdictLabel(verdict: string): string {
  return (
    {
      passed: "Passed",
      partial: "Partial",
      missing: "Missing",
      unknown: "Unknown",
    }[verdict] ?? verdict
  );
}

function ctaSurfaceLabel(surface: string): string {
  return (
    {
      "meta-feed": "Meta feed",
      "meta-reels": "Meta reels",
      tiktok: "TikTok",
      "landing-primary": "Landing primary",
      email: "Email",
    }[surface] ?? surface
  );
}

function ctaStyleLabel(style: string): string {
  return (
    {
      direct: "Direct",
      curious: "Curious",
      "time-boxed": "Time-boxed",
      "proof-led": "Proof-led",
      "low-pressure": "Low-pressure",
    }[style] ?? style
  );
}

function reviewAxisLabel(axis: string): string {
  return (
    {
      "hook-clarity": "Hook clarity",
      "first-3s-payoff": "First-3s payoff",
      "claim-specificity": "Claim specificity",
      "proof-strength": "Proof strength",
      "offer-visibility": "Offer visibility",
      "cta-clarity": "CTA clarity",
      "platform-fit": "Platform fit",
      "tone-match": "Tone match",
      "awareness-fit": "Awareness fit",
      pacing: "Pacing",
      "visual-hierarchy": "Visual hierarchy",
      "captions-overlay": "Captions / overlay",
      "audio-quality": "Audio quality",
      "brand-presence": "Brand presence",
      "tracking-readiness-ref": "Tracking readiness ref",
    }[axis] ?? axis
  );
}
