-- =============================================================================
-- JUNO-06 — Server-side premium enforcement, revised 2026-09-23 after the
-- operator's reprise ruling: "un appel serveur préalable n'est pas une
-- autorisation de sécurité lorsque le résultat premium peut encore être
-- produit intégralement hors ligne." NOT APPLIED: local remediation mission;
-- production applies migrations through its own reviewed process.
--
-- WHAT THIS MIGATION NOW DOES (three things, in order):
--   1. it gives every policy row an `enforcement_class` — the honest record
--      of what the server decision actually protects, per feature;
--   2. it routes all 11 client features through enforce_premium_feature
--      (single atomic server decision: entitlement + free preview + quota +
--      replay window, 20260823000001) — keys, tiers and quotas unchanged
--      from what build 130 already observes;
--   3. it deletes dead seeds, and self-verifies.
--
-- THE THREE CLASSES (the vocabulary the whole codebase now shares —
-- validators, runbook and tests read THESE values):
--
--   server_enforced_data  — the premium RESULT is produced by the server
--      after authorization; the engine/corpus is absent from the APK, so a
--      patched client cannot produce it at all. Free preview spent by the
--      server decision itself (single enforce, in the edge).
--        weekly/monthly-tarot (tarot_cosmic, tarot_monthly): the reading is
--      drawn by the premium-tarot-reading edge from the shared engine
--      bundled server-side (tarot.generated.ts, generated by
--      scripts/build-edge-tarot.mjs — same contract as the astrology
--      bundle). The mobile bundle imports neither engine nor corpus.
--
--   server_metered_ui     — the ACCESS decision is real and server-side
--      (entitlement, preview, quota; the spend is server-recorded), but the
--      result remains computable or bundled offline: a patched APK CAN
--      produce it. Honest metering, not extraction protection. This is the
--      class the operator's ruling created: these features are metered by
--      the server and CIRCUMVENTABLE in the binary, and saying anything
--      stronger in this table would be security theater.
--        natal_chart       — the chart hydrates from the account's OWN
--                            stored birth_chart (get_my_full_profile) and
--                            the astrology engine is bundled for the
--                            synastry fallback; the premium compute exists
--                            in the binary.
--        synastry          — the reading is server-published (JUNO-01) but
--                            resolveSynastryView keeps a local fallback; the
--                            engines are bundled.
--        conversation_guide — the coach corpus (~35 KB) ships in the APK
--                            (English-only by design, both platforms); the
--                            server meters the taps, not the bytes.
--        daily_horoscope, monthly_horoscope — deterministic local labels
--                            seeded from the reader's sun sign; a server
--                            corpus exists (send-daily-horoscope) but the
--                            screens render the local generator.
--        lucky_days        — the WINDOWS const carries hardcoded phase
--                            values; not even computed.
--        date_planner      — PROMPT_KEYS/IDEA_KEYS local i18n arrays.
--
--   public_content        — the bytes are static public facts bundled in
--      every APK; the gate is presentation-level and a patched client is
--      indistinguishable from a paying one. The product decision (2026-09)
--      is to KEEP the gate for the honest, unpatched majority and record
--      here that it is not a boundary.
--        planetary_transits, retrograde_alerts — static THEMES consts; V2
--                            removed the ephemeris from both screens.
--
-- CLASS COUNTS this migration asserts at commit time (11 client features):
--   server_enforced_data: 2   (weekly-tarot, monthly-tarot)
--   server_metered_ui:    7
--   public_content:       2
-- The 'tarot' alias row mirrors tarot_monthly's class (it IS that feature,
-- called by old installed clients — build 130 contract, see below).
--
-- CLIENT-130 CONTRACT (unchanged by this migration):
--   * build 130 (Play 2.1.1) sees the same feature keys, tiers and quotas
--     it has always seen; the added column is invisible to it (no 130 read
--     or write path selects or sets enforcement_class);
--   * the legacy 'tarot' defensive alias is KEPT (old clients still call it;
--     deleting it would turn their gate into unknown_feature);
--   * every free_preview_quota that build 130's gate spends stays 1/day.
--
-- WHY 1/DAY EVERYWHERE: the legacy client path granted exactly one free view
-- per feature per day (PremiumContext.consumeTrial, `currentUsage >= 1`).
-- Server-enforcing these features without a preview quota would silently
-- DELETE the free trial — the exact regression class validate-premium-gating
-- was written to refuse.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 0) enforcement_class — added FIRST so every later statement can carry it.
--    Nullable during the transition, then constrained NOT NULL with a CHECK
--    at the end: a row without a class is a row whose protection is
--    undocumented, and the schema refuses it.
-- -----------------------------------------------------------------------------
ALTER TABLE public.premium_feature_policy
  ADD COLUMN IF NOT EXISTS enforcement_class TEXT;

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_enforced_data', updated_at = NOW()
 WHERE feature_key = 'tarot_monthly';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_enforced_data', updated_at = NOW()
 WHERE feature_key = 'tarot_cosmic';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_enforced_data', updated_at = NOW()
 WHERE feature_key = 'tarot';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'natal_chart';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'conversation_guide';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'synastry';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'daily_horoscope';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'monthly_horoscope';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'lucky_days';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE feature_key = 'date_planner';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'public_content', updated_at = NOW()
 WHERE feature_key = 'planetary_transits';

UPDATE public.premium_feature_policy
   SET enforcement_class = 'public_content', updated_at = NOW()
 WHERE feature_key = 'retrograde_alerts';

-- Rows that must NOT survive to the NOT NULL below:
--   1. the dead seeds of 20260419000006 (deleted here — BEFORE the column
--      becomes NOT NULL, or the ALTER fails on their NULL class; the delete
--      list moved up from its old section 3 for exactly that reason);
--   2. belt-and-braces: any OTHER historical row this file does not know
--      about (20260907's lesson: the repository is not always where the
--      change happened) is classified conservatively rather than breaking
--      the migration — unknown rows are not client features; the class
--      column is informational for them and the count assertions below are
--      scoped to the known catalog so they cannot lie about the 11.
DELETE FROM public.premium_feature_policy
 WHERE feature_key IN ('compatibility_details', 'priority_messages', 'likes_you_see_who');

UPDATE public.premium_feature_policy
   SET enforcement_class = 'server_metered_ui', updated_at = NOW()
 WHERE enforcement_class IS NULL;

-- Belt-and-braces: any row that slipped past the statements above (a future
-- seed, a manual insert) still cannot stay classless, and the value must be
-- one of the three documented classes.
ALTER TABLE public.premium_feature_policy
  ALTER COLUMN enforcement_class SET DEFAULT 'server_metered_ui';
ALTER TABLE public.premium_feature_policy
  ALTER COLUMN enforcement_class SET NOT NULL;
ALTER TABLE public.premium_feature_policy
  ADD CONSTRAINT premium_feature_policy_enforcement_class_check
  CHECK (enforcement_class IN ('server_enforced_data', 'server_metered_ui', 'public_content'))
  NOT VALID; -- validated below; kept NOT VALID so the ADD cannot fail on rows
             -- the UPDATEs above have not touched in a concurrent replay.

-- -----------------------------------------------------------------------------
-- 1) The rows that do not exist yet
--    (INSERT for existence; the preview quota is stated again as literal
--    targeted UPDATEs in section 2 — validate-premium-gating reads migration
--    TEXT and attributes quotas from per-key UPDATE statements, the same
--    convention as 20260828000001. Grouped VALUES carry the value at runtime
--    but the text scan cannot attribute it per key.)
--    enforcement_class is explicit per row — the honest class, never a
--    guessed default: the INSERT happens after the column exists (section 0).
-- -----------------------------------------------------------------------------
INSERT INTO public.premium_feature_policy
  (feature_key, required_tier, daily_quota, free_preview_quota, enforcement_class)
VALUES
  ('synastry',           'celestial', NULL, NULL, 'server_metered_ui'),
  ('daily_horoscope',    'celestial', NULL, 1, 'server_metered_ui'),
  ('monthly_horoscope',  'cosmic',    NULL, 1, 'server_metered_ui'),
  ('lucky_days',         'cosmic',    NULL, 1, 'server_metered_ui'),
  ('planetary_transits', 'cosmic',    NULL, 1, 'public_content'),
  ('retrograde_alerts',  'cosmic',    NULL, 1, 'public_content')
ON CONFLICT (feature_key) DO UPDATE
  SET required_tier      = EXCLUDED.required_tier,
      daily_quota        = EXCLUDED.daily_quota,
      free_preview_quota = EXCLUDED.free_preview_quota,
      enforcement_class  = EXCLUDED.enforcement_class,
      updated_at         = NOW();

-- -----------------------------------------------------------------------------
-- 2) Literal per-key quota statements (the validator's attribution contract)
-- -----------------------------------------------------------------------------
UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'daily_horoscope';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'monthly_horoscope';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'lucky_days';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'planetary_transits';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'retrograde_alerts';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'date_planner';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'tarot_monthly';

UPDATE public.premium_feature_policy
   SET free_preview_quota = 1, updated_at = NOW()
 WHERE feature_key = 'tarot_cosmic';

-- -----------------------------------------------------------------------------
-- 3) Self-verification (a migration that changes privileges must prove itself
--    — same house rule as 20260903000003). Asserts the CATALOG this change
--    claims to produce — rows, quotas, classes, counts — refusing to commit
--    anything else.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  v_expected TEXT[] := ARRAY[
    'natal_chart', 'conversation_guide', 'synastry',
    'daily_horoscope', 'monthly_horoscope', 'lucky_days',
    'planetary_transits', 'retrograde_alerts',
    'date_planner', 'tarot_monthly', 'tarot_cosmic', 'tarot'
  ];
  v_expected_class CONSTANT TEXT[] := ARRAY[
    'server_metered_ui',   -- natal_chart
    'server_metered_ui',   -- conversation_guide
    'server_metered_ui',   -- synastry
    'server_metered_ui',   -- daily_horoscope
    'server_metered_ui',   -- monthly_horoscope
    'server_metered_ui',   -- lucky_days
    'public_content',      -- planetary_transits
    'public_content',      -- retrograde_alerts
    'server_metered_ui',   -- date_planner
    'server_enforced_data',-- tarot_monthly
    'server_enforced_data',-- tarot_cosmic
    'server_enforced_data' -- tarot (alias of tarot_monthly)
  ];
  v_missing TEXT;
  v_bad RECORD;
  v_count INT;
BEGIN
  IF array_length(v_expected, 1) <> array_length(v_expected_class, 1) THEN
    RAISE EXCEPTION 'JUNO-06 self-check: key/class arrays out of sync';
  END IF;

  SELECT f INTO v_missing
    FROM unnest(v_expected) AS f
   WHERE NOT EXISTS (
     SELECT 1 FROM public.premium_feature_policy p WHERE p.feature_key = f
   )
   LIMIT 1;
  IF v_missing IS NOT NULL THEN
    RAISE EXCEPTION 'JUNO-06 self-check: policy row missing: %', v_missing;
  END IF;

  -- The honest classes, one by one. A drift here is the exact security
  -- theater this column exists to prevent: a feature labeled
  -- server_enforced_data whose result the APK can still produce.
  FOR v_bad IN
    SELECT feature_key, enforcement_class
      FROM public.premium_feature_policy
     WHERE feature_key = ANY (v_expected)
  LOOP
    IF v_bad.enforcement_class IS DISTINCT FROM
       v_expected_class[array_position(v_expected, v_bad.feature_key)] THEN
      RAISE EXCEPTION
        'JUNO-06 self-check: % must be %, got %',
        v_bad.feature_key,
        v_expected_class[array_position(v_expected, v_bad.feature_key)],
        v_bad.enforcement_class;
    END IF;
  END LOOP;

  -- The published counts, so a future row added without a class decision
  -- cannot land silently (the verdict "X/11 server-enforced" lives or dies
  -- here). SCOPED to the known catalog: a historical row this file does not
  -- know about was conservatively classed above and must not make the
  -- published counts lie about the 11 client features. 12 rows = 11 client
  -- features + the 'tarot' alias.
  SELECT COUNT(*) INTO v_count
    FROM public.premium_feature_policy
   WHERE feature_key = ANY (v_expected)
     AND enforcement_class = 'server_enforced_data';
  IF v_count <> 3 THEN
    RAISE EXCEPTION 'JUNO-06 self-check: expected 3 server_enforced_data rows (tarot_cosmic, tarot_monthly, alias), got %', v_count;
  END IF;
  SELECT COUNT(*) INTO v_count
    FROM public.premium_feature_policy
   WHERE feature_key = ANY (v_expected)
     AND enforcement_class = 'server_metered_ui';
  IF v_count <> 7 THEN
    RAISE EXCEPTION 'JUNO-06 self-check: expected 7 server_metered_ui rows, got %', v_count;
  END IF;
  SELECT COUNT(*) INTO v_count
    FROM public.premium_feature_policy
   WHERE feature_key = ANY (v_expected)
     AND enforcement_class = 'public_content';
  IF v_count <> 2 THEN
    RAISE EXCEPTION 'JUNO-06 self-check: expected 2 public_content rows, got %', v_count;
  END IF;

  -- Validate the CHECK constraint over the rows that exist now.
  EXECUTE 'ALTER TABLE public.premium_feature_policy
             VALIDATE CONSTRAINT premium_feature_policy_enforcement_class_check';

  FOR v_bad IN
    SELECT feature_key, required_tier, free_preview_quota
      FROM public.premium_feature_policy
     WHERE feature_key IN ('daily_horoscope','monthly_horoscope','lucky_days',
                           'planetary_transits','retrograde_alerts',
                           'date_planner','tarot_monthly','tarot_cosmic')
  LOOP
    IF v_bad.free_preview_quota IS DISTINCT FROM 1 THEN
      RAISE EXCEPTION 'JUNO-06 self-check: % must keep a 1/day free preview, got %',
        v_bad.feature_key, v_bad.free_preview_quota;
    END IF;
  END LOOP;

  FOR v_bad IN
    SELECT feature_key, required_tier
      FROM public.premium_feature_policy
     WHERE feature_key IN ('monthly_horoscope','lucky_days',
                           'planetary_transits','retrograde_alerts',
                           'date_planner','tarot_cosmic')
  LOOP
    IF v_bad.required_tier NOT IN ('cosmic', 'premium_plus') THEN
      RAISE EXCEPTION 'JUNO-06 self-check: % must stay cosmic, got %',
        v_bad.feature_key, v_bad.required_tier;
    END IF;
  END LOOP;

  FOR v_bad IN
    SELECT feature_key, free_preview_quota
      FROM public.premium_feature_policy
     WHERE feature_key = 'synastry'
  LOOP
    IF v_bad.free_preview_quota IS NOT NULL THEN
      RAISE EXCEPTION 'JUNO-06 self-check: synastry must keep NULL preview (per-target contract lives in synastry_free_grant)';
    END IF;
  END LOOP;
END;
$$;

commit;
